---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: El plugin de SnapCenter para Microsoft SQL Server necesita backups de registros de transacciones para ejecutar operaciones de restauración de último minuto, que restauran la base de datos a un momento entre dos backups completos. 
---
= Cuánto tiempo se retienen los backups de registros de transacciones en el sistema de almacenamiento de origen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El plugin de SnapCenter para Microsoft SQL Server necesita backups de registros de transacciones para ejecutar operaciones de restauración de último minuto, que restauran la base de datos a un momento entre dos backups completos.

Por ejemplo, si el plugin para SQL Server hizo un backup completo a las 8:00 y otro backup completo a las 8:00 p. m., se podía utilizar el último backup de registros de transacciones para restaurar la base de datos a cualquier momento entre las 5:00 y las 5:00 Si no se cuenta con registros de transacciones, el plugin para SQL Server solamente puede ejecutar operaciones de restauración a un momento específico, que restaura una base de datos al momento en que el plugin para SQL Server finalizó un backup completo.

En general, se requieren operaciones de restauración de último minuto únicamente durante un día o dos. De forma predeterminada, SnapCenter conserva un mínimo de dos días.
