---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: El plugin para SQL Server se integra con Microsoft SQL Server en el host Windows y con la tecnología Snapshot de NetApp en el sistema de almacenamiento. Para trabajar con el plugin para SQL Server, se utiliza la interfaz de SnapCenter. 
---
= Funciones del plugin de SnapCenter para Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El plugin para SQL Server se integra con Microsoft SQL Server en el host Windows y con la tecnología Snapshot de NetApp en el sistema de almacenamiento. Para trabajar con el plugin para SQL Server, se utiliza la interfaz de SnapCenter.

El plugin para SQL Server incluye estas características principales:

* *Interfaz gráfica de usuario unificada con tecnología SnapCenter*
+
La interfaz de SnapCenter ofrece estandarización y consistencia entre plugins y entornos. La interfaz de SnapCenter permite completar procesos de backup y restauración consistentes entre plugins, utilizar informes centralizados, utilizar informes centralizados, utilizar visualizaciones de consola rápidas, configurar el RBAC y supervisar trabajos en todos los plugins. SnapCenter además ofrece gestión de políticas y programación centralizada para admitir operaciones de backup y clonado.

* *Administración central automatizada*
+
Es posible programar backups rutinarios de SQL Server, configurar retención de backups basada en políticas y configurar operaciones de restauración de momento específico y de último minuto. Si desea supervisar de manera proactiva el entorno de SQL Server, configure SnapCenter para que envíe alertas por correo electrónico.

* *Tecnología NetApp instantánea no disruptiva*
+
El plugin para SQL Server utiliza la tecnología de Snapshot de NetApp con el plugin de NetApp SnapCenter para Microsoft Windows. Esto permite realizar backups de bases de datos en cuestión de segundos y restaurarlos rápidamente sin necesidad de dejar sin conexión a SQL Server. Las snapshots consumen un espacio de almacenamiento mínimo.



Además de estas funciones principales, el plugin para SQL Server ofrece los siguientes beneficios:

* Compatibilidad con flujos de trabajo de backup, restauración, clonado y verificación
* Seguridad compatible con RBAC y delegación de roles centralizada
* Creación de copias de bases de datos de producción con gestión eficiente del espacio y en un momento específico con fines de prueba o de extracción de datos con la tecnología FlexClone de NetApp
+
Se requiere una licencia de FlexClone en el sistema de almacenamiento donde está el clon.

* Verificación de backups no disruptiva y automatizada
* Capacidad para ejecutar varios backups al mismo tiempo entre varios servidores
* Cmdlets de PowerShell para crear scripts de operaciones de backup, verificación, restauración y clonado
* Compatibilidad con grupos de disponibilidad (AG) AlwaysOn en SQL Server para acelerar las operaciones de configuración, backup y restauración de AG
* Base de datos en memoria y extensión de espacio libre (BPE) como parte de SQL Server 2014
* Compatibilidad con backup de LUN y VMDK
* Compatibilidad con infraestructuras físicas y virtualizadas
* Compatibilidad con iSCSI, Fibre Channel, FCoE, asignación de dispositivos sin formato (RDM) y VMDK sobre NFS y VMFS
+

NOTE: Los volúmenes NAS deben tener una política de exportación predeterminada en la máquina virtual de almacenamiento (SVM).

* Compatibilidad con FileStream y grupos de archivos en bases de datos independientes de SQL Server.

