---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: Proporciona instrucciones para preparar la instalación del servidor de SnapCenter y el plugin de SnapCenter para Microsoft SQL Server. 
---
= Prepare la instalación del servidor de SnapCenter y del plugin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Proporciona un conjunto condensado de instrucciones de preparación para instalar SnapCenter Server y el plugin de SnapCenter para Microsoft SQL Server.



== Requisitos de dominio y grupo de trabajo

SnapCenter Server se puede instalar en sistemas que estén en un dominio o en un grupo de trabajo.

Si utiliza un dominio de Active Directory, debe utilizar un usuario de dominio con derechos de administrador local. El usuario de dominio debe ser miembro del grupo de administrador local en el host de Windows.

Si utiliza grupos de trabajo, debe utilizar una cuenta local con derechos de administrador locales.



== Requisitos de licencia

El tipo de licencia que instale dependerá del entorno.

[cols="1,3"]
|===
| Licencia | Donde se la requiere 


 a| 
Basado en controladora estándar de SnapCenter
 a| 
Necesario para las controladoras de almacenamiento FAS o AFF

La licencia estándar de SnapCenter es una licencia basada en la controladora y se incluye como parte del paquete Premium. Si tiene la licencia de conjunto de SnapManager, también obtendrá el derecho de licencia estándar de SnapCenter. Si desea instalar SnapCenter a modo de prueba con almacenamiento FAS o AFF, puede obtener una licencia de evaluación Premium Bundle poniéndose en contacto con el representante de ventas.



 a| 
SnapCenter basada en capacidad estándar
 a| 
Necesario con ONTAP Select y Cloud Volumes ONTAP

Si es cliente de Cloud Volumes ONTAP o ONTAP Select, necesita adquirir una licencia basada en capacidad por TB en función de los datos gestionados por SnapCenter. De forma predeterminada, SnapCenter envía una licencia de prueba integrada basada en capacidad estándar de SnapCenter de 90 días y 100 TB. Si desea obtener más detalles, póngase en contacto con el representante de ventas.



 a| 
SnapMirror o SnapVault
 a| 
ONTAP

Se requieren licencias de SnapMirror o SnapVault si la replicación se habilita en SnapCenter.



 a| 
Licencias adicionales (opcional)
 a| 
Consulte link:../install/concept_snapcenter_licenses.html["Licencias SnapCenter"^].



 a| 
Licencias estándar de SnapCenter (opcional)
 a| 
Destinos secundarios


NOTE: Se recomienda, pero no es obligatorio, añadir licencias estándar de SnapCenter a destinos secundarios. Si las licencias estándar de SnapCenter están deshabilitadas en destinos secundarios, no puede usar SnapCenter para realizar un backup de los recursos en el destino secundario después de realizar una operación de conmutación al nodo de respaldo. Sin embargo, se requiere una licencia de FlexClone en destinos secundarios para realizar operaciones de clonado y verificación.

|===


== Requisitos del host y puerto

Para ver los requisitos mínimos del ONTAP y el complemento de la aplicación, consulte https://imt.netapp.com/matrix/imt.jsp?components=105961;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^].

[cols="1,3"]
|===
| Hosts | Requisitos mínimos 


 a| 
Sistema operativo (64 bits)
 a| 
Consulte https://imt.netapp.com/matrix/imt.jsp?components=105961;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^]



 a| 
CPU
 a| 
* Host del servidor: 4 núcleos
* Host de plugin: 1 núcleo




 a| 
RAM
 a| 
* Host del servidor: 8 GB
* Host de plugins: 1 GB




 a| 
Espacio en el disco duro
 a| 
Host del servidor:

* 4 GB para software y registros de SnapCenter Server
* 6 GB para el repositorio de SnapCenter
* Cada host de plugin: 2 GB para la instalación y los registros de un plugin, esto es obligatorio solo si el plugin está instalado en un host dedicado.




 a| 
Bibliotecas de terceros
 a| 
Requerida en el host de servidor de SnapCenter y el host de plugins:

* Microsoft .NET Framework 4.7.2 o posterior
* Windows Management Framework (WMF) 4.0 o posterior
* PowerShell 4.0 o posterior




 a| 
Exploradores
 a| 
Chrome, Internet Explorer y Microsoft Edge

|===
[cols="1,3"]
|===
| Tipo de puerto | Puerto predeterminado 


 a| 
Puerto SnapCenter
 a| 
8146 (HTTPS), bidireccional, personalizable, como en la URL _\https://server:8146_



 a| 
Puerto de comunicación SMCore de SnapCenter
 a| 
8145 (HTTPS), bidireccional, personalizable



 a| 
Base de datos del repositorio
 a| 
3306 (HTTPS), bidireccional



 a| 
Hosts de plugins de Windows
 a| 
135 DE FEBRERO DE 445 (TCP)

Además de los puertos 135 y 445, el intervalo de puertos dinámico especificado por Microsoft también debería estar abierto. Operaciones de instalación remota Utilice el servicio Instrumental de administración de Windows (WMI), que busca dinámicamente este intervalo de puertos.

Para obtener información sobre el intervalo de puertos dinámicos admitido, consulte https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Descripción general del servicio y requisitos de puertos de red para Windows"^].



 a| 
Plugin de SnapCenter para Windows
 a| 
8145 (HTTPS), bidireccional, personalizable



 a| 
Puerto de comunicación del clúster de ONTAP o de SVM
 a| 
443 (HTTPS), bidireccional; 80 (HTTP), bidireccional

El puerto se utiliza para establecer la comunicación entre el host del servidor de SnapCenter, el host del plugin y SVM o el clúster de ONTAP.

|===


== Requisitos del plugin de SnapCenter para Microsoft SQL Server

Debe tener un usuario con privilegios de administrador local y permisos locales para iniciar sesión en el host remoto. Si gestiona nodos de clúster, necesita un usuario con privilegios de administrador para todos los nodos del clúster.

Debe tener un usuario con permisos de administrador del sistema en SQL Server. El plugin utiliza Microsoft VDI Framework, para lo que se requiere acceso de sysadmin.

Si utilizaba SnapManager para Microsoft SQL Server y desea importar datos de SnapManager para Microsoft SQL Server a SnapCenter, consulte link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["Importación de backups archivados"^]
