---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: Proporciona instrucciones para instalar SnapCenter Server y el plugin de SnapCenter para Microsoft SQL Server. 
---
= Inicio rápido de instalar el plugin de SnapCenter para SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ofrece un conjunto condensado de instrucciones de instalación para instalar SnapCenter Server y el plugin de SnapCenter para Microsoft SQL Server.



== Preparación de la instalación



=== Requisitos de dominio y grupo de trabajo

SnapCenter Server se puede instalar en sistemas que estén en un dominio o en un grupo de trabajo.

Si utiliza un dominio de Active Directory, debe utilizar un usuario de dominio con derechos de administrador local. El usuario de dominio debe ser miembro del grupo de administrador local en el host de Windows.

Si utiliza grupos de trabajo, debe utilizar una cuenta local con derechos de administrador locales.



=== Requisitos de licencia

El tipo de licencia que instale dependerá del entorno.

[cols="1,3"]
|===
| Licencia | Donde se la requiere 


 a| 
Basado en controladora estándar de SnapCenter
 a| 
Es necesario para las controladoras de almacenamiento FAS, AFF o All SAN Array (ASA)

La licencia estándar de SnapCenter es una licencia basada en la controladora y se incluye como parte del paquete Premium. Si tiene la licencia de conjunto de SnapManager, también obtendrá el derecho de licencia estándar de SnapCenter.
Si desea instalar SnapCenter a modo de prueba con almacenamiento FAS, AFF o ASA, puede obtener una licencia de evaluación Premium Bundle poniéndose en contacto con el representante de ventas.



 a| 
SnapCenter basada en capacidad estándar
 a| 
Necesario con ONTAP Select y Cloud Volumes ONTAP

Si es cliente de Cloud Volumes ONTAP o ONTAP Select, necesita adquirir una licencia basada en capacidad por TB en función de los datos gestionados por SnapCenter. De forma predeterminada, SnapCenter envía una licencia de prueba integrada basada en capacidad estándar de SnapCenter de 90 días y 100 TB. Si desea obtener más detalles, póngase en contacto con el representante de ventas.



 a| 
SnapMirror o SnapVault
 a| 
ONTAP

Se requieren licencias de SnapMirror o SnapVault si la replicación se habilita en SnapCenter.



 a| 
Licencias adicionales (opcional)
 a| 
Consulte link:../install/concept_snapcenter_licenses.html["Licencias SnapCenter"^].



 a| 
Licencias estándar de SnapCenter (opcional)
 a| 
Destinos secundarios


NOTE: Se recomienda, pero no es obligatorio, añadir licencias estándar de SnapCenter a destinos secundarios. Si las licencias estándar de SnapCenter están deshabilitadas en destinos secundarios, no puede usar SnapCenter para realizar un backup de los recursos en el destino secundario después de realizar una operación de conmutación al nodo de respaldo. Sin embargo, se requiere una licencia de FlexClone en destinos secundarios para realizar operaciones de clonado y verificación.

|===


=== Requisitos del host y puerto

Para ver los requisitos mínimos del ONTAP y el complemento de la aplicación, consulte https://imt.netapp.com/matrix/imt.jsp?components=112389;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^].

[cols="1,3"]
|===
| Hosts | Requisitos mínimos 


 a| 
Sistema operativo (64 bits)
 a| 
Consulte https://imt.netapp.com/matrix/imt.jsp?components=108408;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^]



 a| 
CPU
 a| 
* Host del servidor: 4 núcleos
* Host de plugin: 1 núcleo




 a| 
RAM
 a| 
* Host del servidor: 8 GB
* Host de plugins: 1 GB




 a| 
Espacio en el disco duro
 a| 
Host del servidor:

* 4 GB para software y registros de SnapCenter Server
* 6 GB para el repositorio de SnapCenter
* Cada host de plugin: 2 GB para la instalación y los registros de un plugin, esto es obligatorio solo si el plugin está instalado en un host dedicado.




 a| 
Bibliotecas de terceros
 a| 
Requerida en el host de servidor de SnapCenter y el host de plugins:

* Microsoft .NET Framework 4.7.2 o posterior
* Windows Management Framework (WMF) 4.0 o posterior
* PowerShell 4.0 o posterior




 a| 
Exploradores
 a| 
Chrome, Internet Explorer y Microsoft Edge

|===
[cols="1,3"]
|===
| Tipo de puerto | Puerto predeterminado 


 a| 
Puerto SnapCenter
 a| 
8146 (HTTPS), bidireccional, personalizable, como en la URL _\https://server:8146_



 a| 
Puerto de comunicación SMCore de SnapCenter
 a| 
8145 (HTTPS), bidireccional, personalizable



 a| 
Base de datos del repositorio
 a| 
3306 (HTTPS), bidireccional



 a| 
Hosts de plugins de Windows
 a| 
135 DE FEBRERO DE 445 (TCP)

Además de los puertos 135 y 445, el intervalo de puertos dinámico especificado por Microsoft también debería estar abierto. Operaciones de instalación remota Utilice el servicio Instrumental de administración de Windows (WMI), que busca dinámicamente este intervalo de puertos.

Para obtener información sobre el intervalo de puertos dinámicos admitido, consulte https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Descripción general del servicio y requisitos de puertos de red para Windows"^].



 a| 
Plugin de SnapCenter para Windows
 a| 
8145 (HTTPS), bidireccional, personalizable



 a| 
Puerto de comunicación del clúster de ONTAP o de SVM
 a| 
443 (HTTPS), bidireccional; 80 (HTTP), bidireccional

El puerto se utiliza para establecer la comunicación entre el host del servidor de SnapCenter, el host del plugin y SVM o el clúster de ONTAP.

|===


=== Requisitos del plugin de SnapCenter para Microsoft SQL Server

Debe tener un usuario con privilegios de administrador local y permisos locales para iniciar sesión en el host remoto. Si gestiona nodos de clúster, necesita un usuario con privilegios de administrador para todos los nodos del clúster.

Debe tener un usuario con permisos de administrador del sistema en SQL Server. El plugin utiliza Microsoft VDI Framework, para lo que se requiere acceso de sysadmin.



== Instale el servidor SnapCenter



=== Paso 1: Descargue e instale el servidor SnapCenter

. Descargue el paquete de instalación del servidor SnapCenter desde el https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Sitio de soporte de NetApp"^] y, a continuación, haga doble clic en el archivo exe.
+
Tras iniciar la instalación, se realizan todas las comprobaciones previas y si los requisitos mínimos no son los correctos, se muestran mensajes de error o de advertencia. Puede ignorar los mensajes de advertencia y continuar con la instalación; sin embargo, los errores deben corregirse.

. Revise los valores rellenados previamente necesarios para la instalación del servidor SnapCenter y modifíquelos si es necesario.
+
No es necesario especificar la contraseña para la base de datos de repositorio del servidor MySQL. Durante la instalación del servidor SnapCenter, la contraseña se genera automáticamente.

+

NOTE: El carácter especial “%” no se admite en la ruta personalizada para la instalación. Si incluye “%” en la ruta, la instalación falla.

. Haga clic en *instalar ahora*.




=== Paso 2: Inicie sesión en SnapCenter

. Inicie SnapCenter desde un acceso directo en el escritorio del host o desde la dirección URL proporcionada por la instalación (_\https://server:8146_ para el puerto predeterminado 8146 donde está instalado SnapCenter Server).
. Introduzca las credenciales.
+
Para un formato de nombre de usuario de administrador de dominio integrado, utilice: _NetBIOS\<username>_ o _<username>@<domain>_ o _<DomainFQDN>\<username>_.

+
Para un formato de nombre de usuario de administrador local integrado, utilice _<username>_.

. Haga clic en *Iniciar sesión*.




=== Paso 3: Añada una licencia estándar basada en controladora de SnapCenter

. Inicie sesión en la controladora con la línea de comandos de ONTAP e introduzca lo siguiente:
+
`system license add -license-code <license_key>`

. Compruebe la licencia:
+
`license show`





=== Paso 4: Añadir una licencia basada en capacidad de SnapCenter

. En el panel izquierdo de la GUI de SnapCenter, haga clic en *Configuración > Software* y, a continuación, en la sección Licencia, haga clic en *+*.
. Seleccione uno de los dos métodos para obtener la licencia:
+
** Introduzca sus credenciales de inicio de sesión en el sitio de soporte de NetApp para importar licencias.
** Desplácese hasta la ubicación del archivo de licencia de NetApp y haga clic en *Open*.


. En la página Notifications del asistente, utilice el umbral de capacidad predeterminado del 90 %.
. Haga clic en *Finalizar*.




=== Paso 5: Configure las conexiones al sistema de almacenamiento

. En el panel izquierdo, haga clic en *sistemas de almacenamiento > Nuevo*.
. En la página Add Storage System, realice lo siguiente:
+
.. Introduzca el nombre o la dirección IP del sistema de almacenamiento.
.. Introduzca las credenciales que se utilizan para acceder al sistema de almacenamiento.
.. Active las casillas para habilitar el sistema de gestión de eventos (EMS) y AutoSupport.


. Haga clic en *más opciones* si desea modificar los valores predeterminados asignados a la plataforma, el protocolo, el puerto y el tiempo de espera.
. Haga clic en *Enviar*.




== Instale el plugin para Microsoft SQL Server



=== Paso 1: Configure credenciales Run As para instalar el plugin para Microsoft SQL Server

. En el panel izquierdo, haga clic en *Configuración > credenciales > Nuevo*.
. Introduzca las credenciales.
+
Para un formato de nombre de usuario de administrador de dominio integrado, utilice: _NetBIOS\<username>_ o _<username>@<domain>_ o _<DomainFQDN>\<username>_.

+
Para un formato de nombre de usuario de administrador local integrado, utilice _<username>_.





=== Paso 2: Añada un host e instale el plugin para Microsoft SQL Server

. En el panel izquierdo de la interfaz gráfica de usuario de SnapCenter, haga clic en *hosts > Managed hosts > Add*.
. En la página hosts del asistente, realice lo que sigue:
+
.. Host Type: Seleccione el tipo de host Windows.
.. Nombre de host: Utilice el host SQL o especifique el FQDN de un host Windows dedicado.
.. Credenciales: Seleccione el nombre de credencial válido del host que creó o cree nuevas credenciales.


. En la sección Select Plug-ins to Install, seleccione *Microsoft SQL Server*.
. Haga clic en *más opciones* para especificar los siguientes detalles:
+
.. Puerto: Conserve el número de puerto predeterminado o especifique el número de puerto.
.. Ruta de instalación: La ruta predeterminada es _C:\Program Files\NetApp\SnapCenter_. Opcionalmente, puede personalizar la ruta.
.. Añadir todos los hosts del clúster: Seleccione esta casilla de comprobación si está usando SQL en WSFC.
.. Skip preinstall checks: Seleccione esta casilla de comprobación si ya ha instalado los plugins manualmente o no desea validar si el host cumple los requisitos para instalar el plugin.


. Haga clic en *Enviar*.

