---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: Es posible crear una política de backup para el recurso o el grupo de recursos antes de usar SnapCenter con el fin de realizar un backup de los recursos de SQL Server. También es posible crear una política de backup en el momento de crear un grupo de recursos o realizar un backup de un único recurso. 
---
= Crear políticas de backup para bases de datos de SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear una política de backup para el recurso o el grupo de recursos antes de usar SnapCenter con el fin de realizar un backup de los recursos de SQL Server. También es posible crear una política de backup en el momento de crear un grupo de recursos o realizar un backup de un único recurso.

.Antes de empezar
* Debe estar definida la estrategia de protección de datos.
* Debe haberse preparado para la protección de datos completando ciertas tareas, como instalar SnapCenter, añadir hosts, identificar recursos y crear conexiones con el sistema de almacenamiento.
* Debe haber configurado el directorio de registro del host para backup de registro.
* Debe haber actualizado (detectado) los recursos de SQL Server.
* Si va a replicar snapshots en un reflejo o almacén, el administrador de SnapCenter debe haberle asignado las máquinas virtuales de almacenamiento (SVM) para los volúmenes de origen y de destino.
+
Para obtener información sobre cómo los administradores asignan recursos a los usuarios, consulte la información de instalación de SnapCenter.

* Si desea ejecutar los scripts de PowerShell en scripts previos y posteriores, debe establecer el valor del parámetro usePowershellProcessforScripts en TRUE en el archivo web.config.
+
El valor predeterminado es FALSE.

* Revise los requisitos previos y las limitaciones específicos de SnapMirror Active Sync. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"].


.Acerca de esta tarea
* Una política de backup es un conjunto de reglas que rigen cómo gestionar y conservar backups, y con qué frecuencia se realizará un backup del recurso o del grupo de recursos. De forma adicional, se puede especificar la configuración de replicación y script. Puede especificar opciones en la política para ahorrar tiempo cuando desee reutilizarla con otro grupo de recursos.
+
LA RUTA_DE_SCRIPTS se define mediante la clave PredefinedWindowsScriptsDirectory ubicada en el archivo SMCoreServiceHost.exe.Config del host del plugin.

+
Si es necesario, puede cambiar esta ruta y reiniciar el servicio SMcore. Se recomienda utilizar la ruta predeterminada para la seguridad.

+
El valor de la tecla se puede mostrar desde swagger a través de la API: API /4.7/config settings

+
Puede usar LA API GET para mostrar el valor de la clave. No se admite LA CONFIGURACIÓN de API.

* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
+
Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención.  Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.

+
Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.







== Paso 1: Crear nombre de política

. En el panel de navegación izquierdo, selecciona *Configuración*.
. En la página Configuración, selecciona *Políticas*.
. Selecciona *Nuevo*.
. En la página *Name*, introduzca el nombre y los detalles de la política.




== Paso 2: Configure las opciones de política

. En la página Policy type, realice los siguientes pasos:
+
.. Seleccione el tipo de almacenamiento.
.. Seleccione el ámbito de la política.
+
[role="tabbed-block"]
====
.Backup completo y backup de registros
--
Realizar un backup de los archivos de la base de datos y los registros de transacciones y para truncar los registros de transacciones.

... Seleccione *copia de seguridad completa y copia de seguridad de registro*.
... Introduzca el número máximo de bases de datos que se deben incluir en un backup para cada Snapshot.
+

NOTE: Debe aumentar dicho valor si desea ejecutar varias operaciones de backup en forma simultánea.



--
.Backup completo
--
Realice un backup de los archivos de la base de datos.

... Seleccione *copia de seguridad completa*.
... Introduzca el número máximo de bases de datos que se deben incluir en un backup para cada Snapshot.
El valor predeterminado es 100
+

NOTE: Debe aumentar dicho valor si desea ejecutar varias operaciones de backup en forma simultánea.



--
.Backup de registros
--
... Realice un backup de los registros de transacciones.
... Seleccione *copia de seguridad de registro*.


--
.Copiar solo backup
--
... Si va a realizar una copia de seguridad de los recursos mediante otra aplicación de copia de seguridad, seleccione *copia sólo copia de seguridad*.


Mantener los registros de transacciones intactos permite a cualquier aplicación de backup restaurar la base de datos. Por lo general, no debe utilizar la opción de solo copiar en ningún otro caso.


NOTE: Microsoft SQL no es compatible con la opción *copia de seguridad sólo* junto con la opción *copia de seguridad completa y copia de seguridad de registro* para almacenamiento secundario.

--
====






== Paso 3: Configure los ajustes del grupo de disponibilidad

. En la sección Availability Group Settings, realice las siguientes acciones:
+
.. Backup únicamente en la réplica de backup preferida.
+
Seleccione esta opción para realizar un backup solo en la réplica de backup preferida. La réplica de backup preferida se decide mediante las preferencias de backup configuradas para el AG en SQL Server.

.. Seleccione replicas for backup.
+
Seleccione la réplica principal o secundaria del AG para el backup.

.. Seleccionar prioridad de backup (prioridad de backup mínima y máxima)
+
Indique un número mínimo y un número máximo de prioridad de backup mediante los cuales se determine la réplica de AG para backup. Por ejemplo, puede tener una prioridad mínima de 10 y una prioridad máxima de 50. En este caso, se tendrán en cuenta para el backup todas las réplicas de AG que tengan una prioridad superior a 10 e inferior a 50.

+
De forma predeterminada, la prioridad mínima es 1 y la máxima es 100.



+

NOTE: En las configuraciones de clúster, los backups se conservan en cada nodo del clúster según la configuración de retención establecida en la política. Si cambia el nodo propietario del AG, las copias de seguridad se realizan según la configuración de retención y se conservarán las copias de seguridad del nodo propietario anterior. La retención de AG solo se aplica a nivel de nodo.





== Paso 4: Configure los ajustes de Snapshot y replicación

. En la página Snapshot and Replication, realice los siguientes pasos:
+
.. Especifique el tipo de programa seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
+
Solo puede seleccionar un tipo de programación por política.

+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de backup mientras crea un grupo de recursos. De este modo, se pueden crear grupos de recursos que comparten la misma política y frecuencia de backup, pero se pueden asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.







== Paso 5: Configure los ajustes de retención actualizados al minuto

. En la sección Up-to-the minute retention settings, según el tipo de backup seleccionado en la página de tipo de backup, realice una o más de las siguientes acciones:


[role="tabbed-block"]
====
.Número específico de copias
--
Conserve únicamente una cantidad específica de snapshots.

. Seleccione la opción *Keep log backups aplicable a Last <number> Days* y especifique el número de días que se conservarán. Si se acerca a ese límite, tal vez deba eliminar copias más antiguas.


--
.Número específico de días
--
Retener las copias de backup por una cantidad determinada de días.

. Seleccione la opción *Keep log backups applicable to last <number> days of full backups* y especifique el número de días que se conservarán las copias de seguridad de registros.


--
====


== Paso 6: Configurar los ajustes de la instantánea

. Para la configuración de retención de backup completo, realice las siguientes acciones:
+
.. Especifique el número total de snapshots que desea conservar
+
... Para especificar el número de instantáneas a conservar, seleccione *Copias a conservar*.
... Si la cantidad de copias de Snapshot supera el número especificado, las copias de Snapshot se eliminan empezando por las más antiguas.
+

IMPORTANT: De forma predeterminada, el valor del número de retención se establece en 2. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva snapshot en el destino.

+

NOTE: El valor de retención máximo es 1018. Se producirá un error en los backups si la retención se establece con un valor superior al admitido por la versión de NetApp ONTAP subyacente.







. El tiempo que se conservan las snapshots
+
.. Si desea especificar el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas, seleccione *Retener copias para*.


. Seleccione *Período de bloqueo de copia de instantánea* y especifique la duración en días, meses o años.
+
El período de retención de SnapLock debe ser inferior a 100 años.

. Seleccione una etiqueta de política.
+

NOTE: Puede asignar etiquetas SnapMirror a instantáneas principales para replicación remota, lo que permite que las instantáneas principales descarguen la operación de replicación de instantáneas de SnapCenter a los sistemas secundarios de ONTAP .  Esto se puede hacer sin habilitar la opción SnapMirror o SnapVault en la página de políticas.





== Paso 7: Configure las opciones de replicación secundaria

. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:


[role="tabbed-block"]
====
.Actualice SnapMirror
--
Actualice SnapMirror después de crear una copia snapshot local.

. Seleccione esta opción para crear copias de SnapMirror de conjuntos de backups en otro volumen (SnapMirror).
+
Esta opción debe estar habilitada para la sincronización activa de SnapMirror.

+
Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

+
Consulte link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Consulte los backups y los clones de SQL Server en la página Topology"].



--
.Actualizar SnapVault
--
Actualice SnapVault después de crear una copia snapshot.

. Seleccione esta opción para realizar una replicación de backup de disco a disco.
+
Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

+
Cuando SnapLock se configura solo en el secundario desde ONTAP conocido como Almacén de SnapLock, al hacer clic en el botón *Refrescar* de la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

+
Para obtener más información sobre el Almacén SnapLock, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Confirmar copias Snapshot a WORM en un destino de almacén"]

+
Consulte link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Consulte los backups y los clones de SQL Server en la página Topology"].



--
.Recuento de reintentos de error
--
. Introduzca el número de intentos de replicación que deben producirse antes de que se interrumpa el proceso.


--
====


== Paso 8: Configurar los ajustes de script

. En la página Script, introduzca la ruta y los argumentos del script previo o script posterior que se deben ejecutar antes o después de la operación de backup, según corresponda.
+
Por ejemplo, se puede ejecutar un script para actualizar capturas SNMP, automatizar alertas y enviar registros.

+

NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.

+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para que el almacenamiento secundario no alcance el límite máximo de Snapshots.





== Paso 9: Configure los ajustes de verificación

En la página Verification, realice los siguientes pasos:

. En la sección Run verification for following backup schedules, seleccione la frecuencia de backup.
. En la sección Database consistency check options, realice las siguientes acciones:
+
.. Limitar la estructura de integridad a la estructura física de la base de datos (PHYSICAL_ONLY)
+
... Seleccione *limitar la estructura de integridad a la estructura física de la base de datos (PHYSICAL_ONLY)* para limitar la comprobación de integridad a la estructura física de la base de datos y detectar páginas dañadas, errores de sumas de comprobación y errores de hardware habituales que afecten a la base de datos.


.. Suprimir todos los mensajes de información (NO INFOMSGS)
+
... Seleccione *Supress all information messages (NO INFOMSGS)* para suprimir todos los mensajes informativos. Seleccionado de forma predeterminada.


.. Visualizar todos los mensajes de error notificados por objeto (ALL_ERRORMSGS)
+
... Seleccione *Display all reported error messages per object (ALL_ERRORMSGS)* para visualizar todos los errores notificados por objeto.


.. No comprobar los índices no almacenados en clúster (NOINDEX)
+
... Seleccione *no comprobar los índices no almacenados en clúster (NOINDEX)* si no desea comprobar los índices no almacenados en clúster. La base de datos de SQL Server utiliza la comprobación de la consistencia de base de datos de Microsoft SQL Server para comprobar la integridad lógica y física de los objetos de la base de datos.


.. Limitar las comprobaciones y obtener los bloqueos en lugar de utilizar una instantánea de la base de datos interna (TABLOCK)
+
... Seleccione *Limitar las comprobaciones y obtener los bloqueos en lugar de utilizar una copia Snapshot interna de la base de datos (TABLOCK)* para limitar las comprobaciones y obtener bloqueos en lugar de utilizar una instantánea interna de la base de datos.




. En la sección *Backup de registro*, seleccione *verificar copia de seguridad de registro al finalizar* para verificar la copia de seguridad de registro al finalizar.
. En la sección *Verification script settings*, introduzca la ruta de acceso y los argumentos del script previo o posterior que deben ejecutarse antes o después de la operación de verificación, respectivamente.
+

NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.





== Paso 10: Resumen de la revisión

. Revisa el resumen y luego selecciona *Finalizar*.

