---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords: migrate resources 
summary: 'Después de haber aprovisionado el sistema de almacenamiento de NetApp con el plugin de SnapCenter para Microsoft Windows, puede migrar los recursos al sistema de almacenamiento de NetApp o de un LUN de NetApp a otro LUN de NetApp mediante la interfaz gráfica de usuario \(GUI\) de SnapCenter o los cmdlets de PowerShell.' 
---
= Migrar recursos al sistema de almacenamiento de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de haber aprovisionado el sistema de almacenamiento de NetApp con el plugin de SnapCenter para Microsoft Windows, puede migrar los recursos al sistema de almacenamiento de NetApp o de un LUN de NetApp a otro LUN de NetApp mediante la interfaz gráfica de usuario (GUI) de SnapCenter o los cmdlets de PowerShell.

.Antes de empezar
* Debe haber añadido sistemas de almacenamiento al servidor SnapCenter.
* Debe haber actualizado (detectado) los recursos de SQL Server.


La mayoría de los campos en estas páginas del asistente son claros y explicativos. La siguiente información describe algunos de los campos que pueden requerir explicación.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *Recursos* y, a continuación, seleccione el plugin adecuado en la lista.
. En la página Resources, seleccione *Database* o *Instance* en la lista desplegable *View*.
. Seleccione la base de datos o la instancia de la lista y haga clic en *migrar*.
. En la página Resources, realice las siguientes acciones:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
*Nombre de la base de datos* (opcional)
 a| 
Si ha seleccionado una instancia para la migración, debe seleccionar las bases de datos de esa instancia en la lista desplegable *bases de datos*.



 a| 
*Elija Destinos*
 a| 
Seleccione la ubicación objetivo para los archivos de datos y de registro.

Los archivos de datos y de registro se mueven a la carpeta Data and Log correspondiente en la unidad de NetApp seleccionada. Si falta alguna carpeta en la estructura de carpetas, se crea una carpeta y se migra el recurso.



 a| 
*Mostrar detalles del archivo de base de datos* (opcional)
 a| 
Seleccione esta opción si desea migrar varios archivos de una única base de datos.


NOTE: Esta opción no se muestra cuando selecciona el recurso *Instance*.



 a| 
*Opciones*
 a| 
Seleccione *Delete copy of Migrated Database at original Location* para eliminar la copia de la base de datos del origen.

Opcional: *EJECUTE ESTADÍSTICAS DE ACTUALIZACIÓN en tablas antes de desvincular la base de datos*.

|===
. En la página Verify, realice las siguientes acciones:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
*Opciones de comprobación de consistencia de base de datos*
 a| 
Seleccione *Ejecutar antes de* para comprobar la integridad de la base de datos antes de la migración. Seleccione *Ejecutar después de* para comprobar la integridad de la base de datos después de la migración.



 a| 
*Opciones de DBCC CHECKDB*
 a| 
** Seleccione la opción *PHYSICAL_ONLY* para limitar la comprobación de integridad a la estructura física de la base de datos y detectar páginas dañadas, errores de sumas de comprobación y errores de hardware habituales que afecten a la base de datos.
** Seleccione la opción *NO_INFOMSGS* para suprimir todos los mensajes informativos.
** Seleccione la opción *ALL_ERRORMSGS* para visualizar todos los errores notificados por objeto.
** Seleccione la opción *NOINDEX* si no desea comprobar los índices no almacenados en clúster.
+
La base de datos de SQL Server utiliza la comprobación de la consistencia de base de datos de Microsoft SQL Server para comprobar la integridad lógica y física de los objetos de la base de datos.

+

NOTE: Se recomienda seleccionar esta opción para disminuir el tiempo de ejecución.

** Seleccione la opción **TABLOCK** para limitar las comprobaciones y obtener bloqueos en lugar de utilizar una copia de Snapshot interna de la base de datos.


|===
. Revise el resumen y, a continuación, haga clic en **Finalizar**.

