---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar los plugins de SnapCenter, y credenciales adicionales para realizar operaciones de protección de datos en sistemas de archivos Windows o bases de datos. 
---
= Configure credenciales para el paquete de plugins de SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar los plugins de SnapCenter, y credenciales adicionales para realizar operaciones de protección de datos en sistemas de archivos Windows o bases de datos.

.Antes de empezar
* Debe configurar credenciales de Windows antes de instalar plugins.
* Debe configurar las credenciales con privilegios de administrador, incluidos los derechos de administrador en el host remoto.
* Autenticación SQL en hosts Windows
+
Debe configurar credenciales de SQL después de instalar plugins.

+
Si va a implementar el plugin de SnapCenter para Microsoft SQL Server, debe configurar las credenciales de SQL después de instalar plugins. Configure una credencial para un usuario con permisos de administrador del sistema en SQL Server.

+
El método de autenticación de SQL se verifica de acuerdo con una instancia de SQL Server. Esto significa que debe detectarse una instancia de SQL Server en SnapCenter. Por lo tanto, antes de añadir una credencial de SQL, debe añadir un host, instalar paquetes de plugins y actualizar los recursos. Se necesita la autenticación de SQL Server para realizar operaciones como la programación o la detección de recursos.



.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
. En la página Credential, especifique la información necesaria para configurar las credenciales:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Escriba un nombre para la credencial.



 a| 
Nombre de usuario/Contraseña
 a| 
Introduzca el nombre de usuario y la contraseña que se utilizarán para la autenticación.

** Administrador del dominio
+
Especifique el administrador de dominio en el sistema en el que va a instalar el plugin de SnapCenter. Los formatos válidos para el campo Nombre de usuario son:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema en el que va a instalar el plugin de SnapCenter. Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores local si la cuenta de usuario tiene privilegios elevados o si la función de control de acceso de usuario está desactivada en el sistema host. El formato válido para el campo Username es: `UserName`

+
No utilice comillas dobles (") ni marcas de retroceso (') en las contraseñas. No debe usar el signo menos de (<) y el signo de exclamación (!) los símbolos juntos en las contraseñas. Por ejemplo, arrendhan<!10, les10<!, backtick'12.





 a| 
Modo de autenticación
 a| 
Seleccione el modo de autenticación que desea utilizar. Si selecciona el modo de autenticación de SQL, también debe especificar la instancia de SQL Server y el host donde está ubicada esa instancia.

|===
. Haga clic en *Aceptar*.


Después de terminar de configurar las credenciales, se recomienda asignar el mantenimiento de credenciales a un usuario o un grupo de usuarios en la página User and Access.
