---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Cómo SnapCenter descubre las bases de datos de Oracle. 
---
= Nodos preferidos en la configuración de RAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En una configuración de Real Application Clusters (RAC) de Oracle, es posible especificar los nodos preferidos que utiliza SnapCenter para ejecutar la operación de backup. Si no se especifica un nodo preferido, SnapCenter asigna automáticamente un nodo como preferido y lo usa para crear el backup.

Los nodos preferidos pueden ser uno o varios de los nodos del clúster donde se encuentran las instancias de la base de datos de RAC. La operación de backup se activa solo en estos nodos preferidos y en el orden de preferencia indicado.

.Ejemplo
La base de datos de RAC cdbrac tiene tres instancias: cdbrac1 en el nodo node1, cdbrac2 en el nodo node2 y cdbrac3 en el nodo node3.

Las instancias 1 y 2 están configuradas como preferidos, con el nodo 2 en el primer lugar de preferencia y el nodo 1 en el segundo. Cuando se ejecuta una operación de backup, primero se intenta en el nodo 2, ya que es el primero en preferencia.

Si el nodo 2 no tiene un estado adecuado para el backup, lo cual puede deberse a diversos motivos, por ejemplo, que el agente del plugin no esté en ejecución en el host, la instancia de la base de datos del host no tiene el estado requerido para el tipo de backup especificado, O la instancia de base de datos del nodo 2 en una configuración de FlexASM no sirve a la instancia de ASM local; luego se intenta ejecutar la operación en el nodo 1.

El nodo 3 no se usará para el backup, ya que no es parte de la lista de nodos preferidos.



== Configuración de ASM Flex

En una configuración de Flex ASM, los nodos de hoja no se mostrarán como nodos preferidos si la cardinalidad es inferior al número de nodos del clúster de RAC. Si hay algún cambio en las funciones del nodo del clúster de ASM de Flex, debe detectar manualmente para que se actualicen los nodos preferidos.



== Estado de la base de datos necesario

Las instancias de base de datos de RAC de los nodos preferidos deben tener el estado necesario para que el backup se ejecute correctamente:

* Una de las instancias de base de datos de RAC de los nodos preferidos configurados debe tener el estado abierto para que se pueda crear un backup en línea.
* Una de las instancias de base de datos de RAC de los nodos preferidos configurados debe tener el estado de montaje y las demás instancias, incluidos los demás nodos preferidos, deben tener el estado de montaje o un valor inferior para crear un backup de montaje sin conexión.
* Las instancias de base de datos de RAC pueden tener cualquier estado, pero es necesario especificar los nodos preferidos para poder crear un backup de apagado sin conexión.

