---
permalink: protect-sce/reference_storage_types_supported_by_snapcenter_plug_in_for_microsoft_windows_and_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: SnapCenter es compatible con una gran variedad de tipos de almacenamiento, tanto en máquinas físicas como virtuales. Antes de instalar el paquete para el host, es necesario verificar que el tipo de almacenamiento sea compatible. 
---
= Tipos de almacenamiento compatibles con el plugin de SnapCenter para Microsoft Windows y Microsoft Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter es compatible con una gran variedad de tipos de almacenamiento, tanto en máquinas físicas como virtuales. Antes de instalar el paquete para el host, es necesario verificar que el tipo de almacenamiento sea compatible.

Windows Server es compatible con el aprovisionamiento y la protección de datos de SnapCenter. Para acceder a la información más actualizada sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121031;&solution=1259&isHWU&src=IMT[] [Herramienta de matriz de interoperabilidad de NetApp^].

|===
| Máquina | Tipo de almacenamiento | Aprovisionamiento con | Notas de soporte 


 a| 
Servidor físico
 a| 
LUN conectados a FC
 a| 
Interfaz gráfica de usuario de SnapCenter o cmdlets de PowerShell
 a| 



 a| 
Servidor físico
 a| 
LUN conectados a iSCSI
 a| 
Interfaz gráfica de usuario de SnapCenter o cmdlets de PowerShell
 a| 



 a| 
Máquina virtual de VMware
 a| 
LUN de RDM conectados por un adaptador de bus de host FC o iSCSI
 a| 
Cmdlets de PowerShell
 a| 
Solo compatibilidad física


NOTE: Los VMDK no son compatibles.



 a| 
Máquina virtual de VMware
 a| 
LUN iSCSI conectados directamente al sistema invitado por el iniciador de iSCSI
 a| 
Interfaz gráfica de usuario de SnapCenter o cmdlets de PowerShell
 a| 

NOTE: Los VMDK no son compatibles.



 a| 
Máquina virtual Hyper-V.
 a| 
LUN de Virtual FC (VFC) conectados por un switch Fibre Channel virtual
 a| 
Interfaz gráfica de usuario de SnapCenter o cmdlets de PowerShell
 a| 
Para aprovisionar LUN de Virtual FC (VFC) conectados por un switch Fibre Channel virtual se debe usar Hyper-V Manager.


NOTE: No se admiten los discos de acceso directo Hyper-V ni el backup de bases de datos en VHD(x) con aprovisionamiento en almacenamiento de NetApp.



 a| 
Máquina virtual Hyper-V.
 a| 
LUN iSCSI conectados directamente al sistema invitado por el iniciador de iSCSI
 a| 
Interfaz gráfica de usuario de SnapCenter o cmdlets de PowerShell
 a| 

NOTE: No se admiten los discos de acceso directo Hyper-V ni el backup de bases de datos en VHD(x) con aprovisionamiento en almacenamiento de NetApp.

|===