---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar mensajes de correo electrónico o buzones en lugar de la base de datos completa de Exchange.' 
---
= Recuperación granular de correos y buzones de correo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar mensajes de correo electrónico o buzones en lugar de la base de datos completa de Exchange.

La restauración de bases de datos completas sólo para recuperar un correo individual consume mucho tiempo y recursos. SMBR le ayuda a recuperar rápidamente los mensajes de correo electrónico creando una copia de clon de la Snapshot y, a continuación, usando las API de Microsoft para montar el buzón en SMBR. Para obtener información sobre cómo utilizar SMBR, consulte https://library.netapp.com/ecm/ecm_download_file/ECMLP2871407["Guía de administración de SMBR"^].

Si quiere más información sobre SMBR, consulte lo siguiente:

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR["Cómo restaurar manualmente un solo elemento con SMBR (también se aplica a las restauraciones de Ontrack Power Control)"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["Cómo restaurar desde el almacenamiento secundario en SMBR con SnapCenter"^]
* https://www.youtube.com/watch?v=fOMuaaXrreI&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Recuperación de Microsoft Exchange Mail desde SnapVault mediante SMBR"^]

