---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar mensajes de correo electrónico o buzones en lugar de la base de datos completa de Exchange.' 
---
= Recuperación granular de correos y buzones de correo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software Single Mailbox Recovery (SMBR) le permite restaurar y recuperar mensajes de correo electrónico o buzones en lugar de la base de datos completa de Exchange.

La restauración de bases de datos completas sólo para recuperar un correo individual consume mucho tiempo y recursos. SMBR le ayuda a recuperar rápidamente los mensajes de correo electrónico creando una copia de clon de la Snapshot y, a continuación, usando las API de Microsoft para montar el buzón en SMBR. Para obtener información sobre cómo utilizar SMBR, consulte https://["Guía de administración de SMBR"^].

*Más información*

* link:../install/concept_snapcenter_licenses.html#single-mailbox-recovery-smbr-licenses["Licencias de SMBR"^]
* https://["Biblioteca de documentación de SMBR"^]
* https://["Cómo restaurar desde el almacenamiento secundario en SMBR con SnapCenter"^]
* https://["Recuperación de Microsoft Exchange Mail desde SnapVault mediante SMBR"^]

