---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords:  
summary: Debe instalar el plugin para Exchange desde la interfaz de usuario de SnapCenter. Sin embargo, si no puede hacerlo por algún motivo, puede ejecutar el programa de instalación del plugin para Exchange sin supervisión en el modo silencioso desde la línea de comandos de Windows. 
---
= Instale el plugin de SnapCenter para Exchange silenciosamente desde la línea de comandos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar el plugin para Exchange desde la interfaz de usuario de SnapCenter. Sin embargo, si no puede hacerlo por algún motivo, puede ejecutar el programa de instalación del plugin para Exchange sin supervisión en el modo silencioso desde la línea de comandos de Windows.

*Lo que necesitará*

* Debe tener un backup de los recursos de Microsoft Exchange Server.
* Debe haber instalado los paquetes de plugins de SnapCenter.
* Debe eliminar la versión anterior del plugin de SnapCenter para Microsoft SQL Server antes de instalar.
+
Para obtener más información, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["Cómo instalar un plugin de SnapCenter de forma manual y directa desde el host del plugin"^].



* Pasos*

. Compruebe si existe una carpeta _C:\temp_ en el host del plugin y que el usuario que ha iniciado sesión tiene acceso completo a ella.
. Descargue el plugin de SnapCenter para Microsoft Windows desde _C:\ProgramData\NetApp\SnapCenter\Package_ Repository.
+
Es posible acceder a esta ruta desde el host en el que se ha instalado el servidor SnapCenter.

. Copie el archivo de instalación en el host en el que desea instalar el plugin.
. Desde el símbolo del sistema de Windows en el host local, desplácese hasta el directorio en el que guardó los archivos de instalación del plugin.
. Introduzca el siguiente comando para instalar el plugin.
+
_Snapcenter_Windows_host_plugin.exe"/silent /DEBUGLOG"<Debug_Log_Path>" /log"<Log_Path>" BI_SNAPCENTER_PORT=<Num> SUITE_INSTALLDIR="<Install_Directory_Path>" BI_SERVICEACCOUNT=<domain\administrator> BI_SERVICEPWD=<password> FeatureInstall=HPPW,SCW,SCE_

+
Por ejemplo:

+
_C:\ProgramData\NetApp\SnapCenter\Package Repository\snapcenter_Windows_host_plugin.exe"/silent /Featurelog"C:\HPPW_SCSQL_Install.log" /log"C:\TEMP" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter"_DEBUGENG=SERVIPW_Administrator=contraseña_COVISPW_SEW_SEW_Administrator=SERVISPW_SEW_SEW_DURBW_SEW_SEAT=Install_SEAT=Administrador_SEBURB

+

NOTE: Todos los parámetros que se pasan durante la instalación del plugin para Exchange distinguen entre mayúsculas y minúsculas.

+
Introduzca los siguientes valores para las variables:

+
|===
| Variable | Valor 


 a| 
_/DEBUGLOG"<Debug_Log_Path>_
 a| 
Indique el nombre y la ubicación del archivo de registro del instalador de la suite, como en el ejemplo siguiente:

_Setup.exe /DEBUGLOG"C:\PathToLog\setupexe.log_



 a| 
BI_SNAPCENTER_PORT
 a| 
Indique el puerto en el que SnapCenter se comunica con SMCore.



 a| 
SUITE_INSTALLDIR
 a| 
Indique el directorio de instalación para el paquete de plugins del host.



 a| 
BI_SERVICEACCOUNT
 a| 
Indique la cuenta de servicio web del plugin de SnapCenter para Microsoft Windows.



 a| 
BI_SERVICEPWD
 a| 
Indique la contraseña para la cuenta de servicio web del plugin de SnapCenter para Microsoft Windows.



 a| 
ISFeatureInstall
 a| 
Indique la solución que debe aplicar SnapCenter en un host remoto.

|===
. Supervise el programador de tareas de Windows, el archivo de registro de instalación principal _C:\Installdebug.log_ y los archivos de instalación adicionales en _C:\Temp_.
. Supervise el directorio _%temp%_ para comprobar si los instaladores _msiexe.exe_ están instalando el software sin errores.
+

NOTE: La instalación del plugin para Exchange registra el plugin en el host y no en el servidor de SnapCenter. Es posible registrar el plugin en SnapCenter Server. Para ello, se debe añadir el host mediante la interfaz gráfica de usuario de SnapCenter o el cmdlet de PowerShell. Una vez añadido el host, el plugin se detecta automáticamente.


