---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar el paquete de plugins y credenciales adicionales para realizar operaciones de protección de datos en bases de datos. 
---
= Configure credenciales para el plugin de SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar el paquete de plugins y credenciales adicionales para realizar operaciones de protección de datos en bases de datos.

*Acerca de esta tarea*

Debe configurar credenciales para instalar plugins en hosts de Windows. Aunque puede crear credenciales para Windows después de implementar hosts e instalar plugins, lo mejor es crear credenciales después de añadir SVM antes de implementar hosts e instalar plugins.

Configure las credenciales con privilegios de administrador, incluidos los derechos de administrador en el host remoto.

Si se configuran las credenciales para grupos de recursos individuales y el nombre de usuario no tiene privilegios de administrador completos, debe asignar al menos los privilegios de grupo de recursos y backup al nombre de usuario.

* Pasos*

. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
+
Se mostrará la ventana Credential.

. En la página Credential, haga lo siguiente:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Escriba un nombre para la credencial.



 a| 
Nombre de usuario
 a| 
Introduzca el nombre de usuario utilizado para autenticación.

** Administrador de dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador de dominio o cualquier miembro del grupo de administrador en el sistema en el que va a instalar el plugin de SnapCenter. Los formatos válidos para el campo Nombre de usuario son:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema en el que va a instalar el plugin de SnapCenter. Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores local si la cuenta de usuario tiene privilegios elevados o si la función de control de acceso de usuario está desactivada en el sistema host. El formato válido para el campo Username es: `UserName`





 a| 
Contraseña
 a| 
Introduzca la contraseña usada para autenticación.



 a| 
Autenticación
 a| 
Seleccione Windows como el modo de autenticación.

|===
. Haga clic en *Aceptar*.

