---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Es posible crear una política de backup para los recursos de Exchange o los grupos de recursos antes de usar SnapCenter con el fin de realizar un backup de los recursos de Microsoft Exchange Server. También es posible crear una política de backup en el momento de crear un grupo de recursos o realizar un backup de un único recurso. 
---
= Crear políticas de backup para bases de datos de Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear una política de backup para los recursos de Exchange o los grupos de recursos antes de usar SnapCenter con el fin de realizar un backup de los recursos de Microsoft Exchange Server. También es posible crear una política de backup en el momento de crear un grupo de recursos o realizar un backup de un único recurso.

.Antes de empezar
* Debe estar definida la estrategia de protección de datos.
+
Para obtener detalles, consulte la información sobre cómo definir una estrategia de protección de datos para bases de datos de Exchange.

* Debe haberse preparado para la protección de datos completando ciertas tareas, como instalar SnapCenter, añadir hosts, identificar recursos y crear conexiones con el sistema de almacenamiento.
* Debe haber actualizado (detectado) los recursos de Exchange Server.
* Si va a replicar snapshots en un reflejo o almacén, el administrador de SnapCenter debe haberle asignado las máquinas virtuales de almacenamiento (SVM) para los volúmenes de origen y de destino.
* Para ejecutar los scripts de PowerShell en scripts previos y posteriores, es necesario configurar el valor de `usePowershellProcessforScripts` parámetro en true en la `web.config` archivo.
+
El valor predeterminado es FALSE.

* Revise los requisitos previos y las limitaciones específicos de SnapMirror Active Sync. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"].


.Acerca de esta tarea
* Una política de backup es un conjunto de reglas que rigen cómo gestionar y conservar backups, y con qué frecuencia se realizará un backup del recurso o del grupo de recursos. Asimismo, es posible especificar la configuración de scripts. Puede especificar opciones en la política para ahorrar tiempo cuando desee reutilizarla con otro grupo de recursos.
* La retención de un backup completo es específica de una política determinada. Una base de datos o un recurso que utiliza la política A con una retención de backup completo de valor 4 retiene 4 backups completos y no afecta la política B de la misma base de datos o recurso, que puede presentar una retención de valor 3 para retener 3 backups completos.
* La retención de backup de registros rige para todas las políticas y se aplica a todos los backups de registros de una base de datos o registro. Por lo tanto, cuando se realiza un backup completo mediante la política B, la configuración de retención de registros afecta los backups de registros creados con la política A en la misma base de datos o el mismo recurso. De igual modo, la configuración de retención de registros de la política A afecta los backups de registros creados con la política B en la misma base de datos.
* LA RUTA_DE_SCRIPTS se define mediante la clave PredefinedWindowsScriptsDirectory ubicada en el archivo SMCoreServiceHost.exe.Config del host del plugin.
+
Si es necesario, puede cambiar esta ruta y reiniciar el servicio SMcore. Se recomienda utilizar la ruta predeterminada para la seguridad.

+
El valor de la tecla se puede mostrar desde swagger a través de la API: API /4.7/config settings

+
Puede usar LA API GET para mostrar el valor de la clave. No se admite LA CONFIGURACIÓN de API.

+
|===


| *Mejor práctica:* es mejor configurar la directiva de retención secundaria en función del número de copias de seguridad completas y de registros, en general, que desee conservar. Cuando se configuran las políticas de retención secundarias, se tiene en cuenta que cuando las bases de datos y los registros que están en volúmenes diferentes, cada backup puede tener tres Snapshot y cuando las bases de datos y los registros están en el mismo volumen, cada backup puede tener dos Snapshot. 
|===
* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
+
Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención.  Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.

+
Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las snapshots de SnapLock heredarán el tiempo de caducidad de SnapLock Vault. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.





.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Backup Type and Replication, realice los siguientes pasos:
+
.. Elija el tipo de backup:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Realice un backup de los archivos de la base de datos y de los registros de transacciones necesarios
 a| 
Seleccione *copia de seguridad completa y copia de seguridad de registro*.

Se realiza un backup de las bases de datos con truncamiento de registros, y todos los registros se incluyen en el backup, incluso los truncados.


NOTE: Este es el tipo de backup recomendado.



 a| 
Realice un backup de los archivos de la base de datos y de los registros de transacciones sin confirmar
 a| 
Seleccione *copia de seguridad completa*.

Se realiza un backup de las bases de datos con truncamiento de registros, y los registros acortados no se incluyen en el backup.



 a| 
Realice un backup de todos los registros de transacciones
 a| 
Seleccione *copia de seguridad de registro*.

Se realiza un backup de todos los registros de transacciones en el sistema de archivos activo y no hay truncamiento de registros.

Se crea un directorio _scebackupinfo_ en el mismo disco que el registro activo. Este directorio contiene el puntero a los cambios incrementales de la base de datos de Exchange y no es equivalente a los archivos de registro completos.



 a| 
Realizar un backup de todos los archivos de la base de datos y los registros de transacciones sin acortarlos
 a| 
Seleccione *copia de seguridad*.

Se realiza un backup de todas las bases de datos y todos los registros y no hay truncamiento de registros. Normalmente se utiliza este tipo de backup para volver a insertar una réplica o para probar o diagnosticar un problema.

|===
+

NOTE: Se debe definir el espacio requerido para los backups de registros en función de la retención de backup completo y no en la retención de último minuto (UTM).

+

NOTE: Cree políticas de almacén independientes para registros y bases de datos cuando se trate de volúmenes de Exchange (LUN) y establezca la opción Keep (retención) para la política de registros en el doble de número para cada etiqueta que la política de base de datos, usando las mismas etiquetas. Para obtener más información, consulte: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["Los backups de SnapCenter para Exchange solo conservan la mitad de las copias Snapshot en el volumen de registro de destino del almacén"^]

.. En la sección Database Availability Group Settings, seleccione una acción:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Realice un backup de copias activas
 a| 
Seleccione esta opción para realizar un backup únicamente de las copias activas de la base de datos seleccionada.

En el caso de los grupos de disponibilidad de la base de datos (DAG), con esta opción se realiza un backup solo de las copias activas de todas las bases de datos en el DAG.

Las copias pasivas no se incluyen en el backup.



 a| 
Realizar un backup de las copias en los servidores que se seleccionarán en el momento de crear el trabajo de backup
 a| 
Seleccione esta opción para realizar un backup de cualquier copia de las bases de datos en los servidores seleccionados, ya sean activas o pasivas.

En el caso de los DAG, con esta opción se realiza un backup tanto de las copias activas como pasivas de todas las bases de datos en los servidores seleccionados.

|===
+

NOTE: En las configuraciones de clúster, los backups se conservan en cada nodo del clúster según la configuración de retención establecida en la política. Si cambia el nodo propietario del clúster, se conservarán las copias de seguridad del nodo propietario anterior. La retención solo se aplica a nivel de nodo.

.. En la sección frecuencia de programación, seleccione uno o más tipos de frecuencia: *A petición*, *hora*, *Diario*, *Semanal* y *Mensual*.
+

NOTE: Es posible especificar el cronograma (fecha de inicio y de finalización) para las operaciones de backup a la vez que se crea un grupo de recursos. De este modo, se pueden crear grupos de recursos que comparten la misma política y frecuencia de backup, pero se pueden asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.

.. Seleccione la etiqueta de política.
+
Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+

NOTE: Si ha seleccionado *Actualizar SnapMirror después de crear una copia Snapshot local*, puede especificar opcionalmente la etiqueta de la directiva secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.

.. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:
+

NOTE: Debe seleccionar las opciones de replicación secundarias para que el *Periodo de bloqueo de copia de instantánea secundaria* sea efectivo. La opción *Periodo de bloqueo de copia de instantánea secundaria* está disponible en la página Retención.

+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Actualice SnapMirror después de crear una instantánea local
 a| 
Seleccione esta opción para mantener copias de SnapMirror de conjuntos de backups en otro volumen (SnapMirror).

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal.

Esta opción debe estar habilitada para la sincronización activa de SnapMirror.


IMPORTANT: La política solo se puede usar si se configura la sincronización activa de SnapMirror para volúmenes de Exchange ONTAP. SnapCenter no permite esto. Debe activar la opción “Mirror”.

Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Consulte link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["Consulte los backups de Exchange en la página Topology"].



 a| 
Actualizar SnapVault después de crear una instantánea local
 a| 
Seleccione esta opción para realizar una replicación de backup de disco a disco.



 a| 
Número de reintentos con error
 a| 
Introduzca el número de intentos de replicación que deben producirse antes de que se interrumpa el proceso.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.



. En la página Retention, configure los ajustes de retención.
+
Las opciones que se muestren dependerán del tipo de backup y de frecuencia previamente seleccionados.

+

NOTE: El valor de retención máximo es 1018. Se producirá un error en los backups si la retención se establece en un valor superior a la versión de ONTAP subyacente.

+

IMPORTANT: Debe establecer el número de retención en 2 o un valor más alto si tiene pensado habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera Snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva Snapshot en el destino.

+
.. En la sección Log backups retention settings, seleccione una de las siguientes opciones:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Retener únicamente una cantidad específica de backups de registros
 a| 
Seleccione *Number of full backups for which logs are retained* y especifique la cantidad de backups completos para la cual desea definir una capacidad de restauración de último minuto.

La retención de último minuto (UTM) se aplica al backup de registros creado mediante un backup completo o un backup de registros. Por ejemplo, si la configuración de retención UTM se configura para retener los backups de registros de los últimos 5 backups completos, se conservan los backups de registros de los últimos 5 backups completos.

Las carpetas de registro creadas como parte de los backups completos y de registros se eliminan automáticamente como parte de UTM. No es posible eliminar las carpetas de registro manualmente. Por ejemplo, si la configuración de retención de backup completo o completo y el backup de registros se establece en 1 mes y la retención UTM se establece en 10 días, la carpeta de registro creada como parte de estos backups se eliminará según UTM. Como resultado, solo habrá 10 días de carpetas de registro y todos los demás backups se marcan para una restauración a un momento específico.

Es posible configurar el valor de retención UTM como 0, si no desea realizar una restauración de último minuto. Esto habilitará la operación de restauración a un momento específico.

*Mejores prácticas:* Es mejor que la configuración sea igual a la configuración de Total Snapshots (copias de seguridad completas) en la sección Configuración de retención de copia de seguridad completa. De este modo se garantiza que se conservan los archivos de registro para cada backup completo.



 a| 
Retener las copias de backup por una cantidad determinada de días
 a| 
Seleccione la opción *Keep log backups for last* y especifique el número de días que se conservarán las copias de seguridad de registro.

Se conservan los backups de registros por la cantidad de días de backups completos.



 a| 
Período de bloqueo de instantánea
 a| 
Seleccione *Período de bloqueo de copia de instantánea* y seleccione Días, Meses o Años.

El período de retención de SnapLock debe ser inferior a 100 años.

|===
+
Si seleccionó *Log backup* como tipo de copia de seguridad, las copias de seguridad de registros se conservan como parte de la configuración de retención de último minuto para las copias de seguridad completas.

.. En la sección Full backup retention settings, seleccione una de las siguientes opciones para backups a petición y, a continuación, seleccione una opción para backups completos:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Conserve únicamente una cantidad específica de snapshots
 a| 
Si desea especificar el número de copias de seguridad completas que se deben conservar, seleccione la opción *Total de copias de Snapshot para mantener* y especifique el número de instantáneas (copias de seguridad completas) que se deben retener.

Si se supera la cantidad especificada de backups completos, se eliminarán los backups completos que exceden dicha cantidad empezando por las copias más antiguas.



 a| 
Retener los backups completos por una cantidad determinada de días
 a| 
Seleccione la opción *Keep Snapshot copies for* y especifique el número de días para conservar Snapshots (copias de seguridad completas).



 a| 
Período de bloqueo de instantánea primaria
 a| 
Seleccione *Periodo de bloqueo de copia de instantánea primaria* y seleccione Días, Meses o Años.

El período de retención de SnapLock debe ser inferior a 100 años.



 a| 
Período de bloqueo de instantánea secundaria
 a| 
Seleccione *Periodo de bloqueo de copia de instantánea secundaria* y seleccione Días, Meses o Años.

|===
+
Si se dispone de una base de datos que solo tiene backups de registros y ningún backup completo en un host de una configuración de DAG, los backups de registros se retienen de las siguientes maneras:

+
*** De forma predeterminada, SnapCenter busca el backup completo más antiguo de la base de datos en todos los otros hosts del DAG y elimina todos los backups de registros de este host que se realizaron antes del backup completo.
*** Para anular este comportamiento de retención predeterminada en una base de datos en un host de un DAG que solo presenta backups de registros, se puede añadir la clave * MaxLogBackupOnlyCountWithoutFullBackup* en el archivo _C:\Program Files\NetApp\SnapCenter WebApp\web.config_.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
En el ejemplo, el valor 10 indica que se conservan hasta 10 backups de registros en el host.





. En la página Script, introduzca la ruta y los argumentos del script previo o script posterior que se deben ejecutar antes o después de la operación de backup, según corresponda.
+
** Los argumentos de copia de seguridad del script incluyen "'$Database'" y "'$ServerInstance'".
** Los argumentos de copia de seguridad de PostScript incluyen «»$Database», «»$ServerInstance», «»$BackupName», «»$LogDirectory» y «»$LogSnapshot».
+
Es posible ejecutar un script para actualizar las capturas SNMP, automatizar alertas, enviar registros, etc.

+

NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.



. Revise el resumen y, a continuación, haga clic en *Finalizar*.

