---
permalink: protect-sce/task_reseed_a_replica_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Puede usar cmdlets de PowerShell para restaurar una réplica en mal estado mediante la copia más reciente del mismo host o la copia más reciente de un host alternativo. 
---
= Repropagación de una réplica mediante cmdlets de PowerShell para base de datos de Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar cmdlets de PowerShell para restaurar una réplica en mal estado mediante la copia más reciente del mismo host o la copia más reciente de un host alternativo.

La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["Guía de referencia de cmdlets de SnapCenter Software"^].

.Pasos
. Inicie una sesión de conexión con el servidor SnapCenter para el usuario especificado mediante el `Open-SmConnection` cmdlet.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Realimentar la base de datos mediante el `reseed-SmDagReplicaCopy` cmdlet.
+
En este ejemplo se reactiva la copia fallida de la base de datos denominada execdb en el host "mva-rx200.netapp.com" utilizando la última copia de seguridad en ese host.

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database execdb
----
+
En este ejemplo se reactiva la copia fallida de la base de datos denominada execdb utilizando la última copia de seguridad de la base de datos (producción/copia) en un host alternativo "mva-rx201.netapp.com."

+
[listing]
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database  execdb -BackupHost "mva-rx201.netapp.com"
----

