---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Es posible crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar cmdlets de PowerShell para realizar backups y restaurar.' 
---
= Cree una conexión de sistema de almacenamiento y una credencial mediante cmdlets de PowerShell para Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar cmdlets de PowerShell para realizar backups y restaurar.

*Lo que necesitará*

* Debe haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que no se encuentren en curso las instalaciones de plugins.
+
No debe haber instalaciones de complementos de host en curso al añadir una conexión a sistemas de almacenamiento, ya que puede que la caché del host no se actualice y que el estado de las bases de datos pueda aparecer en la interfaz gráfica de usuario de SnapCenter como «'no disponible para el backup' o «'no en el almacenamiento de NetApp'».

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en clústeres diferentes. Cada uno de los sistemas de almacenamiento que admite SnapCenter debe tener un nombre único y una dirección IP de LIF de datos única.



* Pasos*

. Inicie una sesión de conexión de PowerShell mediante el `Open-SmConnection` cmdlet.
+
En este ejemplo, se abre una sesión de PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Cree una nueva conexión con el sistema de almacenamiento mediante el `Add-SmStorageConnection` cmdlet.
+
En este ejemplo, se crea una nueva conexión con el sistema de almacenamiento:

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. Cree una nueva cuenta Run as con el `Add-Credential` cmdlet.
+
En este ejemplo, se crea una nueva cuenta Run as denominada "ExchangeAdmin" con credenciales de Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guía de referencia de cmdlets de SnapCenter Software"^].
