---
permalink: protect-scw/concept_snapcenter_plug_in_for_microsoft_windows_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Windows 
summary: El plugin de SnapCenter para Microsoft Windows es un componente en el lado del host de NetApp SnapCenter Software que permite la gestión de protección de datos para aplicaciones de recursos de sistemas de archivos Microsoft. Además, ofrece aprovisionamiento de almacenamiento, consistencia de Snapshot y reclamación de espacio para sistemas de archivos Windows. El plugin para Windows automatiza las operaciones de backup, restauración y clonado del sistema de archivos en el entorno de SnapCenter. 
---
= Información general sobre el plugin de SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El plugin de SnapCenter para Microsoft Windows es un componente en el lado del host de NetApp SnapCenter Software que permite la gestión de protección de datos para aplicaciones de recursos de sistemas de archivos Microsoft. Además, ofrece aprovisionamiento de almacenamiento, consistencia de Snapshot y reclamación de espacio para sistemas de archivos Windows. El plugin para Windows automatiza las operaciones de backup, restauración y clonado del sistema de archivos en el entorno de SnapCenter.

Cuando se instala el plugin para Windows, es posible utilizar SnapCenter con la tecnología SnapMirror de NetApp para crear copias de reflejo de conjuntos de backups en otro volumen, y también con la tecnología SnapVault de NetApp para realizar replicaciones de backup disco a disco para archivado o cumplimiento de normativas.
