---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: Definir una estrategia de backup antes de crear backups garantiza que se cuente con todos los backups necesarios para restaurar o clonar correctamente los sistemas de archivos. La estrategia de backup queda determinada principalmente por el SLA, el RTO y el RPO. 
---
= Defina una estrategia de backup para sistemas de archivos de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir una estrategia de backup antes de crear backups garantiza que se cuente con todos los backups necesarios para restaurar o clonar correctamente los sistemas de archivos. La estrategia de backup queda determinada principalmente por el SLA, el RTO y el RPO.

Un acuerdo de nivel de servicio define el nivel de servicio que se espera y aborda varios problemas vinculados con el servicio, como su disponibilidad y rendimiento. El objetivo de tiempo de recuperación es el plazo de recuperación después de una interrupción del servicio. El RPO define la estrategia respecto de la antigüedad de los archivos que se deben recuperar del almacenamiento de backup para reanudar las operaciones regulares después de un fallo. El acuerdo de nivel de servicio, el objetivo de tiempo de recuperación y el RPO ayudan a establecer una estrategia de protección de datos.



== Programaciones de backup para sistemas de archivos Windows

La frecuencia de los backups se especifica en las políticas; la programación de los backups se especifica en la configuración del grupo de recursos. El factor más crítico para determinar la frecuencia o la programación de los backups es la tasa de cambio del recurso y la importancia de los datos. Puede ser recomendable realizar el backup de un recurso muy utilizado una vez por hora, mientras que, en el caso de un recurso de poco uso, es suficiente hacerlo una vez por día. Otros factores son la importancia del recurso para la organización, el SLA y el RPO.

Un acuerdo de nivel de servicio define el nivel de servicio que se espera y aborda varios problemas vinculados con el servicio, como su disponibilidad y rendimiento. El RPO define la estrategia respecto de la antigüedad de los archivos que se deben recuperar del almacenamiento de backup para reanudar las operaciones regulares después de un fallo. El SLA y el RPO contribuyen a la estrategia de protección de datos.

Incluso en el caso de un recurso utilizado intensivamente, no existe el requisito de ejecutar un backup completo más de una o dos veces al día.

Las programaciones de backup están compuestas por dos partes:

* Frecuencia de backup
+
La frecuencia de los backups (cada cuánto tiempo deben realizarse los backups), denominada _schedule type_ para algunos plugins, forma parte de la configuración de una política. Por ejemplo, puede configurar la frecuencia de la copia de seguridad como horaria, diaria, semanal o mensual, o puede especificar *Ninguno* que convierte la política en una directiva sólo bajo demanda. Puede acceder a las directivas haciendo clic en *Configuración* > *Directivas*.

* Programaciones de backup
+
Las programaciones de los backups (el momento exacto en que se realizan los backups) forman parte de una configuración de grupo de recursos. Por ejemplo, si tiene un grupo de recursos que posee una política configurada para backups semanales, quizás sea conveniente configurar la programación para que realice backups todos los jueves a las 00:10. Puede acceder a los programas de grupos de recursos haciendo clic en *Recursos* > *grupos de recursos*.





== Cantidad de tareas de backup necesarias para sistemas de archivos Windows

Algunos factores que determinan la cantidad de backups que se necesitan son el tamaño del sistema de archivos Windows, la cantidad de volúmenes que se usan, la tasa de cambio del recurso y el acuerdo de nivel de servicio.



== Convención de nomenclatura de backups para sistemas de archivos Windows

Los backups del sistema de archivos Windows usan la convención de nomenclatura predeterminada para las copias de Snapshot. La convención de nomenclatura de backups predeterminada añade la fecha/hora a los nombres de las copias de Snapshot, lo cual ayuda a identificar cuándo se crearon las copias.

La copia de Snapshot usa la siguiente convención de nomenclatura predeterminada: Resourcegroupname_hostname_timestamp

Es necesario asignar un nombre a los grupos de recursos de backup de forma lógica, como en el ejemplo siguiente:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
En este ejemplo, los elementos de la sintaxis tienen los siguientes significados:

* `dts1` es el nombre del grupo de recursos.
* `mach1x88` es el nombre del host.
* `03-12-2016_23.17.26` es la fecha y la marca de hora.


Al crear un backup, también se puede añadir una etiqueta descriptiva que ayude a identificar el backup. Por el contrario, si se desea usar una convención de nomenclatura de backup personalizada, se debe cambiar el nombre del backup una vez que finaliza la operación de backup.



== Opciones de retención de backups

Es posible elegir la cantidad de días durante los cuales se retendrán las copias de backup o especificar la cantidad de copias de backup que se desean retener, con un máximo de 255 copias en ONTAP. Por ejemplo, una organización puede necesitar retener 10 días de copias de backup o 130 copias de backup.

Al crear una política, es posible especificar las opciones de retención para cada tipo y programación de backup.

Si se configura la replicación de SnapMirror, la política de retención se refleja en el volumen de destino.

SnapCenter elimina los backups previos que tengan etiquetas de retención que coincidan con el tipo de programación. Si se modifica el tipo de programación para el recurso o el grupo de recursos, los backups con la etiqueta del tipo de programación anterior podrían conservarse en el sistema.


NOTE: Para la retención a largo plazo de copias de backup, es conveniente usar el backup de SnapVault.
