---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords:  
summary: Si desea instalar el plugin de SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el cmdlet de PowerShell Install-SmHostPackage. 
---
= Instale el plugin de SnapCenter para Microsoft Windows en varios hosts remotos mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea instalar el plugin de SnapCenter para Microsoft Windows en varios hosts a la vez, puede hacerlo mediante el `Install-SmHostPackage` Cmdlet de PowerShell.

Tiene que haber iniciado sesión en SnapCenter como usuario del dominio con derechos de administrador local en cada host en el que desee instalar los plugins.

* Pasos*

. Inicie PowerShell.
. En el host del servidor SnapCenter, establezca una sesión mediante el `Open-SmConnection` cmdlet y, a continuación, introduzca las credenciales.
. Añada el host o el clúster independiente a SnapCenter mediante el `Add-SmHost` cmdlet y los parámetros necesarios.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["Guía de referencia de cmdlets de SnapCenter Software"^].

. Instale el plugin en varios hosts mediante el `Install-SmHostPackage` cmdlet y los parámetros necesarios.
+
Puede utilizar el `-skipprecheck` opción cuando instaló los plugins manualmente y no desea validar si el host cumple con los requisitos para instalar el plugin.


