---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: Puede utilizar la página SnapCenter Add Host para añadir hosts de Windows. El plugin de SnapCenter para Microsoft Windows está instalado automáticamente en el host especificado. Este es el método recomendado para la instalación de plugins. Puede añadir un host e instalar un plugin para un host individual o para un clúster. 
---
= Añada hosts e instale el plugin de SnapCenter para Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la página SnapCenter Add Host para añadir hosts de Windows. El plugin de SnapCenter para Microsoft Windows está instalado automáticamente en el host especificado. Este es el método recomendado para la instalación de plugins. Puede añadir un host e instalar un plugin para un host individual o para un clúster.

.Antes de empezar
* Debe ser un usuario al que se ha asignado una función que tenga permisos de instalación y desinstalación de plugins, como el rol de administrador de SnapCenter.
* Al instalar un plugin en un host de Windows, si especifica una credencial que no está integrada o si el usuario pertenece a un usuario de grupo de trabajo local, debe deshabilitar UAC en el host.
* El usuario de SnapCenter debe agregarse a la función «'Iniciar sesión como servicio'» del servidor Windows.
* Debe asegurarse de que el servicio de cola de mensajes esté en estado en ejecución.
* Si está utilizando la cuenta de servicio gestionado en grupo (GMSA), debe configurar GMSA con privilegios administrativos.
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Configurar la cuenta de servicio administrado de grupo en Windows Server 2012 o posterior para el sistema de archivos de Windows"]



.Acerca de esta tarea
* No es posible añadir un servidor SnapCenter como host de plugins a otro servidor SnapCenter.
* Plugins de Windows
+
** Microsoft Windows
** Servidor de Microsoft Exchange
** Microsoft SQL Server
** SAP HANA
** Plugins personalizados


* Instalar plugins en un clúster
+
Si instala plugins en un clúster (WSFC, Oracle RAC o DAG de Exchange), se instalan en todos los nodos del clúster.

* Almacenamiento E-series
+
No puede instalar el plugin para Windows en un host de Windows conectado al almacenamiento E-series.




NOTE: SnapCenter no admite la adición de un mismo host (host del plugin) a SnapCenter si el host ya forma parte de un grupo de trabajo y se cambió a otro dominio o viceversa.
Si desea añadir el mismo host, debe quitar el host de SnapCenter y volver a añadirlo.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *hosts*.
. Asegúrese de que *Managed hosts* esté seleccionado en la parte superior.
. Haga clic en *Agregar*.
. En la página hosts, realice lo siguiente:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Tipo de host
 a| 
Seleccione el tipo de host *Windows*.

El servidor de SnapCenter añade el host y, a continuación, instala el plugin para Windows si aún no está instalado en el host.



 a| 
Nombre de host
 a| 
Introduzca el nombre de dominio completamente cualificado (FQDN) o la dirección IP del host.

SnapCenter depende de una configuración adecuada del DNS. Por lo tanto, lo más recomendable es introducir el nombre de dominio completamente cualificado (FQDN).

Puede introducir las direcciones IP o el FQDN de uno de los siguientes:

** Host independiente
** Clustering de conmutación al nodo de respaldo de Windows Server (WSFC)
+
Si va a añadir un host mediante SnapCenter y forma parte de un subdominio, debe proporcionar el FQDN.





 a| 
Credenciales
 a| 
Seleccione el nombre de credencial que ha creado o cree las credenciales nuevas.

Las credenciales deben tener derechos de administrador en el host remoto. Para obtener más detalles, consulte los detalles de cómo crear una credencial.

Los detalles sobre las credenciales, incluidos el nombre de usuario, el dominio y el tipo de host, se muestran colocando el cursor sobre el nombre de las credenciales que ha proporcionado.


NOTE: El modo de autenticación se determina por el tipo de host que especifique en el asistente Add host.

|===
. En la sección Select Plug-ins to Install, seleccione los plugins que desea instalar.
+
Para nuevas implementaciones, no aparece ningún paquete de plugins.

. (Opcional) haga clic en *más opciones*.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Puerto
 a| 
Conserve el número de puerto predeterminado o especifique el número de puerto.

El número de puerto predeterminado es 8145. Si el servidor SnapCenter se instaló en un puerto personalizado, ese número de puerto se mostrará como el puerto predeterminado.


NOTE: Si ha instalado plugins manualmente y ha especificado un puerto personalizado, debe especificar el mismo puerto. De lo contrario, la operación dará error.



 a| 
Ruta de instalación
 a| 
La ruta predeterminada es C:\Program Files\NetApp\SnapCenter.

Opcionalmente, puede personalizar la ruta. Para el paquete de plugins de SnapCenter para Windows, la ruta predeterminada es C:\Program Files\NetApp\SnapCenter. Sin embargo, si lo desea, puede personalizar la ruta predeterminada.



 a| 
Añada todos los hosts del clúster
 a| 
Seleccione esta casilla de comprobación para añadir todos los nodos del clúster en un WSFC.



 a| 
Omitir comprobaciones previas a la instalación
 a| 
Seleccione esta casilla de comprobación si ya ha instalado los plugins manualmente y no desea validar si el host cumple con los requisitos para la instalación del plugin.



 a| 
Utilice Group Managed Service Account (GMSA) para ejecutar los servicios de plug-in
 a| 
Seleccione esta casilla de verificación si desea utilizar la cuenta de servicio gestionado de grupo (GMSA) para ejecutar los servicios de complemento.

Proporcione el nombre de GMSA con el siguiente formato: _Domainname\accountName$_.


NOTE: GMSA se utilizará como cuenta de servicio de inicio de sesión solo en el complemento SnapCenter para el servicio de Windows.

|===
. Haga clic en *Enviar*.
+
Si no ha seleccionado la casilla de comprobación *Skip prechecks*, el host se valida para comprobar si cumple con los requisitos para la instalación del plugin. Se comprueban el espacio en disco, la memoria RAM, la versión de PowerShell, la versión de NET y la ubicación comparando estos elementos con los requisitos mínimos. Si no se satisfacen los requisitos mínimos, se muestran los mensajes de error o advertencia correspondientes.

+
Si el error está relacionado con el espacio en disco o la RAM, puede actualizar el archivo web.config ubicado en `C:\Program Files\NetApp\SnapCenter` Webapp para modificar los valores predeterminados. Si el error está relacionado con otros parámetros, primero debe solucionar el problema.

+

NOTE: En una configuración de alta disponibilidad, si actualiza el archivo web.config, debe actualizar el archivo en ambos nodos.

. Supervise el progreso de la instalación.

