---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: Puede crear una nueva política de backup para recursos antes de usar SnapCenter para realizar backups de sistemas de archivos Windows, o bien puede crear una nueva política de backup en el momento de crear un grupo de recursos o al realizar el backup de un recurso. 
---
= Crear políticas de backup para sistemas de archivos Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear una nueva política de backup para recursos antes de usar SnapCenter para realizar backups de sistemas de archivos Windows, o bien puede crear una nueva política de backup en el momento de crear un grupo de recursos o al realizar el backup de un recurso.

.Antes de empezar
* Debe tener definida una estrategia de backup. link:task_define_a_backup_strategy_for_windows_file_systems.html["Leer más"^]
* Debe tener preparada la protección de datos.
+
Para prepararse para la protección de datos, debe completar ciertas tareas, como instalar SnapCenter, añadir hosts, detectar recursos y crear conexiones de máquina virtual de almacenamiento (SVM).

* Si desea replicar snapshots en un almacenamiento secundario con snapmirror o snapvault, el administrador de SnapCenter debe haberle asignado las SVM de los volúmenes de origen y de destino.
* Si desea ejecutar los scripts de PowerShell en scripts previos y posteriores, debe establecer el valor del parámetro usePowershellProcessforScripts en TRUE en el archivo web.config.
+
El valor predeterminado es FALSE

* Revise los requisitos previos y las limitaciones específicos de SnapMirror Active Sync. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"].


.Acerca de esta tarea
* LA RUTA_DE_SCRIPTS se define mediante la clave PredefinedWindowsScriptsDirectory ubicada en el archivo SMCoreServiceHost.exe.Config del host del plugin.
+
Si es necesario, puede cambiar esta ruta y reiniciar el servicio SMcore. Se recomienda utilizar la ruta predeterminada para la seguridad.

+
El valor de la tecla se puede mostrar desde swagger a través de la API: API /4.7/config settings

+
Puede usar LA API GET para mostrar el valor de la clave. No se admite LA CONFIGURACIÓN de API.

* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
** Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención. Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.




.Pasos
. En el panel de navegación izquierdo, selecciona *Configuración*.
. En la página Configuración, selecciona *Políticas*.
. Selecciona *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Backup and Replication, realice las siguientes tareas:
+
.. Seleccione un valor para backup.
+
|===
| Opción | Descripción 


 a| 
Copia de seguridad consistente del sistema de archivos
 a| 
Elija esta opción si desea que SnapCenter ponga en modo inactivo la unidad de disco en la que reside el sistema de archivos antes de que comience la operación de backup y luego la reanude tras finalizar dicha operación.



 a| 
Copia de seguridad coherente con los fallos del sistema de archivos
 a| 
Elija esta opción si no desea que SnapCenter ponga en modo inactivo la unidad de disco en la que reside el sistema de archivos.

|===
.. Seleccione una frecuencia de programación (también llamada tipo de política).
+
La política especifica solamente la frecuencia de backup. La programación de protección específica para realizar el backup se define en el grupo de recursos. Por lo tanto, dos o más grupos de recursos pueden compartir la misma política y frecuencia de backup y, a su vez, tener diferentes programaciones de backup.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.

.. Seleccione una etiqueta de política.
+
Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+

NOTE: Si ha seleccionado *Actualizar SnapMirror después de crear una copia Snapshot local*, puede especificar opcionalmente la etiqueta de la directiva secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.



. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Actualizar SnapMirror tras crear una copia Snapshot local
 a| 
Seleccione esta opción para crear copias de SnapMirror de conjuntos de backups en otro volumen (SnapMirror).

Esta opción debe estar habilitada para la sincronización activa de Snapmirror.

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Consulte link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["Consulte los backups y los clones relacionados en la página Topology"].



 a| 
Actualizar SnapVault después de crear una copia Snapshot
 a| 
Seleccione esta opción para realizar una replicación de backup de disco a disco.

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón Refresh de la página Topology, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recupera de ONTAP.

Cuando SnapLock se configura solo en el secundario de ONTAP conocido como Almacén de SnapLock, al hacer clic en el botón Actualizar de la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

Para obtener más información sobre el Almacén SnapLock, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Confirmar copias Snapshot a WORM en un destino de almacén"]



 a| 
Número de reintentos con error
 a| 
Introduzca el número de intentos de replicación que deben producirse antes de que se interrumpa el proceso.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.

. En la página Retention settings, especifique la configuración de retención para backups bajo demanda y para cada frecuencia de programación que seleccionó.
+
|===
| Opción | Descripción 


 a| 
Copias de Snapshot totales que se deben conservar
 a| 
Elija esta opción si desea especificar el número de instantáneas que SnapCenter almacena antes de eliminarlas automáticamente.



 a| 
Conserve copias Snapshot para
 a| 
Elija esta opción si desea especificar el número de días que SnapCenter retiene una copia de backup antes de eliminarla.



 a| 
Período de bloqueo de copia de instantánea
 a| 
Seleccione el período de bloqueo de la instantánea y especifique la duración en días, meses o años.

El período de retención de SnapLock debe ser inferior a 100 años.

|===
+

IMPORTANT: Debe establecer el número de retención en 2 o superior. El valor mínimo para el número de retención es 2.

+

NOTE: El valor máximo de retención es 1018.  Las copias de seguridad fallarán si la retención se establece en un valor superior al que admite la versión de ONTAP .

. En la página Script, introduzca la ruta del script previo o script posterior que desea que el servidor SnapCenter ejecute antes o después de la operación de backup respectivamente, y el límite de tiempo que SnapCenter espera para que se ejecute el script.
+
Por ejemplo, se puede ejecutar un script para actualizar capturas SNMP, automatizar alertas y enviar registros.

+

NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

