---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: Puede utilizar SnapCenter para restaurar backups de sistemas de archivos. La restauración de sistema de archivos es un proceso multifase que copia todos los datos de un backup especificado en la ubicación original del sistema de archivos. 
---
= Restaurar backups de sistemas de archivos Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar SnapCenter para restaurar backups de sistemas de archivos. La restauración de sistema de archivos es un proceso multifase que copia todos los datos de un backup especificado en la ubicación original del sistema de archivos.

.Antes de empezar
* Debe tener un backup del sistema de archivos.
* Si existe una operación programada, como una operación de backup, en curso para un sistema de archivos, debe cancelarse esa operación antes de poder iniciar una operación de restauración.
* Solo puede restaurar un backup de sistema de archivos a la ubicación original, no a una ruta alternativa.
+
No puede restaurar un solo archivo desde un backup porque el sistema de archivos restaurado sobrescribe los datos en la ubicación original del sistema de archivos. Para restaurar un solo archivo desde un backup del sistema de archivos, debe clonar el backup y acceder al archivo en el clon.

* No puede restaurar un sistema o volumen de arranque.
* SnapCenter puede restaurar los sistemas de archivos de un clúster de Windows sin que el grupo de clústeres esté sin conexión.


.Acerca de esta tarea
* LA RUTA_DE_SCRIPTS se define mediante la clave PredefinedWindowsScriptsDirectory ubicada en el archivo SMCoreServiceHost.exe.Config del host del plugin.
+
Si es necesario, puede cambiar esta ruta y reiniciar el servicio SMcore. Se recomienda utilizar la ruta predeterminada para la seguridad.

+
El valor de la tecla se puede mostrar desde swagger a través de la API: API /4.7/config settings

+
Puede usar LA API GET para mostrar el valor de la clave. No se admite LA CONFIGURACIÓN de API.

* Para la operación de restauración de sincronización activa de SnapMirror, debe seleccionar el backup de la ubicación principal.
* Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.


[role="tabbed-block"]
====
.UI de SnapCenter
--
.Pasos
. En el panel de navegación de la izquierda, haga clic en *Recursos* y, a continuación, seleccione el plugin adecuado en la lista.
. Para filtrar la lista de recursos, seleccione las opciones File System y Resource Group.
. Seleccione un grupo de recursos de la lista y, a continuación, haga clic en *Restaurar*.
. En la página backups, seleccione si desea restaurar desde los sistemas de almacenamiento principal o secundario y luego seleccione un backup para restaurar.
. Seleccione sus opciones en el asistente Restore.
. Puede introducir la ruta y los argumentos del script previo o script posterior que desea que SnapCenter ejecute antes o después de la operación de restauración, respectivamente.
+
Por ejemplo, es posible ejecutar un script para actualizar las capturas SNMP, automatizar alertas, enviar registros, etc.

+

NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.

. En la página Notification, seleccione una de las siguientes opciones:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Registre los eventos del servidor SnapCenter en el syslog del sistema de almacenamiento
 a| 
Seleccione esta opción para registrar los eventos de servidor de SnapCenter en el syslog del sistema de almacenamiento.



 a| 
Envíe una notificación de AutoSupport sobre las operaciones con errores al sistema de almacenamiento
 a| 
Seleccione esta opción para enviar información sobre las operaciones con errores a NetApp mediante AutoSupport.



 a| 
Preferencia de correo electrónico
 a| 
Seleccione *Always*, *On Failure* o *On failure or warning* para enviar mensajes de correo electrónico a los destinatarios después de restaurar las copias de seguridad. Introduzca el servidor SMTP, la línea de asunto predeterminada del correo electrónico y las direcciones de correo electrónico del remitente y destinatario.

|===
. Revise el resumen y, a continuación, haga clic en *Finalizar*.
. Supervise el progreso de la operación haciendo clic en *Monitor* > *Jobs*.



IMPORTANT: Si el sistema de archivos restaurado contiene una base de datos, debe también restaurar la base de datos. Si no restaura la base de datos, la base de datos puede quedar en estado no válido. Para obtener información sobre cómo restaurar bases de datos, consulte la guía de protección de datos de esa base de datos.

--
.Cmdlets de PowerShell
--
.Pasos
. Inicie una sesión de conexión con el servidor de SnapCenter para el usuario especificado mediante el cmdlet de Open-SmConnection.
+
[listing]
----
PS C:\> Open-Smconnection
----
. Para recuperar la información sobre los backups que desea restaurar, puede usar los cmdlets Get-SmBackup y Get-SmBackupReport.
+
Este ejemplo muestra información sobre todos los backups disponibles:

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
En este ejemplo, se muestra información detallada sobre el backup del 29 de enero de 2015 al 3 de febrero de 2015:

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Puede restaurar los datos del backup mediante el cmdlet Restore-SmBackup.
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].

--
====