---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: Es posible usar scripts previos y posteriores como parte de las operaciones de protección de datos. Estos scripts permiten la automatización antes o después del trabajo de protección de datos. Por ejemplo, se puede incluir un script para notificar automáticamente si hay fallos o advertencias en un trabajo de protección de datos. Para configurar scripts previos y posteriores, es necesario comprender algunos de los requisitos para crearlos. 
---
= Scripts previos y posteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar scripts previos y posteriores como parte de las operaciones de protección de datos. Estos scripts permiten la automatización antes o después del trabajo de protección de datos. Por ejemplo, se puede incluir un script para notificar automáticamente si hay fallos o advertencias en un trabajo de protección de datos. Para configurar scripts previos y posteriores, es necesario comprender algunos de los requisitos para crearlos.



== Tipos de scripts compatibles

Los siguientes tipos de scripts son compatibles con Windows:

* Archivos de lotes
* Scripts de PowerShell
* Scripts Perl


Los siguientes tipos de scripts se admiten para UNIX:

* Scripts Perl
* Scripts Python
* Scripts de shell
+

NOTE: Junto con el shell bash predeterminado, también se admiten otros shell como sh-shell, k-shell y c-shell.





== Ruta del script

Todos los scripts previos y posteriores que se ejecutan como parte de las operaciones de SnapCenter, en sistemas de almacenamiento virtualizados y no virtualizados, se ejecutan en el host del plugin.

* Los scripts de Windows deben encontrarse en el host del plugin.



NOTE: La ruta scripts previos o posteriores no debe incluir unidades o recursos compartidos. La ruta debe ser relativa a LA RUTA DE ACCESO_SCRIPTS.

* Los scripts de UNIX deben encontrarse en el host del plugin.



NOTE: La ruta de acceso del script se valida en el momento de la ejecución.



== Dónde especificar scripts

Los scripts se especifican en las políticas de backup. Cuando se inicia una tarea de backup, la política asocia automáticamente el script con los recursos que se incluirán en el backup. Al crear una política de backup, se pueden especificar los argumentos de script previo y script posterior.


NOTE: No puede especificar varios scripts.



== Tiempo de espera de scripts

De forma predeterminada, el tiempo de espera se establece en 60 segundos. Puede modificar el valor del tiempo de espera.



== Salida de script

El directorio predeterminado para los archivos de salida scripts previos y posteriores de Windows es Windows\System32.

No hay una ubicación predeterminada para los scripts previos y posteriores de UNIX. Puede redirigir el archivo de salida a cualquier ubicación preferida.
