---
permalink: upgrade/upgrade_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, linux 
summary: Puede utilizar el archivo de instalación del servidor de SnapCenter para actualizar el servidor de SnapCenter. 
---
= Actualice el servidor SnapCenter en el host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el archivo de instalación del servidor de SnapCenter para actualizar el servidor de SnapCenter.

* Pasos*

. Realice una de las acciones para actualizar el servidor SnapCenter.
+
|===
| Si desea ejecutar... | Realice lo siguiente... 


 a| 
Actualización no interactiva
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DUPGRADE=<value> -DINSTALL_LOG_NAME=<filename>`

Ejemplo: Sudo ./snapcenter_linux_server.bin -i silent -DUPGRADE=1 -DINSTALL_LOG_NAME=InstallerLog.log

Los registros se almacenarán en _/var/opt/snapcenter/logs_.

Parámetros que se transferirán para la actualización:

** DINSTALL_LOG_NAME: Nombre del archivo de registro donde se almacenarán los registros de instalación.
** DUPGRADE: El valor predeterminado es 0. Especifique este parámetro y su valor como cualquier entero que no sea 0 para actualizar el servidor SnapCenter.




 a| 
Instalación interactiva
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

Se le pedirá que confirme la actualización. Introduzca un valor distinto de 0 para confirmar la actualización del servidor SnapCenter.

|===



NOTE: Debe cerrar sesión y, a continuación, iniciar sesión en SnapCenter, o bien cerrar y abrir un nuevo explorador para acceder a la interfaz gráfica de usuario de SnapCenter.
