---
permalink: protect-hana/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: El tipo de backup especifica el tipo de backup que desea crear. SnapCenter admite los tipos de backups basados en archivos y backups basados en copias de Snapshot para bases de datos de SAP HANA. 
---
= Tipo de backups admitido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El tipo de backup especifica el tipo de backup que desea crear. SnapCenter admite los tipos de backups basados en archivos y backups basados en copias de Snapshot para bases de datos de SAP HANA.



== Backups basados en archivos

Los backups basados en archivos verifican la integridad de la base de datos. Es posible programar una operación de backup basado en archivos para que se produzca en intervalos específicos. Solo se realiza un backup de los inquilinos activos. No es posible restaurar ni clonar backups basados en archivos desde SnapCenter.



== Backup basado en copia de Snapshot

Los backups basados en copia de Snapshot aprovechan la tecnología de copia de Snapshot de NetApp para crear copias en línea y de solo lectura de los volúmenes en los cuales residen las bases de datos de SAP HANA.
