---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Antes de instalar el paquete de plugins de SnapCenter para Linux, tiene que conocer bien algunos requisitos básicos de espacio y tamaño del sistema host. 
---
= Requisitos del host para instalar el paquete de plugins de SnapCenter para Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el paquete de plugins de SnapCenter para Linux, tiene que conocer bien algunos requisitos básicos de espacio y tamaño del sistema host.

|===
| Elemento | Requisitos 


 a| 
Sistemas operativos
 a| 
* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server (SLES)


Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"].



 a| 
RAM mínima para el plugin de SnapCenter en el host
 a| 
1 GB



 a| 
Espacio de registro e instalación mínimo para el plugin de SnapCenter en el host
 a| 
2 GB


NOTE: Debe asignar el espacio en disco suficiente y supervisar el consumo de almacenamiento en la carpeta de registros. El espacio de registro necesario varía, según la cantidad de entidades que se han de proteger y la frecuencia de las operaciones de protección de datos. Si no hay espacio en disco suficiente, no se crearán registros de las operaciones ejecutadas recientemente.



 a| 
Paquetes de software obligatorios
 a| 
Java 11 Oracle Java y OpenJDK

Si ha actualizado JAVA a la versión más reciente, debe asegurarse de que la opción JAVA_HOME ubicada en /var/opt/snapcenter/spl/etc/spl.properties esté configurada en la versión DE JAVA correcta y en la ruta de acceso correcta.

Para obtener la información más reciente sobre las versiones compatibles, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"].

|===