---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_windows_hana.html 
sidebar: sidebar 
keywords: SAP HANA, plug-ins 
summary: Antes de instalar el paquete de plugins de SnapCenter para Windows, debe estar familiarizado con algunos requisitos básicos de espacio y tamaño del sistema host. 
---
= Requisitos del host para instalar el paquete de plugins de SnapCenter para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar el paquete de plugins de SnapCenter para Windows, debe estar familiarizado con algunos requisitos básicos de espacio y tamaño del sistema host.

|===
| Elemento | Requisitos 


 a| 
Sistemas operativos
 a| 
Microsoft Windows

Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/imt/imt.jsp?components=180321;180339;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].



 a| 
RAM mínima para el plugin de SnapCenter en el host
 a| 
1 GB



 a| 
Espacio de registro e instalación mínimo para el plugin de SnapCenter en el host
 a| 
5 GB


NOTE: Debe asignar el espacio en disco suficiente y supervisar el consumo de almacenamiento en la carpeta de registros. El espacio de registro necesario varía en función de la cantidad de entidades que se han de proteger y la frecuencia de las operaciones de protección de datos. Si no hay espacio en disco suficiente, no se crearán registros de las operaciones ejecutadas recientemente.



 a| 
Paquetes de software obligatorios
 a| 
* ASP.NET Core Runtime 8.0.12 (y todos los parches 8,0.x posteriores) Hosting Bundle
* PowerShell Core 7.4.2
* Java 11 Oracle Java y OpenJDK


Para obtener información específica sobre la solución de problemas de .NET, consulte https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["La actualización o instalación de SnapCenter falla en sistemas heredados que no tienen conexión a Internet."]

|===