---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: Antes de añadir un host e instalar los paquetes de plugins, debe cumplir con todos los requisitos. Plugin SnapCenter para base de datos SAP HANA está disponible en entornos Windows y Linux. 
---
= Requisitos previos para añadir hosts e instalar el plugin de SnapCenter para bases de datos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de añadir un host e instalar los paquetes de plugins, debe cumplir con todos los requisitos. Plugin SnapCenter para base de datos SAP HANA está disponible en entornos Windows y Linux.

* Debe haber instalado Java 1.8 64 bit en su host.
+

NOTE: IBM Java no es compatible.

* Debe haber instalado el terminal interactivo de base de datos SAP HANA (cliente HDBSQL) en el host.
* Para Windows, el plugin Creator Service debe ejecutarse con el usuario de Windows "'LocalSystem'", que es el comportamiento predeterminado cuando el plugin para base de datos SAP HANA se instala como administrador de dominio.
* Para Windows, se deben crear claves de almacenamiento como usuario SYSTEM.
* Al instalar un plugin en un host de Windows, si especifica una credencial que no está integrada o si el usuario pertenece a un usuario de grupo de trabajo local, debe deshabilitar UAC en el host. El plugin de SnapCenter para Microsoft Windows se pondrá en marcha de forma predeterminada con el plugin de SAP HANA en hosts Windows.
* Para host Linux, se accede a las claves de almacenamiento de usuario seguro HDB como usuario de sistema operativo HDBSQL.
* El servidor de SnapCenter debe tener acceso al puerto 8145 o un puerto personalizado de plugin para el host de base de datos SAP HANA.




== Host Windows

* Debe tener un usuario de dominio con privilegios de administrador local y permisos locales para iniciar sesión en el host remoto.
* Cuando se instala el plugin para base de datos SAP HANA en un host Windows, el plugin de SnapCenter para Microsoft Windows se instala automáticamente.
* Debe haber habilitado la conexión SSH por contraseña para el usuario raíz o no raíz.
* Debe haber instalado Java 1.8 64 bit en su host de Windows.
+
http://www.java.com/en/download/manual.jsp["Descargas de Java para todos los sistemas operativos"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"]





== Hosts Linux

* Debe haber habilitado la conexión SSH por contraseña para el usuario raíz o no raíz.
* Debe haber instalado Java 1.8 64 bit en su host Linux.
+
http://www.java.com/en/download/manual.jsp["Descargas de Java para todos los sistemas operativos"]

+
https://imt.netapp.com/matrix/imt.jsp?components=112393;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"]

* Para bases de datos SAP HANA que se ejecutan en un host Linux, mientras se instala el plugin para base de datos SAP HANA, el plugin de SnapCenter para UNIX se instala automáticamente.
* Debe tener *bash* como shell por defecto para la instalación del plug-in.




== Comandos suplementarios

Para ejecutar un comando complementario en el plugin de SnapCenter para SAP HANA, debe incluirlo en la `allowed_commands.config` archivo.

`allowed_commands.config` El archivo está ubicado en el subdirectorio «ETC» del directorio del plugin de SnapCenter para SAP HANA.

.Host Windows
Valor predeterminado: `C:\Program Files\NetApp\SnapCenter\HANA\etc\allowed_commands.config`

Ruta personalizada: `<Custome_Directory>\NetApp\SnapCenter\HANA\etc\allowed_commands.config`
Host de Windows:

.Hosts Linux
Valor predeterminado: `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

Ruta personalizada: `<Custome_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

Para permitir comandos complementarios en el host del plugin, abra `allowed_commands.config` archivo en un editor. Introduzca cada comando en una línea independiente. No distingue mayúsculas de minúsculas.
Por ejemplo:

comando: mount

comando: umount

Asegúrese de especificar el nombre de ruta completo. El nombre de ruta debe escribirse entre comillas si contiene espacios.
Por ejemplo:

Comando: «C:\Program Files\NetApp\SnapCreator commands\sdcli.exe»

comando: myscript.bat

Si la `allowed_commands.config` el archivo no está presente, los comandos o la ejecución del script se bloquearán y el flujo de trabajo fallará con el siguiente error:

ejecución '[/mnt/mount -a] no permitida. Autorizar agregando el comando en el archivo %s en el host del plugin.

Si el comando o el script no está presente en `allowed_commands.config`, el comando o la ejecución del script se bloqueará y el flujo de trabajo fallará con el siguiente error:

ejecución '[/mnt/mount -a] no permitida. Autorizar agregando el comando en el archivo %s en el host del plugin.


NOTE: No debe utilizar una entrada comodín (*) para permitir todos los comandos.
