---
permalink: protect-hana/reference_storage_types_supported_by_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: storage types, 
summary: 'SnapCenter es compatible con una amplia gama de tipos de almacenamiento tanto en máquinas físicas como máquinas virtuales (VM). Debe verificar la compatibilidad de su tipo de almacenamiento antes de instalar el plugin de SnapCenter para base de datos SAP HANA.' 
---
= Tipos de almacenamiento compatibles con el plugin de SnapCenter para base de datos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter es compatible con una amplia gama de tipos de almacenamiento tanto en máquinas físicas como máquinas virtuales (VM). Debe verificar la compatibilidad de su tipo de almacenamiento antes de instalar el plugin de SnapCenter para base de datos SAP HANA.

|===
| Máquina | Tipo de almacenamiento 


 a| 
Servidor físico
 a| 
* LUN conectados a FC
* LUN conectados a iSCSI
* Volúmenes conectados en NFS




 a| 
VMware ESXi
 a| 
* Los LUN de RDM conectados por un HBAScanning de adaptadores de bus de host (HBA) FC o iSCSI pueden tardar mucho en completarse debido a que SnapCenter analiza todos los adaptadores de bus de host presentes en el host.
+
Puede editar el archivo *LinuxConfig.pm* ubicado en _/opt/NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ para establecer el valor del parámetro *SCSI_HOSTS_OPTIMIZED_RESCAN* en 1 para volver a analizar sólo los HBA que aparecen en HBA_DRIVER_NAMES.

* LUN iSCSI conectados directamente al sistema invitado por el iniciador de iSCSI
* VMDK en almacenes de datos NFS
* VMDK en VMFS creado
* Volúmenes NFS conectados directamente con el Guest VM
* Almacenes de datos VVOL en NFS y SAN
+
El almacén de datos VVOL solo se puede aprovisionar con ONTAP Tools para VMware vSphere.



|===