---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Antes de usar SnapCenter para realizar un backup de los recursos de la base de datos SAP HANA, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups. 
---
= Crear políticas de backup para bases de datos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar un backup de los recursos de la base de datos SAP HANA, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups.

.Antes de empezar
* Debe tener definida una estrategia de backup.
+
Para obtener más detalles, consulte cómo definir una estrategia de protección de datos para las bases de datos SAP HANA.

* Debe haberse preparado para la protección de datos completando tareas como instalar SnapCenter, añadir hosts, configurar las conexiones del sistema de almacenamiento y añadir recursos.
* El administrador de SnapCenter debe haberle asignado las instancias de SVM de los volúmenes de origen y de destino en caso de que replique snapshots en un reflejo o almacén.
+
Además, puede definir la configuración de replicación, script y aplicaciones en la política. Estas opciones ahorran tiempo cuando se desea volver a utilizar la política con otro grupo de recursos.

* Revise los requisitos previos y las limitaciones específicos de SnapMirror Active Sync. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"].


.Acerca de esta tarea
* Replicación de sistemas SAP HANA
+
** Puede proteger el sistema SAP HANA principal y llevar a cabo todas las operaciones de protección de datos.
** Puede proteger el sistema SAP HANA secundario, pero no es posible crear los backups.
+
Tras la conmutación al respaldo, toda la operación de protección de datos se puede realizar mientras el sistema SAP HANA secundario se convierte en el sistema SAP HANA principal.

+
No puede crear un backup para el volumen de datos SAP HANA, pero SnapCenter sigue protegiendo los volúmenes no data (NDV).



* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
** Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención. Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.




.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Policy type, realice los siguientes pasos:
+
** Elija el tipo de almacenamiento
** Elija el tipo de backup:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Crear un backup mediante la tecnología Snapshot
 a| 
Seleccione *Snapshot Based*.



 a| 
Realice una comprobación de integridad de la base de datos
 a| 
Seleccione *copia de seguridad basada en archivos*. Solo se realiza un backup de los inquilinos activos.

|===


. En la página Snapshot and Replication, realice los siguientes pasos:
+
** Especifique el tipo de programa seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de backup mientras crea un grupo de recursos. Esto le permite crear grupos de recursos que comparten la misma política y frecuencia de backup, pero también le permite asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.



. En la página Snapshot and Replication, especifique la configuración de retención para el tipo de backup y el tipo de programación seleccionados en la página Backup Type:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Mantenga un cierto número de Snapshots
 a| 
Seleccione *Copias para guardar* y, a continuación, especifique el número de instantáneas que desea conservar.

Si la cantidad de snapshots supera el número especificado, las snapshots se eliminan empezando por las más antiguas.


NOTE: El valor de retención máximo es 1018 para recursos en ONTAP 9.4 o posterior, y 254 para recursos en ONTAP 9.3 o anterior. Se producirá un error en los backups si la retención se establece en un valor superior a la versión de ONTAP subyacente.


IMPORTANT: Para los backups basados en copias de Snapshot, debe establecer el número de retención en 2 o más si va a habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera Snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva Snapshot en el destino.


NOTE: Para la replicación de sistemas SAP HANA, se recomienda añadir todos los recursos del sistema SAP HANA a un grupo de recursos. De este modo se garantiza la conservación de la cantidad adecuada de backups.


NOTE: Para la replicación del sistema SAP HANA, el número total de snapshots tomadas será igual a la retención establecida para el grupo de recursos.  La eliminación de la copia Snapshot más antigua se basa en el nodo en el que se encuentra la copia Snapshot más antigua.
Por ejemplo, la retención se establece en 7 para un grupo de recursos con la replicación de sistemas SAP HANA principal y la replicación de sistemas SAP HANA secundaria.  Puede tomar un máximo de 7 Snapshots al mismo tiempo, incluyendo la replicación de sistemas SAP HANA primaria y la replicación de sistemas SAP HANA secundaria.



 a| 
Mantenga los Snapshots durante una cierta cantidad de días
 a| 
Seleccione *Retener copias para* y, a continuación, especifique el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de la copia snapshot primaria
 a| 
Seleccione Snapshot copy locking period y seleccione días, meses o años.

El período de retención de SnapLock debe ser inferior a 100 años.



 a| 
Período de bloqueo de copia de snapshot secundaria
 a| 
Seleccione *Periodo de bloqueo de copia de instantánea secundaria* y seleccione Días, Meses o Años.

Para que esta opción sea efectiva, debe realizar las siguientes tareas:

** Seleccione el *Periodo de bloqueo de copia de instantánea primaria*.
** Seleccione una de las opciones de replicación secundaria o ambas.


|===
. Seleccione una etiqueta de Snapshot.
+
Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+

NOTE: Si ha seleccionado *Actualizar SnapMirror después de crear una copia Snapshot local*, puede especificar opcionalmente la etiqueta de la directiva secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.

. Para los backups basados en copias de Snapshot, en la sección Select secondary replication options, seleccione una o ambas de las siguientes opciones de replicación secundaria:
+

NOTE: Debe seleccionar las opciones de replicación secundarias para que el *Periodo de bloqueo de copia de instantánea secundaria* sea efectivo.

+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
*Actualizar SnapMirror después de crear una copia Snapshot local*
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de backup en otro volumen (replicación de SnapMirror).

Esta opción debe estar habilitada para la sincronización activa de SnapMirror.

Si la relación en ONTAP es del tipo Reflejo y almacén y si selecciona solo esta opción, la instancia de Snapshot creada en el origen no se transferirá al destino, pero figurará en el destino. Si esta Snapshot se selecciona desde el destino para realizar una operación de restauración, entonces aparece el mensaje de error Secondary Location is not available for the selected vaulted/mirrored backup.

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal.

Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Consulte link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Consulte los backups y los clones de la base de datos SAP HANA en la página Topology"].



 a| 
*Actualizar SnapVault después de crear una copia Snapshot local*
 a| 
Seleccione esta opción para realizar una replicación de backup disco a disco (backups de SnapVault).

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Cuando SnapLock se configura solo en el secundario desde ONTAP conocido como Almacén de SnapLock, al hacer clic en el botón *Refrescar* de la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

Para obtener más información sobre el Almacén SnapLock, consulte https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Confirmar copias Snapshot a WORM en un destino de almacén"]

Consulte link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Consulte los backups y los clones de la base de datos SAP HANA en la página Topology"].



 a| 
*Número de reintentos de error*
 a| 
Escriba el número máximo de intentos de replicación que se permitirán antes de que la operación se detenga.

|===
+

NOTE:  Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

