---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: Es posible crear plugins personalizados para las aplicaciones que se usan y emplear SnapCenter para el backup, la restauración o la clonado de tales aplicaciones. Al igual que otros complementos de SnapCenter, los plugins personalizados funcionan como componentes del host en el software Snap Center de NetApp y permiten la protección de datos para aplicaciones y la gestión de recursos. 
---
= Información general sobre los plugins personalizados de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear plugins personalizados para las aplicaciones que se usan y emplear SnapCenter para el backup, la restauración o la clonado de tales aplicaciones. Al igual que otros plugins de SnapCenter, los plugins personalizados funcionan como componentes del host en el software SnapCenter de NetApp y permiten la protección de datos para aplicaciones y la gestión de recursos.

Cuando se instalan plugins personalizados, es posible usar SnapCenter con la tecnología NetApp SnapMirror para crear mirrors de conjuntos de backups en otro volumen, y la tecnología NetApp SnapVault para la replicación de backup de disco a disco. Los plugins personalizados se pueden utilizar tanto en entornos de Windows como de Linux.


NOTE: La interfaz de línea de comandos no admite los comandos de los plugins personalizados de SnapCenter SnapCenter.

NetApp proporciona el complemento de almacenamiento para realizar operaciones de protección de datos del volumen de datos en el almacenamiento de ONTAP mediante el marco de trabajo de complementos personalizados integrado en SnapCenter.

Puede instalar el plugin personalizado y el plugin de almacenamiento en la página Add Host.

link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html["Añada hosts e instale paquetes de plugins en hosts remotos."^]

NetApp también proporciona MySQL, MAXDB, DB2, SYBASE y DPGLUE Plug-ins personalizados MongoDB, ORASCPM y PostgreSQL. Estos plugins pueden descargarse del https://["Almacén de automatización del almacenamiento de NetApp"^].


NOTE: La política de soporte de SnapCenter cubrirá la compatibilidad con el marco de complementos personalizados de SnapCenter, el motor principal y las API asociadas. El soporte técnico no cubrirá el código fuente del complemento ni los scripts asociados incluidos en el marco de complementos personalizados.

Para crear sus propios plugins personalizados, consulte link:concept_develop_a_plug_in_for_your_application.html["Desarrolle un complemento para la aplicación"^].
