---
permalink: protect-scc/concept_develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords:  
summary: El servidor de SnapCenter permite poner en marcha y gestionar sus aplicaciones como complementos en SnapCenter. 
---
= Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El servidor de SnapCenter permite poner en marcha y gestionar sus aplicaciones como complementos en SnapCenter. Las aplicaciones de su elección pueden conectarse al servidor de SnapCenter para disfrutar de funcionalidades de protección y gestión de datos.

SnapCenter le permite desarrollar complementos personalizados utilizando diferentes lenguajes de programación. Puede desarrollar un complemento personalizado utilizando Perl, Java, BATCH u otros lenguajes de scripting.

Para utilizar plugins personalizados en SnapCenter, debe realizar las siguientes tareas:

* Cree un complemento para su aplicación siguiendo las instrucciones de esta guía
* Cree un archivo de descripción
* Exporte el plugin personalizado para instalarlo en el host de SnapCenter
* Cargue el archivo zip del plugin en el servidor de SnapCenter




== Gestión de complementos genérica en todas las llamadas API

Para cada llamada a la API, utilice la siguiente información:

* Parámetros del plugin
* códigos de salida
* Registrar mensajes de error
* Coherencia de datos




=== Utilice los parámetros del plugin

Se pasa un conjunto de parámetros al plug-in como parte de cada llamada API realizada. En la siguiente tabla, se muestra información específica de los parámetros.

|===
| Parámetro | Específico 


 a| 
ACCIÓN
 a| 
Determina el nombre del flujo de trabajo. Por ejemplo, descubra, copia de seguridad, archivoOrVolRestore o cloneVolAndLun



 a| 
RECURSOS
 a| 
Enumera los recursos que se deben proteger. UID y tipo identifican un recurso. La lista se presenta al plugin con el siguiente formato:

“<UID>,<TYPE>;<UID>,<TYPE>”. Por ejemplo, “Instance1,instancia;Instance2\\DB1,base de datos”



 a| 
NOMBRE_APLICACIÓN
 a| 
Determina qué plugin se está utilizando. Por ejemplo, DB2, MYSQL. El servidor SnapCenter cuenta con compatibilidad integrada para las aplicaciones de la lista. Este parámetro distingue mayúsculas de minúsculas.



 a| 
APP_IGNORE_ERROR
 a| 
(Y o N) esto hace que SnapCenter salga o no salga cuando se encuentra un error de aplicación. Esto es útil cuando se realiza el backup de varias bases de datos y no se desea que un solo fallo detenga la operación de backup.



 a| 
<RESOURCE_NAME>__APP_INSTANCE_USERNAME
 a| 
Se han establecido las credenciales de SnapCenter para el recurso.



 a| 
<RESOURCE_NAME>_APP_INSTANCE_PASSWORD
 a| 
Se han establecido las credenciales de SnapCenter para el recurso.



 a| 
<CUSTOM_PARAM>_<RESOURCE_NAME>
 a| 
Todos los valores de clave personalizada de nivel de recursos están disponibles para los plug-ins con “<RESOURCE_NAME>_”. Por ejemplo, si una clave personalizada es “MASTER_SLAVE” para un recurso llamado “MySQLDB”, estará disponible como MySQLDB_MASTER_SLAVE

|===


=== Utilice los códigos de salida

El plugin devuelve el estado de la operación a su host mediante códigos de salida. Cada código tiene un significado específico y el plug-in utiliza el código de salida derecho para indicar lo mismo.

En la siguiente tabla se muestran los códigos de error y su significado.

|===
| Código de salida | Específico 


 a| 
0
 a| 
Funcionamiento correcto.



 a| 
99
 a| 
La operación solicitada no es compatible o está implementada.



 a| 
100
 a| 
Error en la operación, omita la pausa y salga. La función de inactividad está predeterminada.



 a| 
101
 a| 
Error en la operación, continúe con la operación de backup.



 a| 
otros
 a| 
Error en la operación, ejecución de la reanudación y salida.

|===


=== Registrar mensajes de error

Los mensajes de error pasan del plugin al servidor de SnapCenter. El mensaje incluye el mensaje, el nivel de registro y la Marca de hora.

En la tabla siguiente se enumeran los niveles y sus propósitos.

|===
| Parámetro | Específico 


 a| 
INFORMACIÓN
 a| 
mensaje informativo



 a| 
ADVERTIR
 a| 
mensaje de advertencia



 a| 
ERROR
 a| 
mensaje de error



 a| 
DEPURAR
 a| 
depurar mensaje



 a| 
TRAZA
 a| 
mensaje de seguimiento

|===


=== Conserve la consistencia de datos

Los plugins personalizados conservan datos entre operaciones de la misma ejecución del flujo de trabajo. Por ejemplo, un plugin puede almacenar datos al final de la inactividad, que se puede utilizar durante la operación de inactivación.

Los datos que se van a conservar se establecen como parte del objeto de resultado mediante el complemento. Sigue un formato específico y se describe con detalle en cada estilo de desarrollo de complementos.
