---
permalink: protect-scc/concept_how_resources_resource_groups_and_policies_are_used_for_protecting_custom_plug_in_resources.html 
sidebar: sidebar 
keywords: custom plug-in 
summary: Antes de usar SnapCenter, es necesariol comprender ciertos conceptos básicos vinculados con las operaciones de backup, clonado y restauración que se ejecutan. El usuario interactúa con recursos, grupos de recursos y políticas para diferentes operaciones. 
---
= Cómo se usan los recursos, los grupos de recursos y las políticas para proteger los recursos de los plugins personalizados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter, es necesariol comprender ciertos conceptos básicos vinculados con las operaciones de backup, clonado y restauración que se ejecutan. El usuario interactúa con recursos, grupos de recursos y políticas para diferentes operaciones.

* Los recursos generalmente son bases de datos, sistemas de archivos de Windows o máquinas virtuales que se incluyen en un backup o se clonan con SnapCenter.
* Un grupo de recursos de SnapCenter es una agrupacion de recursos en un host o un clúster.
+
Al realizar una operación con un grupo de recursos, esta se ejecuta en los recursos definidos en el grupo de acuerdo con la programación que se especificó para dicho grupo de recursos.

+
Es posible realizar un backup bajo demanda de un solo recurso o de un grupo de recursos. También puede realizar backups programados para recursos individuales y para grupos de recursos.

* Las políticas especifican la frecuencia de backup, la retención de copias, la replicación, los scripts y otras características de las operaciones de protección de datos.
+
Cuando se crea un grupo de recursos, se seleccionan una o varias políticas para él. Asimismo, puede seleccionar una política al realizar un backup bajo demanda para un recurso individual.



Piense en un grupo de recursos como definir _qué_ desea proteger y cuándo desea protegerlo en términos de día y hora. Piense en una directiva como definir _how_ desea protegerla. Cuando se realiza un backup de todas las bases de datos o todos los sistemas de archivos de un host, por ejemplo, puede crearse un grupo de recursos que incluya todas las bases de datos o todos los sistemas de archivos del host. Luego, se pueden vincular dos políticas al grupo de recursos: Una diaria y una horaria. Cuando crea el grupo de recursos y añade las políticas, puede configurar el grupo de recursos para que ejecute un backup diario basado en archivos y otra programación que ejecute un backup por hora basado en Snapshot.
