---
permalink: protect-scc/create_policies_for_custom_plug_in_resources.html 
sidebar: sidebar 
keywords: create policies, custom plug-in 
summary: Antes de usar SnapCenter para realizar un backup de recursos específicos de un plugin personalizado, debe crear una política de backup para el recurso o el grupo de recursos que incluirá en el backup. 
---
= Crear políticas para recursos de plugins personalizados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar un backup de recursos específicos de un plugin personalizado, debe crear una política de backup para el recurso o el grupo de recursos que incluirá en el backup.

.Antes de empezar
* Debe tener definida una estrategia de backup.
+
Para obtener detalles, consulte la información sobre cómo definir una estrategia de protección de datos para plugins personalizados.

* Debe tener preparada la protección de datos.
+
La preparación de la protección de datos incluye instalar SnapCenter, añadir hosts, crear conexiones con el sistema de almacenamiento y añadir recursos.

* Debe asignar las máquinas virtuales de almacenamiento (SVM) para operaciones de mirroring o almacén.
+
El administrador de SnapCenter debe haberle asignado las instancias de SVM de los volúmenes de origen y de destino en caso de que replique snapshots en un reflejo o almacén.

* Debe añadir manualmente los recursos que desee proteger.


.Acerca de esta tarea
* Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups. De forma adicional, puede definir la configuración de replicación, script y aplicaciones.
* Puede especificar opciones en la política para ahorrar tiempo cuando desee reutilizarla con otro grupo de recursos.
* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
** Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención. Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.




.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Policy type, realice lo siguiente:
+
.. Seleccione el tipo de almacenamiento.
.. En la sección Custom backup settings, proporcione cualquier configuración de backup específica que tenga que pasarse al plugin en formato de clave-valor.
+
Puede pasar varios pares de clave-valor al plugin.



. En la página Snapshot and Replication, realice los siguientes pasos:
+
.. Especifique el tipo de programa seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de backup mientras crea un grupo de recursos. De este modo, puede crear grupos de recursos que compartan la misma política y la misma frecuencia de backup, pero también asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.

.. En la sección Configuración de instantánea, especifique la configuración de retención para el tipo de copia de seguridad y el tipo de programación seleccionado en la página *Tipo de copia de seguridad*:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Mantenga un cierto número de Snapshots
 a| 
Seleccione *Copias para guardar* y, a continuación, especifique el número de instantáneas que desea conservar.

Si la cantidad de snapshots supera el número especificado, las snapshots se eliminan empezando por las más antiguas.


NOTE: Debe establecer el número de retención en 2 o un valor más alto si tiene pensado habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera Snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva Snapshot en el destino.


NOTE: El valor de retención máximo es 1018. Se producirá un error en los backups si la retención se establece en un valor superior a la versión de ONTAP subyacente.



 a| 
Mantenga los Snapshots durante una cierta cantidad de días
 a| 
Seleccione *Retener copias para* y, a continuación, especifique el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de la copia snapshot primaria
 a| 
Seleccione Período de bloqueo de instantáneas y seleccione Días, Meses o Años.

El período de retención de SnapLock debe ser inferior a 100 años.



 a| 
Período de bloqueo de copia de snapshot secundaria
 a| 
Seleccione *Periodo de bloqueo de copia de instantánea secundaria* y seleccione Días, Meses o Años.

|===
.. Seleccione una etiqueta de Snapshot.
+
Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+

NOTE: Si ha seleccionado *Actualizar SnapMirror después de crear una copia Snapshot local*, puede especificar opcionalmente la etiqueta de la directiva secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.



. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:
+

NOTE: Debe seleccionar las opciones de replicación secundarias para que el *Periodo de bloqueo de copia de instantánea secundaria* sea efectivo.

+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
*Actualizar SnapMirror después de crear una copia Snapshot local*
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de backup en otro volumen (replicación de SnapMirror).

Si la relación en ONTAP es del tipo Reflejo y almacén y solo se selecciona esta opción, Snapshot creado en el origen no se transferirá al destino, pero figurará en el destino. Si esta copia Snapshot se selecciona del destino con el fin de realizar una operación de recuperación, aparece un mensaje de error indicando que la ubicación secundaria no está disponible para el backup reflejado/en almacenamiento.

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal.

Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Consulte link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["Consulte los clones y backups relacionados con los recursos de plugins personalizados en la página Topology"].



 a| 
*Actualizar SnapVault después de crear una copia Snapshot local*
 a| 
Seleccione esta opción para realizar una replicación de backup disco a disco (backups de SnapVault).

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Cuando SnapLock se configura solo en el secundario desde ONTAP conocido como Almacén de SnapLock, al hacer clic en el botón *Refrescar* de la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

Para obtener más información sobre el almacén de SnapLock, consulte Confirmar instantáneas en WORM en un almacén
destino

Consulte link:view_custom_plug_in_resource_backups_and_clones_in_the_topology_page.html["Consulte los clones y backups relacionados con los recursos de plugins personalizados en la página Topology"].



 a| 
*Número de reintentos de error*
 a| 
Escriba el número máximo de intentos de replicación que se permitirán antes de que la operación se detenga.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

