---
permalink: protect-scc/define_a_backup_strategy.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 'Definir una estrategia de backup antes de crear las tareas de backup garantiza que se cuente con todos los backups necesarios para restaurar o clonar correctamente los recursos. La estrategia de backup queda determinada principalmente por el acuerdo de nivel de servicio \(SLA\), el objetivo de tiempo de recuperación \(RPO\) y el objetivo de punto de recuperación \(RPO\).' 
---
= Defina una estrategia de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definir una estrategia de backup antes de crear las tareas de backup garantiza que se cuente con todos los backups necesarios para restaurar o clonar correctamente los recursos. La estrategia de backup queda determinada principalmente por el SLA, el RTO y el RPO.

.Acerca de esta tarea
Un acuerdo de nivel de servicio define el nivel de servicio que se espera y aborda varios problemas vinculados con el servicio, como su disponibilidad y rendimiento. El objetivo de tiempo de recuperación es el plazo de recuperación después de una interrupción del servicio. El RPO define la estrategia respecto de la antigüedad de los archivos que se deben recuperar del almacenamiento de backup para reanudar las operaciones regulares después de un fallo. El acuerdo de nivel de servicio, el objetivo de tiempo de recuperación y el RPO ayudan a establecer una estrategia de protección de datos.

.Pasos
. Determinar cuándo se debe realizar el backup de los recursos.
. Decidir cuántas tareas de backup se necesitan.
. Decidir el nombre que se asignará a los backups.
. Decidir si se harán snapshots de los grupos de consistencia y elegir las opciones apropiadas para eliminar las snapshots de los grupos de consistencia.
. Decidir si se desean usar la tecnología NetApp SnapMirror para la replicación o la tecnología NetApp SnapVault para la retención a largo plazo.
. Determinar el período de retención para las copias Snapshot en el sistema de almacenamiento de origen y el destino de SnapMirror.
. Determinar si se desea ejecutar comandos antes o después de la operación de backup y proporcionar un script previo o posterior.

