---
permalink: protect-scc/reference_backup_schedules_of_custom_plug_in_resources.html 
sidebar: sidebar 
keywords:  
summary: El factor más importante para determinar una programación de backup es la tasa de cambio del recurso. Mientras más frecuentes sean los backups de los recursos, menos archivos de registro necesitará SnapCenter para la restauración, lo cual puede acelerar las operaciones de restauración. 
---
= Programaciones de backup de recursos de plugins personalizados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El factor más importante para determinar una programación de backup es la tasa de cambio del recurso. Mientras más frecuentes sean los backups de los recursos, menos archivos de registro necesitará SnapCenter para la restauración, lo cual puede acelerar las operaciones de restauración.

Puede ser recomendable realizar el backup de un recurso muy utilizado una vez por hora, mientras que, en el caso de un recurso de poco uso, es suficiente hacerlo una vez por día. Otros factores que se deben tener en cuenta son la importancia del recurso para la organización, el SLA y el RPO.

El SLA define el nivel de servicio que se espera y aborda varios problemas vinculados con el servicio, como su disponibilidad y rendimiento. El RPO define la estrategia respecto de la antigüedad de los archivos que se deben recuperar del almacenamiento de backup para reanudar las operaciones regulares después de un fallo. El SLA y RPO ayudan a establecer una estrategia de protección de datos.

Las programaciones de backup están compuestas por dos partes:

* Frecuencia de backup
+
La frecuencia de backup (cada cuánto se deben realizar los backups), también denominada tipo de programación para algunos plugins, es parte de una configuración de políticas. Por ejemplo, se puede configurar una frecuencia de backup horaria, diaria, semanal o mensual. Puede acceder a las directivas en la interfaz gráfica de usuario de SnapCenter haciendo clic en *Configuración* > *Directivas*.

* Programaciones de backup
+
Las programaciones de backup (el momento exacto en que se realiza el backup) forman parte de la configuración de un recurso o un grupo de recursos. Por ejemplo, si hay un grupo de recursos con una política configurada para realizar un backup semanal, es posible configurar la programación para que se realice un backup todos los jueves a las 00:10 Para acceder a las programaciones de grupos de recursos en la interfaz gráfica de usuario de SnapCenter, haga clic en *Recursos*, seleccione el complemento adecuado y haga clic en *Ver* > *Grupo de recursos*.


