---
permalink: protect-scc/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux_scc.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Debe asegurarse de que el host cumpla con los requisitos antes de instalar el paquete de plugins de SnapCenter para Linux. 
---
= Requisitos del host para instalar el paquete de plugins de SnapCenter para Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que el host cumpla con los requisitos antes de instalar el paquete de plugins de SnapCenter para Linux.

|===
| Elemento | Requisitos 


 a| 
Sistemas operativos
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
RAM mínima para el plugin de SnapCenter en el host
 a| 
1 GB



 a| 
Espacio de registro e instalación mínimo para el plugin de SnapCenter en el host
 a| 
2 GB


NOTE: Debe asignar el espacio en disco suficiente y supervisar el consumo de almacenamiento en la carpeta de registros. El espacio de registro necesario varía en función de la cantidad de entidades que se han de proteger y la frecuencia de las operaciones de protección de datos. Si no hay espacio en disco suficiente, no se crearán registros de las operaciones ejecutadas recientemente.



 a| 
Paquetes de software obligatorios
 a| 
Tipos de Java 1.8 (64 bits)Oracle Java o OpenJDK

Si ha actualizado JAVA a la versión más reciente, debe asegurarse de que la opción JAVA_HOME ubicada en /var/opt/snapcenter/spl/etc/spl.properties esté configurada en la versión DE JAVA correcta y en la ruta de acceso correcta.

|===
Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=112392;&solution=1259&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"]
