---
permalink: protect-scc/reference_custom_plugin_in_snapcenter.html 
sidebar: sidebar 
keywords: Custom plug-in 
summary: El plugin personalizado creado se puede instalar en el host mediante SnapCenter Server para permitir la protección de datos de la aplicación. 
---
= Plugin personalizado en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Plugin personalizado en SnapCenter

El complemento personalizado creado con Java, PERL o estilo NATIVO puede instalarse en el host utilizando SnapCenter Server para permitir la protección de datos de su aplicación. Debe haber exportado el plugin para instalarlo en el host SnapCenter mediante el procedimiento proporcionado en este tutorial.



=== Crear un archivo de descripción del plugin

Para cada plugin creado, debe tener un archivo de descripción. El archivo de descripción describe los detalles del plugin. El nombre del archivo debe ser Plugin_descriptor.xml.



==== Usar atributos del archivo descriptor del plugin y su importancia

|===
| Atributo | Descripción 


 a| 
Nombre
 a| 
Nombre del plugin. Se permiten caracteres alfanuméricos. Por ejemplo, DB2, MYSQL, MongoDB

Para los plugins creados con un estilo NATIVO, asegúrese de no proporcionar la extensión del archivo. Por ejemplo, si el nombre del plugin es MongoDB.sh, especifique el nombre como MongoDB.



 a| 
Versión
 a| 
Versión de plugin. Puede incluir tanto la versión principal como la secundaria. Por ejemplo, 1.0, 1.1, 2.0, 2.1



 a| 
DisplayName
 a| 
El nombre del plugin que se mostrará en SnapCenter Server. Si se escriben varias versiones del mismo complemento, asegúrese de que el nombre para mostrar es el mismo en todas las versiones.



 a| 
PluginType
 a| 
Idioma utilizado para crear el plug-in. Los valores admitidos son Perl, Java y Native. El tipo de complemento nativo incluye scripts de shell de Unix/Linux, scripts de Windows, Python o cualquier otro lenguaje de scripting.



 a| 
OSNAME
 a| 
El nombre del sistema operativo del host donde se ha instalado el plugin. Los valores válidos son Windows y Linux. Es posible que un único complemento esté disponible para su puesta en marcha en varios tipos de sistemas operativos, como el complemento DE tipo PERL.



 a| 
OSVersion
 a| 
La versión del sistema operativo del host donde se instaló el plugin.



 a| 
ResourceName
 a| 
Nombre del tipo de recurso que admite el plugin. Por ejemplo, base de datos, instancia, colecciones.



 a| 
Padre
 a| 
En caso de que el ResourceName dependa jerárquicamente de otro tipo de recurso y, a continuación, Parent determina el atributo resourcetype primario.

Por ejemplo, el complemento DB2, ResourceName “Database” tiene una “instancia” principal.



 a| 
RequireFileSystemPlugin
 a| 
Sí o no Determina si la pestaña Recovery se muestra en el asistente Restore.



 a| 
ResourceRequiresAuthentication
 a| 
Sí o no Determina si los recursos, que se detectan automáticamente o no se detectan automáticamente necesitan credenciales para realizar las operaciones de protección de datos después de detectar el almacenamiento.



 a| 
RequireFileSystemClone
 a| 
Sí o no Determina si el plugin requiere la integración del plugin del sistema de archivos para el flujo de trabajo de clonado.

|===
A continuación, se muestra un ejemplo del archivo Plugin_descriptor.xml para el plugin personalizado DB2:

....
<Plugin>
<SMSServer></SMSServer>
<Name>DB2</Name>
<Version>1.0</Version>
<PluginType>Perl</PluginType>
<DisplayName>Custom DB2 Plugin</DisplayName>
<SupportedOS>
<OS>
<OSName>windows</OSName>
<OSVersion>2012</OSVersion>
</OS>
<OS>
<OSName>Linux</OSName>
<OSVersion>7</OSVersion>
</OS>
</SupportedOS>
<ResourceTypes>
<ResourceType>
<ResourceName>Database</ResourceName>
<Parent>Instance</Parent>
</ResourceType>
<ResourceType>
<ResourceName>Instance</ResourceName>
</ResourceType>
</ResourceTypes>
<RequireFileSystemPlugin>no</RequireFileSystemPlugin>
<ResourceRequiresAuthentication>yes</ResourceRequiresAuthentication>
<SupportsApplicationRecovery>yes</SupportsApplicationRecovery>
</Plugin>
....


=== Creación de un archivo ZIP

Después de desarrollar un plugin y crear un archivo descriptor, es necesario añadir los archivos del plugin y el archivo Plugin_descriptor.xml a una carpeta y zip.

Debe tener en cuenta lo siguiente antes de crear un archivo ZIP:

* El nombre de script debe ser el mismo que el del plugin.
* Para el plugin PERL, la carpeta ZIP debe contener una carpeta con el archivo de script y el archivo descriptor debe estar fuera de esta carpeta. El nombre de la carpeta debe ser el mismo que el del plugin.
* Para los plugins distintos al plugin PERL, la carpeta ZIP debe contener el descriptor y los archivos de script.
* La versión de SO debe ser un número.


Ejemplos:

* DB2 plug-in: Agregue el archivo DB2.pm y Plugin_descriptor.xml a “DB2.zip”.
* Plug-in desarrollado con Java: Añada archivos JAR, archivos JAR dependientes y archivo Plugin_descriptor.xml a una carpeta y zip.




=== Cargando el archivo ZIP del plugin

Es necesario cargar el archivo ZIP del plugin en el servidor de SnapCenter para que el plugin se pueda implementar en el host deseado.

Puede cargar el plugin mediante la interfaz de usuario o cmdlets de.

*UI:*

* Cargue el archivo ZIP del plug-in como parte del asistente de flujo de trabajo *Add* o *Modify Host*
* Haga clic en *“Seleccionar para cargar el complemento personalizado”*


*PowerShell:*

* Cmdlet Upload-SmPluginPackage
+
Por ejemplo, PS> Upload-SmPluginPackage -AbsolutePath c:\DB2_1.zip

+
Para obtener información detallada sobre los cmdlets de PowerShell, use la ayuda de cmdlets de SnapCenter o consulte la información de referencia sobre cmdlets.



https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["Guía de referencia de cmdlets de SnapCenter Software"^].



=== Implementación de los plugins personalizados

El complemento personalizado cargado ahora está disponible para su implementación en el host deseado como parte del flujo de trabajo *Add* y *Modify Host*. Es posible cargar varias versiones de plugins en SnapCenter Server y seleccionar la versión deseada para implementarla en un host específico.

Para obtener más información sobre cómo cargar el plugin, consulte, link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html["Añada hosts e instale paquetes de plugins en hosts remotos"]
