---
permalink: protect-scc/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html 
sidebar: sidebar 
keywords: add hosts 
summary: Es necesario usar la página SnapCenterAdd Host para añadir hosts y, a continuación, instalar los paquetes de plugins. Los plugins se instalan automáticamente en hosts remotos. Puede añadir un host e instalar los paquetes de los plugins para un host individual o para un clúster. 
---
= Añada hosts e instale paquetes de plugins en hosts remotos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario usar la página SnapCenterAdd Host para añadir hosts y, a continuación, instalar los paquetes de plugins. Los plugins se instalan automáticamente en hosts remotos. Puede añadir un host e instalar los paquetes de los plugins para un host individual o para un clúster.

.Antes de empezar
* Debe ser un usuario al que se ha asignado una función que tenga permisos de instalación y desinstalación de plugins, como el rol de administrador de SnapCenter.
* Debe asegurarse de que el servicio de cola de mensajes está en ejecución.
* Si está utilizando la cuenta de servicio gestionado en grupo (GMSA), debe configurar GMSA con privilegios administrativos.
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Configurar la cuenta de servicio administrado de grupo en Windows Server 2012 o posterior para aplicaciones personalizadas"]



.Acerca de esta tarea
No es posible añadir un servidor SnapCenter como host de plugins a otro servidor SnapCenter.

Si instala plugins en un clúster (WSFC), los plugins se instalan en todos los nodos del clúster.

.Pasos
. En el panel de navegación izquierdo, seleccione *hosts*.
. Compruebe que la ficha *Managed hosts* está seleccionada en la parte superior.
. Seleccione *Agregar*.
. En la página hosts, realice las siguientes acciones:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Tipo de host
 a| 
Seleccione el tipo de host:

** Windows
** Linux



NOTE: Los plugins personalizados se pueden utilizar tanto en entornos de Windows como de Linux.



 a| 
Nombre de host
 a| 
Introduzca el nombre de dominio completamente cualificado (FQDN) o la dirección IP del host.

SnapCenter depende de una configuración adecuada del DNS. Por lo tanto, lo más recomendable es introducir el FQDN.

En los entornos de Windows, la dirección IP es compatible con los hosts de dominio que no son de confianza solo si se resuelve en el FQDN.

Puede introducir las direcciones IP o el FQDN de un host independiente.

Si va a añadir un host mediante SnapCenter y el host forma parte de un subdominio, debe proporcionar el FQDN.



 a| 
Credenciales
 a| 
Seleccione el nombre de la credencial que ha creado o cree nuevas credenciales.

Las credenciales deben tener derechos de administración en el host remoto. Para obtener más detalles, consulte la información acerca de crear credenciales.

Puede ver los detalles sobre las credenciales colocando el cursor sobre el nombre de las credenciales que ha especificado.


NOTE: El modo de autenticación de las credenciales se determina por el tipo de host que especifique en el asistente Add host.

|===
. En la sección *Seleccione Plug-ins to Install*, seleccione los plugins que desee instalar.
. (Opcional) Seleccione *Más opciones*.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Puerto
 a| 
Conserve el número de puerto predeterminado o especifique el número de puerto.

El número de puerto predeterminado es 8145. Si el servidor SnapCenter se instaló en un puerto personalizado, ese número de puerto se mostrará como el puerto predeterminado.


NOTE: Si ha instalado plugins manualmente y ha especificado un puerto personalizado, debe especificar el mismo puerto. De lo contrario, la operación dará error.



 a| 
Ruta de instalación
 a| 
Los plugins personalizados se pueden instalar en un sistema Windows o Linux.

** En el caso del paquete de plugins de SnapCenter para Windows, la ruta predeterminada es C:\Program Files\NetApp\SnapCenter.
+
Opcionalmente, puede personalizar la ruta.

** Para el paquete de plugins de SnapCenter para Linux, la ruta predeterminada es `/opt/NetApp/snapcenter`.
+
Opcionalmente, puede personalizar la ruta.

** Para los plugins personalizados de SnapCenter:
+
... En la sección Custom Plug-ins, seleccione *Browse* y seleccione la carpeta del plugin personalizado comprimida.
+
La carpeta comprimida contiene el código del plugin y el archivo .xml del descriptor.

+
Para el plugin de almacenamiento, desplácese a. `_C:\ProgramData\NetApp\SnapCenter\Package Repository_` y seleccione `Storage.zip` carpeta.

... Selecciona *Cargar*.
+
El archivo .xml del descriptor en la carpeta del plugin personalizado comprimida se valida antes de cargar el paquete.

+
Aparece la lista de los plugins personalizados que se cargan en el servidor de SnapCenter.

+
Si desea gestionar aplicaciones de MySQL o DB2, puede utilizar los plugins personalizados de MySQL y DB2 proporcionados por NetApp. Los plugins personalizados de MySQL y DB2 están disponibles en la https://automationstore.netapp.com/home.shtml["Automation Store de NetApp"]







 a| 
Omitir comprobaciones previas a la instalación
 a| 
Seleccione esta casilla de comprobación si ya ha instalado los plugins manualmente y no desea validar si el host cumple con los requisitos para la instalación del plugin.



 a| 
Utilice Group Managed Service Account (GMSA) para ejecutar los servicios de plug-in
 a| 
En el caso de host de Windows, seleccione esta casilla de comprobación si desea utilizar una cuenta de servicio gestionado de grupo (GMSA) para ejecutar los servicios de plugin.


IMPORTANT: Proporcione el nombre de GMSA con el siguiente formato: Nombre_de_dominio\accountName$.


NOTE: GMSA se utilizará como cuenta de servicio de inicio de sesión solo en el complemento SnapCenter para el servicio de Windows.

|===
. Seleccione *Enviar*.
+
Si no ha seleccionado la casilla de comprobación *Skip prechecks, el host se valida para comprobar si cumple con los requisitos para la instalación del plugin. El espacio en disco, RAM, versión de PowerShell, versión de .NET, ubicación (para plugins de Windows) y versión de Java (para plugins de Linux) se validan frente a los requisitos mínimos. Si no se satisfacen los requisitos mínimos, se muestran los mensajes de error o advertencia correspondientes.

+
Si el error está relacionado con el espacio en disco o RAM, es posible actualizar el archivo web.config ubicado en C:\Program Files\NetApp\SnapCenter WebApp para modificar los valores predeterminados. Si el error está relacionado con otros parámetros, primero debe solucionar el problema.

+

NOTE: En una configuración de alta disponibilidad, si actualiza el archivo web.config, debe actualizar el archivo en ambos nodos.

. Si el tipo de host es Linux, verifique la huella dactilar y, a continuación, seleccione *Confirmar y Enviar*.
+

NOTE: La verificación de huellas digitales es obligatoria aunque se haya añadido anteriormente el mismo host a SnapCenter y se haya confirmado la huella.

. Supervise el progreso de la instalación.
+
Los archivos de registro específicos de la instalación se encuentran en `/custom_location/snapcenter/` registros.


