---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords: REST API, disaster recovery, DR 
summary: La funcionalidad de recuperación ante desastres de SnapCenter usa API DE REST para hacer backups de SnapCenter Server. 
---
= API DE REST de recuperación ante desastres (DR)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]


La funcionalidad de recuperación ante desastres de SnapCenter usa API REST para hacer backups de SnapCenter Server. Realice los pasos siguientes antes de usar las API DE REST de DR.

* Pasos*

. Cree un nuevo backup de recuperación ante desastres de servidor, que restaura un servidor SnapCenter desde un backup de recuperación ante desastres de servidor específico mediante la API DE REST de backup de recuperación ante desastres: `/4.5/disasterrecovery/server/backup`
. Traer la máquina del servidor secundario, pero antes de instalar el servidor SnapCenter en el servidor secundario debe completar los requisitos previos.
+
** El nombre de host/FQDN de host del servidor alternativo debe ser el mismo que el nombre de host del servidor primario, pero la dirección IP puede ser diferente.
** La versión del servidor secundario debe ser la misma que la del servidor primario.
** El SnapCenter secundario debe instalarse en la misma ubicación y en el mismo puerto que el primario.


. Antes de activar la operación de restauración de recuperación ante desastres de servidor, debe obtener la ruta de destino o la ruta en la que se almacenan los backups de DR después del desastre.
+
** Asegúrese de que los archivos de backup de recuperación ante desastres se copien al nuevo servidor SnapCenter mediante el comando siguiente:
`xcopy <Ssource_Path> \\<Destination_Server_IP>\<Folder_Path> /O /X /E /H /K {ex : xcopy C:\DRBackup \\10.225.81.114\c$\DRBackup /O /X /E /H /K}`


. Instalar el servidor SnapCenter en la máquina secundaria.
+
** Al realizar la operación de restauración de recuperación ante desastres, debe asegurarse de que no exista ningún trabajo en ejecución relacionado con el servidor SnapCenter.


. Instale el servidor SnapCenter secundario en la misma ubicación y en el mismo puerto que el servidor primario.
+
** Realizar la operación de restauración de recuperación ante desastres del servidor mediante la API de restauración de recuperación ante desastres:  `/4.5/disasterrecovery/server/restore`
+
Si el plugin no puede resolver el nombre de host del servidor, inicie sesión en cada host del plugin y añada la entrada etc/host para la nueva IP en el formato <New IP> SC_Server_Name. Por ejemplo: `10.225.81.35 SCServer1`

+
Las entradas del servidor etc/host no se restaurarán. Puede restaurarlo manualmente desde la carpeta de backup de recuperación ante desastres.






NOTE: Para una configuración de F5, la operación de restauración se realiza como independiente, debe ejecutar un conjunto de comandos para volver a crear la F5. Consulte el enlace: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Migrate_SnapCenter_migrate_to_another_Server["Cómo migrar SnapCenter a otro servidor"^]


NOTE: Después de la restauración de recuperación ante desastres, se añadirá el host, pero debe instalar el plugin manualmente.


NOTE: La programación de backup del repositorio se restaurará únicamente si instala el plugin de SnapCenter para Windows y asocia LUN de NetApp a la máquina servidor.


NOTE: Si las DLL están dañadas, puede intentar reparar el servidor SnapCenter o corregir la instalación defectuosa.


NOTE: Si los archivos nsm o de configuración están dañados, puede desinstalar y volver a instalar el servidor SnapCenter con la misma versión.


NOTE: Si la máquina virtual está dañada, abra otra máquina virtual o una máquina con el mismo nombre e instale el servidor SnapCenter con la misma versión.



== API DE REST compatible con la recuperación ante desastres de SnapCenter Server

Con las API DE REST, es posible realizar las siguientes operaciones en la página de API de REST de Swagger. Para obtener información sobre cómo acceder a la página de Swagger, consulte link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Cómo acceder a las API de REST con la página web de la API swagger"].

.Antes de empezar
* Debe iniciar sesión como usuario administrador de SnapCenter.
* El servidor SnapCenter debe estar activo y en funcionamiento para ejecutar la API de restauración de recuperación ante desastres.
* Si las DLL están dañadas, repare la instalación del servidor de SnapCenter.
* Si NSM está dañado o los archivos de configuración están dañados, desinstale y vuelva a instalar el servidor SnapCenter con la misma versión.
* Si la máquina virtual está dañada, abra otra máquina virtual con el mismo nombre e instale el servidor SnapCenter con la misma versión.


.Acerca de esta tarea
SnapCenter Server DR es compatible con todos los plugins.

|===
| Descripción | API REST | Método HTTP 


 a| 
Recuperar los backups de recuperación ante desastres de servidores de SnapCenter existentes

Debe proporcionar la ruta de destino donde estén almacenados los backups de recuperación ante desastres.
 a| 
`/4.5/disasterrecovery/server/backup?targetpath={path}`
 a| 
OBTENGA



 a| 
Crear una nueva copia de seguridad de recuperación ante desastres del servidor.
 a| 
`/4.5/disasterrecovery/server/backup`
 a| 
PUBLICAR



 a| 
Restaura un servidor SnapCenter desde un backup DR de servidor específico.
 a| 
`/4.5/disasterrecovery/server/restore`
 a| 
PUBLICAR



 a| 
Elimine el backup de recuperación ante desastres del servidor según el nombre de la copia de seguridad.
 a| 
``/4.5/disasterrecovery/server/backup``
 a| 
ELIMINAR



 a| 
Habilite o deshabilite la recuperación ante desastres de almacenamiento
 a| 
`/4.5/disasterrecovery/storage`
 a| 
PUBLICAR

|===
.Información relacionada
Consulte link:https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API de recuperación ante desastres"^] vídeo.
