---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para mostrar las API DE REST de SnapCenter Server, y también para emitir manualmente una llamada API. Es posible usar la API DE REST para ayudar a gestionar SnapCenter Server o para realizar operaciones de protección de datos. 
---
= Cómo acceder a las API de REST a través de la página web de API de Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para mostrar las API DE REST de SnapCenter Server, y también para emitir manualmente una llamada API. Es posible usar la API DE REST para ayudar a gestionar SnapCenter Server o para realizar operaciones de protección de datos.

Debe conocer la dirección IP o el nombre de dominio de gestión de la instancia de SnapCenter Server donde desea ejecutar las API de REST.

No se necesitan permisos especiales para ejecutar el cliente API de REST. Cualquier usuario puede acceder a la página web de Swagger. Los permisos respectivos en los objetos a los que se accede a través de la API DE REST se basan en el usuario que genera el token para iniciar sesión en la API DE REST.

.Pasos
. Desde un explorador, introduzca la URL para acceder a la página web de Swagger con el formato _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/swagger/_.
+

NOTE: Asegúrese de que la dirección URL de la API DE REST no tenga los caracteres siguientes: +, ., % y &.

. En el campo *Explore* de Swagger, si la documentación de API de Swagger no se muestra automáticamente, escriba: _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/SnapCenter.yaml_
. Haga clic en *explorar*.
+
Se muestra una lista de los tipos de recursos o categorías de la API.

. Haga clic en un tipo de recurso de la API para mostrar las API en ese tipo de recurso.


Si se produce un comportamiento inesperado al ejecutar las API DE REST de SnapCenter, puede usar los archivos de registro para identificar la causa del problema y resolverlo. Puede descargar los archivos de registro desde la interfaz de usuario de SnapCenter haciendo clic en *Monitor* > *Logs* > *Download*.
