= 
:allow-uri-read: 


Puede utilizar el cmdlet Remove-SmBackup para borrar el número de backups de backups secundarios que no tienen Snapshot. Se recomienda utilizar este cmdlet cuando el total de las Snapshot que se muestran en la topología Manage Copies no corresponde al valor de retención de Snapshot del almacenamiento secundario.

Debe haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.

La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].

.Pasos
. Inicie una sesión de conexión con el servidor de SnapCenter para el usuario especificado mediante el cmdlet de Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Borre el número de backups secundarios con el parámetro -CleanupSecondaryBackups.
+
Este ejemplo borra el número de backups para backups secundarios sin snapshots:

+
[listing]
----
Remove-SmBackup -CleanupSecondaryBackups
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

