= 
:allow-uri-read: 


Puede utilizar el cmdlet Remove-SmBackup para borrar el número de backups de backups secundarios que no tienen copias de Snapshot. Puede ser conveniente usar este cmdlet cuando las copias de Snapshot totales que se muestran en la topología Manage Copies no coinciden con la configuración de retención de copias de Snapshot de almacenamiento secundario.

Debe haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.

La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2886895["Guía de referencia de cmdlets de SnapCenter Software"^].

.Pasos
. Inicie una sesión de conexión con el servidor de SnapCenter para el usuario especificado mediante el cmdlet de Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Borre el número de backups secundarios con el parámetro -CleanupSecondaryBackups.
+
En este ejemplo, se borra el número de backups secundarios sin copias de Snapshot:

+
[listing]
----
Remove-SmBackup -CleanupSecondaryBackups
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

