---
permalink: protect-azure/add-hosts-install-plugin-for-sql.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SQL 
summary: Añada hosts y, a continuación, instale los paquetes de plugins. 
---
= Añadir hosts e instalar el plugin de SnapCenter para base de datos de SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter admite la protección de datos de instancias de SQL en recursos compartidos de SMB en Azure NetApp Files. Se admiten las configuraciones de grupos de disponibilidad (AG) independientes.

Debe usar la página SnapCenter Add Host para añadir hosts y, a continuación, instalar el paquete de los plugins. Los plugins se instalan automáticamente en hosts remotos.

.Antes de empezar
* Debe ser un usuario al que se ha asignado una función que tenga permisos de instalación y desinstalación de plugins, como el rol de administrador de SnapCenter.
* Al instalar un plugin en un host de Windows, si especifica una credencial que no está incorporada o si el usuario pertenece a un usuario de grupo de trabajo local, debe deshabilitar UAC en el host.


.Pasos
. En el panel de navegación izquierdo, seleccione *hosts*.
. Compruebe que la ficha *Managed hosts* está seleccionada en la parte superior.
. Seleccione *Agregar*.
. En la página hosts, haga lo siguiente:
+
.. En el campo Tipo de host, seleccione el tipo de host.
.. En el campo Host name, introduzca el nombre de dominio completamente cualificado (FQDN) o la dirección IP del host.
.. En el campo Credenciales, introduzca la credencial que ha creado.


. En la sección *Seleccione Plug-ins to Install*, seleccione los plugins que desee instalar.
. (Opcional) Haga clic en *Más opciones* y especifique los detalles.
. Seleccione *Enviar*.
. Seleccione *Configurar directorio de registro* y en la página Configurar directorio de registro de host, introduzca la ruta SMB del directorio de registro de host y haga clic en *Guardar*.
. Haga clic en *Enviar* y supervise el progreso de la instalación.

