---
permalink: protect-azure/backup-sap-hana-resource-groups.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database, back up, resource groups 
summary: Un grupo de recursos es una agrupacion de recursos en un host. Se realiza una operación de backup del grupo de recursos con todos los recursos definidos en el grupo. 
---
= Realice un backup de grupos de recursos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un grupo de recursos es una agrupacion de recursos en un host. Se realiza una operación de backup del grupo de recursos con todos los recursos definidos en el grupo.

.Pasos
. En el panel de navegación izquierdo, seleccione *Recursos* y, a continuación, seleccione el plugin apropiado de la lista.
. En la página Resources, seleccione *Resource Group* en la lista *View*.
. En la página Resource Groups, seleccione el grupo de recursos del que desea realizar un backup y, a continuación, seleccione *Back up Now*.
. En la página Backup, realice los siguientes pasos:
+
.. Si hay varias políticas asociadas con el grupo de recursos, en la lista desplegable *Policy*, seleccione la política que desea usar para la copia de seguridad.
+
Si la política seleccionada para el backup bajo demanda está asociada a una programación de backup, los backups bajo demanda se retendrán en función de la configuración de retención especificada para el tipo de programación.

.. Seleccione *copia de seguridad*.


. Supervise el progreso de la operación seleccionando *Monitor* > *Trabajos*.

