---
permalink: protect-azure/create-backup-policies-sap-hana.html 
sidebar: sidebar 
keywords: create policies, SAP HANA, backup policies 
summary: Cree una política de backup para el recurso o grupo de recursos que desea incluir en un backup. 
---
= Crear políticas de backup para bases de datos SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar un backup de los recursos de la base de datos SAP HANA, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y una descripción.
. En la página Policy type, realice los siguientes pasos:
+
.. Seleccione *Azure NetApp Files* como tipo de almacenamiento.
.. Seleccione *Basado en archivos* si desea realizar una comprobación de integridad de la base de datos.
.. Seleccione *Basado en Snapshot* si desea crear una copia de seguridad utilizando la tecnología Snapshot.


. En la página Snapshot and backup, realice los siguientes pasos:
+
.. Seleccione la frecuencia del backup programado.
.. Especifique la configuración de retención.
.. Si desea habilitar la copia de seguridad de Azure NetApp Files, seleccione *Habilitar copia de seguridad* y especifique la configuración de retención.


. Revise el resumen y haga clic en *Finalizar*.

