---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Cree la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp. 
---
= Cree las credenciales de Azure en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp.

Antes de crear la credencial de Azure, asegúrese de haber creado el principal de servicio en Azure. Se necesitarán el ID de inquilino, el ID de cliente y la clave secreta asociados con el principal de servicio para crear la credencial de Azure.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
. En la página Credential, especifique la siguiente información necesaria para crear la credencial.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Escriba un nombre para la credencial.



 a| 
Modo de autenticación
 a| 
Seleccione *Azure Credential* de la lista desplegable.



 a| 
ID de inquilino
 a| 
Introduzca el ID de inquilino.



 a| 
ID del cliente
 a| 
Introduzca el ID de cliente.



 a| 
Clave secreta de cliente
 a| 
Introduzca la clave secreta del cliente.

|===
. Haga clic en *Aceptar*.

