---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Cree la credencial para añadir el host del plugin. 
---
= Cree la credencial para añadir el host del plugin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter.

Debe crear credenciales para instalar los plugins de SnapCenter, y credenciales adicionales para realizar operaciones de protección de datos.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
. En la página Credential, especifique la siguiente información necesaria para crear la credencial.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Escriba un nombre para la credencial.



 a| 
Modo de autenticación
 a| 
Seleccione el modo de autenticación de la lista desplegable.



 a| 
Tipo de autenticación
 a| 
Seleccione *Basado en contraseña* o *Basado en clave SSH* (solo para host Linux).



 a| 
Nombre de usuario
 a| 
Especifique el nombre de usuario.



 a| 
Contraseña
 a| 
Si seleccionó autenticación basada en contraseña, especifique la contraseña.



 a| 
Clave privada SSH
 a| 
Si seleccionó la autenticación basada en clave SSH, especifique la clave privada.



 a| 
Use privilegios sudo
 a| 
Seleccione la casilla de comprobación Use sudo privileges si va a crear credenciales para usuarios que no son raíz.


NOTE: Esto solo se aplica a usuarios Linux.

|===
. Haga clic en *Aceptar*.

