---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Cree la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp. 
---
= Cree las credenciales de Azure en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear la credencial de Azure en SnapCenter para acceder a la cuenta de Azure NetApp.

.Antes de empezar
* Asegúrese de haber creado el principal de servicio en Azure.
* Asegúrese de que tiene disponibles el ID de inquilino, el ID de cliente y la clave secreta asociada al principal de servicio.
+
** El ID de inquilino se puede encontrar en Azure Portal en la página Visión General de Entra ID.
** El ID de cliente también se conoce como ID de aplicación para Enterprise App/Service Principal. Esto se puede encontrar en el portal de Azure en la página Visión general de la aplicación empresarial que ha creado para actuar como principal de servicios para SnapCenter.
** La clave secreta de cliente también se conoce como valor secreto. Puede crear este secreto de cliente en Azure Portal navegando a *Registros de aplicaciones* bajo Entra ID. Después de seleccionar la aplicación empresarial que creó, navegue a *Certificados y secretos* y luego a *Nuevo secreto de cliente*.
+

NOTE: Solo se puede acceder al valor secreto cuando se crea. No podrá acceder a él más tarde.

** Se deben otorgar permisos al principal de servicio. La función de Contributor permitirá al director de servicio realizar las acciones necesarias en Azure. Esto se puede otorgar desde la página Control de Acceso (IAM) de la página Suscripción.




.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
. En la página Credential, especifique la siguiente información necesaria para crear la credencial.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Escriba un nombre para la credencial.



 a| 
Modo de autenticación
 a| 
Seleccione *Azure Credential* de la lista desplegable.



 a| 
ID de inquilino
 a| 
Introduzca el ID de inquilino.



 a| 
ID del cliente
 a| 
Introduzca el ID de cliente.



 a| 
Clave secreta de cliente
 a| 
Introduzca la clave secreta del cliente.

|===
. Haga clic en *Aceptar*.

