---
permalink: protect-azure/protect-applications-azure-netapp-files.html 
sidebar: sidebar 
keywords: azure netapp files, ANF, back up, restore, clone, ANF backup, Azure Blob storage 
summary: Es posible realizar backups, restaurar y clonar aplicaciones que se ejecutan en Azure NetApp Files. 
---
= Proteja las aplicaciones que se ejecutan en Azure NetApp Files
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter admite la protección de aplicaciones como Oracle, SQL y SAP HANA que residen en Azure NetApp Files. A partir de la versión 6.0.1, SnapCenter admite la función de backup de Azure NetApp Files que amplía las funcionalidades de protección de datos de Azure NetApp Files al proporcionar una solución de backup totalmente gestionada para la recuperación, el archivado y el cumplimiento de normativas a largo plazo.

Azure NetApp Files es una solución de almacenamiento premium que puede ser costosa para la retención de backup a largo plazo. Para optimizar los costes, puede mover los backups desde el almacenamiento de Azure NetApp Files a un almacén de objetos de Azure. A partir de SnapCenter 6,0.1, puede realizar backups y clonar aplicaciones que residen en Azure NetApp Files en Azure Blob Storage (almacén de objetos). Puede conservar dos copias de sus datos, copias snapshot de volúmenes en almacenamiento de Azure NetApp Files para recuperación a corto plazo y otra copia en Azure Blob Storage para recuperación a largo plazo.

Cuando se habilita una política con el backup de Azure NetApp Files y se asocia con un recurso, SnapCenter gestiona la creación de copias Snapshot de volúmenes y el backup de ellas en Azure Blob Storage. SnapCenter crea el almacén de backup y habilita el backup del volumen. Si habilitó el backup para el volumen, SnapCenter utiliza el almacén existente.



== Limitaciones

* No se admiten las funcionalidades de almacenamiento de objetos para los sistemas de almacenamiento FAS, ASA o AFF ONTAP y Amazon FSx para NetApp ONTAP.
* Los flujos de trabajo de montaje y catálogo de Oracle y SAP HANA no son compatibles con los backups de almacenamiento de objetos, pero sí con las copias Snapshot.
* No se admiten los clones de Oracle PDB para los backups de almacenamiento de objetos, pero sí para las Snapshot.
* No se admite la verificación de backups en el almacenamiento de objetos, la compatibilidad con API DE REST, la gestión del ciclo de vida de clones desde el almacenamiento de objetos e las funciones de generación de informes para los backups de almacenamiento de objetos.
* No se admite la restauración desde backups en Azure Blob Storage a Azure NetApp Files. También puede usar la opción clone.
* No se admite la división de clones.

