---
permalink: tech-refresh/task_tech_refresh_storage_system.html 
sidebar: sidebar 
keywords: tech refresh, storage system, 
summary: Realizar una actualización tecnológica del sistema de almacenamiento moviendo los datos del almacenamiento antiguo al nuevo, montando el nuevo almacenamiento en los hosts respectivos y, a continuación, trayendo las bases de datos. 
---
= Actualización tecnológica del sistema de almacenamiento
:allow-uri-read: 


[role="lead"]
Cuando se actualiza el almacenamiento tecnológico, los datos se migran al nuevo almacenamiento y los hosts de aplicaciones se montan con nuevo almacenamiento. El flujo de trabajo de backup de SnapCenter identifica el nuevo almacenamiento y crea la instantánea si el nuevo almacenamiento se registra en SnapCenter.

Es posible realizar la restauración, el montaje y la clonación en los nuevos backups creados después de la actualización del almacenamiento. Sin embargo, estas operaciones fallarán cuando se realicen en los backups que se crearon antes de la actualización del almacenamiento, ya que los backups tienen los detalles del almacenamiento antiguo. Debe ejecutar la API o el cmdlet de actualización tecnológica del almacenamiento para actualizar los backups antiguos en SnapCenter con los nuevos detalles del almacenamiento.

La actualización tecnológica es compatible con los siguientes complementos de SnapCenter:

* Plugin de SnapCenter para Microsoft SQL Server
* Plugin de SnapCenter para Windows
* Plugin de SnapCenter para base de datos de Oracle
* Plugin de SnapCenter para base de datos SAP HANA
* Plugin de SnapCenter para Microsoft Exchange Server


Los casos de uso admitidos son:

* Actualización del almacenamiento principal
+
La actualización tecnológica de almacenamiento es compatible para sustituir el almacenamiento principal por nuevo almacenamiento. No puede convertir el almacenamiento secundario existente en un almacenamiento primario.

* Actualización del almacenamiento secundario


Los demás escenarios admitidos son:

* Cambio de nombre de SVM
* Cambio del nombre del volumen




== Actualice las copias de seguridad del almacenamiento primario

Cuando se actualiza la tecnología del almacenamiento, es conveniente ejecutar la API o el cmdlet de actualización técnica del almacenamiento para actualizar los backups antiguos en SnapCenter con los nuevos detalles del almacenamiento.

.Antes de empezar
Como este flujo de trabajo modifica los datos del repositorio de SnapCenter, se recomienda realizar una copia de seguridad del repositorio de SnapCenter. En caso de cualquier problema con los datos, el repositorio de SnapCenter puede revertirse a estado antiguo mediante el backup.

Para obtener más información, consulte https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Realice un backup del repositorio de SnapCenter"].

.Pasos
. Migrar los datos de un almacenamiento antiguo al nuevo.
+
Para obtener más información sobre cómo migrar, consulte:

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["Cómo migrar los datos a un nuevo almacenamiento"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["¿Cómo puedo copiar un volumen y conservar todas las copias Snapshot?"]


. Ponga el host en modo de mantenimiento.
. Montar el nuevo almacenamiento en los respectivos hosts y resaltar las bases de datos.
+
El nuevo almacenamiento debe conectarse al host de la misma manera que antes. Por ejemplo, si estaba conectado como SAN, necesita conectarse como SAN.

+
El nuevo almacenamiento debe montarse en la misma unidad o ruta que el almacenamiento anterior.

. Verifique que todos los recursos estén activos y en ejecución.
. Añada el nuevo almacenamiento en SnapCenter.
+
Compruebe que tiene un nombre de SVM único en los clústeres de SnapCenter. Si utiliza el mismo nombre de SVM en el nuevo almacenamiento y si todos los volúmenes de la SVM pueden migrarse antes de ejecutar la actualización de almacenamiento, después, se recomienda eliminar la SVM en el clúster antiguo y volver a detectar el clúster antiguo en SnapCenter que eliminará la SVM de la caché.

. Ponga el host en modo de producción.
. En SnapCenter, cree un backup de los recursos cuyo almacenamiento se migra. Es necesario un nuevo backup para que SnapCenter identifique el último espacio de almacenamiento necesario para actualizar los metadatos de los backups antiguos existentes.
+

NOTE: Siempre que se conecte un nuevo LUN al host, tendrá un nuevo número de serie. Durante el descubrimiento del sistema de archivos de Windows, SnapCenter tratará cada número de serie único como nuevo recurso. Durante la actualización de la tecnología de almacenamiento cuando el LUN de un nuevo almacenamiento se conecta al host con la misma letra o ruta de unidad, la detección del sistema de archivos de Windows en SnapCenter marcará el recurso existente como eliminado, incluso si se monta con la misma letra o ruta de la unidad y mostrará el nuevo LUN como nuevo recurso. Cuando el recurso se marca como eliminado, no se considerará para la actualización de la tecnología de almacenamiento en SnapCenter, y se perderán todos los backups del recurso anterior. Cuando se produce una actualización del almacenamiento, en el caso de recursos del sistema de archivos Windows, no se debe realizar la detección de recursos antes de ejecutar la API o el cmdlet de actualización de almacenamiento.

. Ejecute la API de actualización del almacenamiento: `/5.0/techrefresh/primarystorage` O bien el cmdlet: _Invoke-SmTechRefreshPrimaryStorage_.
+

NOTE: Si el recurso se configura con una política de replicación habilitada, el backup más reciente después de la actualización de almacenamiento debe tener detalles del almacenamiento secundario.

+
.. Si utiliza la configuración de instancias de clúster de conmutación por error (FCI) de SQL, las copias de seguridad se mantienen en el nivel del clúster. Debe proporcionar el nombre del clúster como entrada para la actualización de la tecnología de almacenamiento.
.. Si utiliza una configuración de SQL Availability Group (AG), los backups se mantienen en el nivel de nodo. Debe proporcionar el nombre de nodo como entrada para la actualización de la tecnología de almacenamiento.
.. Si utiliza la configuración de Oracle Real Application Clusters (RAC), puede realizar la actualización de la tecnología de almacenamiento en cualquier nodo.
+
El atributo _IsDryRun_ se establece en True de forma predeterminada. Así, se identificarán los recursos para los que se actualiza el almacenamiento. Puede ver el recurso y los detalles del almacenamiento modificados ejecutando la API '5,0/jobs/{jobid}' o el cmdlet _Get-SmJobSummaryReport_.



. Después de verificar los detalles del almacenamiento, establezca el atributo _IsDryRun_ en False y ejecute la API de actualización de almacenamiento: `/5.0/techrefresh/primarystorage` O bien el cmdlet: _Invoke-SmTechRefreshPrimaryStorage_.
+
Esto actualizará los detalles de almacenamiento en las copias de seguridad antiguas.

+
Puede ejecutar la API o el cmdlet en el mismo host varias veces y actualizará los detalles del almacenamiento de los backups anteriores solamente si se actualiza el almacenamiento.

+

NOTE: La jerarquía de clones no se puede migrar en ONTAP. Si el almacenamiento que se migra tiene metadatos de clonado en SnapCenter, el recurso clonado se marcará como recurso independiente. Los clones de los metadatos del clon se eliminarán de forma recursiva.

. (Opcional) Si no se mueven todas las snapshots del almacenamiento primario antiguo al nuevo, ejecute la siguiente API: `/5.0/hosts/primarybackupsexistencecheck` O el cmdlet _Invoke-SmPrimaryBackupsExistenceCheck_.
+
Esto realizará la comprobación de existencia de instantáneas en el nuevo almacenamiento primario y marcará los respectivos backups que no están disponibles para ninguna operación en SnapCenter.





== Actualice los backups del almacenamiento secundario

Cuando se actualiza la tecnología del almacenamiento, es conveniente ejecutar la API o el cmdlet de actualización técnica del almacenamiento para actualizar los backups antiguos en SnapCenter con los nuevos detalles del almacenamiento.

.Antes de empezar
Como este flujo de trabajo modifica los datos del repositorio de SnapCenter, se recomienda realizar una copia de seguridad del repositorio de SnapCenter. En caso de cualquier problema con los datos, el repositorio de SnapCenter puede revertirse a estado antiguo mediante el backup.

Para obtener más información, consulte https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Realice un backup del repositorio de SnapCenter"].

.Pasos
. Migrar los datos de un almacenamiento antiguo al nuevo.
+
Para obtener más información sobre cómo migrar, consulte:

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["Cómo migrar los datos a un nuevo almacenamiento"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["¿Cómo puedo copiar un volumen y conservar todas las copias Snapshot?"]


. Establezca la relación de SnapMirror entre el almacenamiento principal y el nuevo almacenamiento secundario, y asegúrese de que el estado de la relación sea correcto.
. En SnapCenter, cree un backup de los recursos cuyo almacenamiento se migra.
+
Es necesario un nuevo backup para que SnapCenter identifique el último espacio de almacenamiento y se utilizará para actualizar los metadatos de los backups anteriores existentes.

+

IMPORTANT: Debe esperar hasta que se complete esta operación. Si continúa con el siguiente paso antes de que finalice, SnapCenter perderá por completo metadatos de Snapshot secundarias antiguas.

. Después de crear correctamente el backup de todos los recursos de un host, ejecute la API de actualización del almacenamiento secundario: `/5.0/techrefresh/secondarystorage` O bien el cmdlet: _Invoke-SmTechRefreshSecondaryStorage_.
+
Esto actualizará los detalles del almacenamiento secundario de los backups anteriores en el host dado.

+
Si desea ejecutar esto a nivel de recurso, haga clic en *Actualizar* para cada recurso para actualizar los metadatos de almacenamiento secundario.

. Después de actualizar correctamente los backups antiguos, puede romper la relación de almacenamiento secundario anterior con el primario.

