---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords: SnapCenter Server 
summary: La información relacionada con las diversas operaciones que se ejecutan en SnapCenter se almacena en el repositorio de base de datos de servidor de SnapCenter. Es necesario crear backups del repositorio para proteger al servidor SnapCenter de una pérdida de datos. 
---
= Gestione el repositorio del servidor SnapCenter
:allow-uri-read: 


[role="lead"]
La información relacionada con las diversas operaciones que se ejecutan en SnapCenter se almacena en el repositorio de base de datos de servidor de SnapCenter. Es necesario crear backups del repositorio para proteger al servidor SnapCenter de una pérdida de datos.

El repositorio de SnapCenter Server a veces se denomina base de datos NSM. Consulta el  https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^] para ver detalles de todos los cmdlets disponibles.



== Requisitos previos para proteger el repositorio de SnapCenter

El entorno debe cumplir con ciertos requisitos previos para proteger el repositorio de SnapCenter.

* Gestionar conexiones de SVM
+
Debe configurar las credenciales de almacenamiento.

* Aprovisionar hosts
+
Debe haber al menos un disco de almacenamiento de NetApp en el host de repositorio de SnapCenter. Si no hay un disco de NetApp en el host de repositorio de SnapCenter, debe crearlo.

+
Para obtener detalles sobre cómo añadir hosts, configurar conexiones de SVM y aprovisionar hosts, consulte las instrucciones de instalación.

* Aprovisionar LUN de iSCSI o VMDK
+
Para la configuración de alta disponibilidad, puede aprovisionar un LUN de iSCSI o un VMDK en uno de los servidores SnapCenter.





== Realice un backup del repositorio de SnapCenter

Realizar una copia de seguridad del repositorio de SnapCenter Server ayuda a protegerlo frente a la pérdida de datos. Puedes hacer una copia de seguridad del repositorio ejecutando el  `Protect-SmRepository` cmdlet.

.Acerca de esta tarea
El `Protect-SmRepository` cmdlet realiza las siguientes tareas:

* Crea un grupo de recursos y una política
* Crea una programación de backups para el repositorio de SnapCenter


.Pasos
. Inicie PowerShell.
. En el host SnapCenter Server, establece una sesión usando el  `Open-SmConnection` cmdlet y escribe tus credenciales.
. Haz una copia de seguridad del repositorio usando el cmdlet `Protect-SmRepository` que toma los siguientes parámetros requeridos:
+
.. `-HostName (String)`: especifica el nombre de host del servidor donde se encuentra el repositorio de SnapCenter.
.. `-Path (String)`: especifica la ruta del sistema de archivos en el sistema de almacenamiento NetApp donde se almacenan las copias de seguridad del repositorio.
.. `-Schedule (Hashtable)`: define la programación para la copia de seguridad del repositorio. Normalmente se define como una tabla hash.
.. `-RetentionCount (Int32)`: especifica el número de copias de seguridad del repositorio que se deben conservar. Cuando el número de copias de seguridad supera este recuento, se elimina la copia de seguridad más antigua.






== Ver los backups del repositorio de SnapCenter

Puedes mostrar una lista de las copias de seguridad del repositorio de bases de datos de SnapCenter Server ejecutando el cmdlet `Get-SmRepositoryBackups`. Consulta el https://docs.netapp.com/us-en/snapcenter-cmdlets/Get-SmRepositoryBackups.html["Guía de referencia de cmdlets del software SnapCenter - Get-SmRepositoryBackups"^] para más detalles.

Las copias de seguridad del repositorio se crean según la programación especificada en el `Protect-SmRepository` cmdlet.

.Pasos
. Inicie PowerShell.
. Desde el símbolo del sistema, introduce el  `Open-SmConnection` cmdlet y proporciona las credenciales para conectarte al servidor SnapCenter.
. Muestra todas las copias de seguridad disponibles de la base de datos SnapCenter usando el cmdlet `Get-SmRepositoryBackups`.




== Restaurar el repositorio de la base de datos de SnapCenter

Puedes restaurar el repositorio de SnapCenter ejecutando el cmdlet `Restore-SmRepositoryBackup`.

Cuando estás restaurando el repositorio de SnapCenter, otras operaciones de SnapCenter que se estén ejecutando se ven afectadas porque durante la operación de restauración la base de datos del repositorio no está accesible.

.Pasos
. Inicie PowerShell.
. Desde el símbolo del sistema, introduce el  `Open-SmConnection` cmdlet y proporciona las credenciales para conectarte al servidor SnapCenter.
. Restaura la copia de seguridad del repositorio usando el `Restore-SmRepositoryBackup` cmdlet.
+
El siguiente cmdlet restaura el repositorio de bases de datos MySQL de SnapCenter desde los backups que existen en el LUN de iSCSI o VMDK:

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
El siguiente cmdlet restaura la base de datos MySQL de SnapCenter cuando se eliminan accidentalmente los archivos de backup del LUN de iSCSI. Para VMDK, restaure manualmente desde snapshots de ONTAP.

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----



NOTE: El backup que se utilizó para realizar la operación de restauración de repositorio no se mostrará cuando se recuperen los backups del repositorio después de realizar la operación de restauración.



== Migre el repositorio de SnapCenter

Es posible migrar el repositorio de la base de datos del servidor de SnapCenter de la ubicación predeterminada a otro disco. El repositorio puede migrarse cuando se desea reubicarlo en un disco con más espacio.

.Pasos
. Detenga el servicio MYSQL57 en Windows.
. Ubique el directorio de datos de MySQL.
+
Normalmente, puede encontrar el directorio de datos en C:\ProgramData\MySQL\MySQL Server 5.7\Data.

. Copie el directorio de datos de MySQL en la nueva ubicación, por ejemplo, E:\Data\nsm.
. Haga clic con el botón derecho en el nuevo directorio y seleccione *Propiedades* > *Seguridad* para agregar la cuenta de servidor local de Network Service al nuevo directorio y, a continuación, asigne el control total de la cuenta.
. Cambie el nombre del directorio original de la base de datos, por ejemplo, nsm_copy.
. Desde un símbolo del sistema de Windows, cree un vínculo de directorio simbólico mediante el comando _mklink_.
+
`"mklink /d "C:\ProgramData\MySQL\MySQL Server 5.7\Data\nsm" "E:\Data\nsm" "`

. Inicie el servicio MYSQL57 en Windows.
. Compruebe que la ubicación de la base de datos se haya modificado correctamente; para ello, inicie sesión en SnapCenter y verifique las entradas del repositorio, o inicie sesión en la utilidad MySQL y conéctese al nuevo repositorio.
. Elimine el directorio original del repositorio de la base de datos al que cambió el nombre (nsm_copy).




== Restablecer la contraseña del repositorio de SnapCenter

La contraseña de la base de datos del repositorio del servidor MySQL se genera automáticamente durante la instalación del servidor SnapCenter desde SnapCenter 4.2. El usuario de SnapCenter no conoce esta contraseña generada automáticamente en ningún momento. Si se desea acceder a la base de datos del repositorio, se debe restablecer la contraseña.

.Antes de empezar
Debe tener los privilegios de administrador de SnapCenter para restablecer la contraseña.

.Pasos
. Inicie PowerShell.
. Desde el símbolo del sistema, introduce el  `Open-SmConnection` cmdlet y proporciona las credenciales para conectarte al servidor SnapCenter.
. Restablece la contraseña del repositorio usando el `Set-SmRepositoryPassword` cmdlet.
+
El siguiente comando restablece la contraseña de repositorio:

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


.Información relacionada
Puedes obtener la información sobre los parámetros que puedes usar con el cmdlet y sus descripciones ejecutando el comando `Get-Help command_name`. O también, puedes consultar el https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].
