---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: Después de añadir el sistema de almacenamiento, es posible modificar las conexiones y la configuración del sistema de almacenamiento, o eliminar el sistema de almacenamiento. 
---
= Gestione el sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de añadir el sistema de almacenamiento, es posible modificar las conexiones y la configuración del sistema de almacenamiento, o eliminar el sistema de almacenamiento.



== Modifique la configuración del sistema de almacenamiento

Puede usar SnapCenter para modificar la configuración del sistema de almacenamiento si desea cambiar el nombre de usuario, la contraseña, la plataforma, el puerto, el protocolo, Período de tiempo de espera, dirección IP preferida o opciones de mensajería.

*Acerca de esta tarea*

Es posible modificar las conexiones de almacenamiento para un usuario individual o un grupo. Si pertenece a uno o varios grupos con permiso al mismo sistema de almacenamiento, el nombre de la conexión de almacenamiento se muestra varias veces en la lista de conexiones de almacenamiento, una vez para cada grupo con permiso al sistema de almacenamiento.

* Pasos*

. En el panel de navegación izquierdo, haga clic en *sistemas de almacenamiento*.
. En la página Storage Systems, en el menú desplegable *Tipo* realice una de las siguientes acciones:
+
|===
| Seleccione... | Pasos... 


 a| 
SVM de ONTAP
 a| 
Ver todas las máquinas virtuales de almacenamiento (SVM) que se añadieron y modificar la configuración de SVM necesaria.

.. En la página Storage Connections, haga clic en el nombre SVM adecuado.
.. Ejecute una de las siguientes acciones:
+
*** Si la SVM no forma parte de ningún clúster, en la página Modify Storage System, modifique las configuraciones como el nombre de usuario, la contraseña, la configuración de EMS y AutoSupport, la plataforma, el protocolo, el puerto, el tiempo de espera, Y la IP preferida.
*** Si el SVM forma parte de un clúster, en la página Modify Storage System, seleccione * Manage SVM independientemente* y modifique las configuraciones como el nombre de usuario, la contraseña, la configuración de EMS y AutoSupport, la plataforma, el protocolo, el puerto, el tiempo de espera, Y la IP preferida.
+
Después de modificar la SVM para que se gestione de forma independiente, si decide gestionarla a través del clúster, debe eliminar la SVM y, a continuación, hacer clic en *Rediscover*. La SVM se añadirá al clúster de ONTAP.

+

NOTE: Cuando se actualiza una contraseña del sistema de almacenamiento en la interfaz gráfica de usuario de SnapCenter, es necesario reiniciar los servicios de SMCore del plugin correspondiente o el host de servidor debido a que la contraseña actualizada no aparece en SMCore y los trabajos de backup fallarán con un error de credencial incorrecto.







 a| 
Clústeres ONTAP
 a| 
Para ver todos los clústeres que se han añadido y modificar la configuración de clúster necesaria.

.. En la página Storage Connections, haga clic en el nombre del clúster.
.. En la página Modify Storage System, haga clic en el icono para editar junto a Username y modifique el nombre de usuario y la contraseña.
.. Seleccione o borre la configuración de EMS y AutoSupport.
.. Haga clic en *más opciones* y modifique otras configuraciones como la plataforma, el protocolo, el puerto, el tiempo de espera y la IP preferida.


|===
. Haga clic en *Enviar*.




== Elimine el sistema de almacenamiento

Se puede usar SnapCenter para eliminar el sistema de almacenamiento que no se utiliza.

*Acerca de esta tarea*

Es posible eliminar conexiones de almacenamiento para un usuario individual o un grupo. Si pertenece a uno o varios grupos con permiso al mismo sistema de almacenamiento, el nombre del sistema de almacenamiento se muestra varias veces en la lista de conexiones de almacenamiento, una vez para cada grupo con permiso al sistema de almacenamiento.


IMPORTANT: Cuando se elimina un sistema de almacenamiento, se producirá un error en todas las operaciones que se están realizando en ese sistema de almacenamiento.

* Pasos*

. En el panel de navegación izquierdo, haga clic en *sistemas de almacenamiento*.
. En la página sistemas de almacenamiento, en el menú desplegable *Tipo*, seleccione *ONTAP SVM* o *clústeres ONTAP*.
. En la página Storage Connections, seleccione la casilla de comprobación junto a SVM o el clúster que desea eliminar.
+

NOTE: No puede seleccionar la SVM que forma parte de un clúster.

. Haga clic en *Eliminar*.
. En la página Delete Storage System Connection Settings (Eliminar configuración de conexión del sistema de almacenamiento), haga clic en *OK*.
+

NOTE: Si se elimina una SVM del clúster de ONTAP mediante la interfaz gráfica de usuario de ONTAP, en la interfaz gráfica de usuario de SnapCenter, haga clic en *Rediscover* para actualizar la lista de SVM.


