---
permalink: protect-postgresql/create-backup-policies-for-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: Antes de usar SnapCenter para realizar un backup de los recursos de clúster de PostgreSQL, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups. 
---
= Crear políticas de backup para PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar un backup de recursos de PostgreSQL, debe crear una política de backup para el recurso o grupo de recursos que desee incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups.

.Antes de empezar
* Debe tener definida una estrategia de backup.
+
Para obtener más detalles, consulte la información sobre cómo definir una estrategia de protección de datos para clústeres de PostgreSQL.

* Debe haberse preparado para la protección de datos completando tareas como instalar SnapCenter, añadir hosts, configurar las conexiones del sistema de almacenamiento y añadir recursos.
* El administrador de SnapCenter debe haberle asignado las instancias de SVM de los volúmenes de origen y de destino en caso de que replique snapshots en un reflejo o almacén.
+
Además, puede definir la configuración de replicación, script y aplicaciones en la política. Estas opciones ahorran tiempo cuando se desea volver a utilizar la política con otro grupo de recursos.



.Acerca de esta tarea
* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
** Si se especifica un período de bloqueo de instantáneas, se evita la eliminación de las instantáneas hasta que caduque el período de retención. Esto podría provocar que se retenga un número mayor de instantáneas que el recuento especificado en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.




.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Policy type, realice lo siguiente:
+
.. Seleccione el tipo de almacenamiento.
.. En la sección *Configuración de copia de seguridad personalizada*, proporcione cualquier configuración de copia de seguridad específica que tenga que pasarse al plugin en formato de clave-valor.
+
Puede pasar varios pares de clave-valor al plugin.



. En la página Backup and Replication, realice las siguientes acciones:
+
.. Especifique la frecuencia de programación seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de backup mientras crea un grupo de recursos. Esto le permite crear grupos de recursos que comparten la misma política y frecuencia de backup, pero también le permite asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.

.. En la sección Configuración de instantánea, especifique la configuración de retención para el tipo de copia de seguridad y el tipo de programación seleccionado en la página *Tipo de copia de seguridad*:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Mantenga un cierto número de Snapshots
 a| 
Seleccione *Copias para guardar* y, a continuación, especifique el número de instantáneas que desea conservar.

Si la cantidad de snapshots supera el número especificado, las snapshots se eliminan empezando por las más antiguas.


NOTE: Debe establecer el número de retención en 2 o un valor más alto si tiene pensado habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera Snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva Snapshot en el destino.


NOTE: El valor máximo de retención es 1018.  Las copias de seguridad fallarán si la retención se establece en un valor superior al que admite la versión de ONTAP .



 a| 
Mantenga los Snapshots durante una cierta cantidad de días
 a| 
Seleccione *Retener copias para* y, a continuación, especifique el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de copia de instantánea
 a| 
Seleccione *Período de bloqueo de copia de instantánea* y especifique días, meses o años.

El período de retención de SnapLock debe ser inferior a 100 años.

|===


. Seleccione una etiqueta de política.
+

NOTE: Puede asignar etiquetas SnapMirror a instantáneas principales para replicación remota, lo que permite que las instantáneas principales descarguen la operación de replicación de instantáneas de SnapCenter a los sistemas secundarios de ONTAP .  Esto se puede hacer sin habilitar la opción SnapMirror o SnapVault en la página de políticas.

. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
*Actualizar SnapMirror después de crear una copia Snapshot local*
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de backup en otro volumen (replicación de SnapMirror).

Si la relación en ONTAP es del tipo Reflejo y almacén y solo se selecciona esta opción, Snapshot creado en el origen no se transferirá al destino, pero figurará en el destino. Si esta copia Snapshot se selecciona del destino con el fin de realizar una operación de recuperación, aparece un mensaje de error indicando que la ubicación secundaria no está disponible para el backup reflejado/en almacenamiento.

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal.

Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Consulte link:view-postgresql-cluster-backups-and-clones-in-the-topology-page.html["Consulte los backups y los clones relacionados con los recursos de PostgreSQL en la página Topology"].



 a| 
*Actualizar SnapVault después de crear una copia Snapshot local*
 a| 
Seleccione esta opción para realizar una replicación de backup disco a disco (backups de SnapVault).

Durante la replicación secundaria, el tiempo de caducidad del SnapLock carga el tiempo de caducidad del SnapLock principal. Al hacer clic en el botón *Refrescar* de la página Topología, se actualiza el tiempo de caducidad de SnapLock secundario y primario que se recuperan de ONTAP.

Cuando SnapLock se configura solo en el secundario desde ONTAP conocido como Almacén de SnapLock, al hacer clic en el botón *Refrescar* de la página Topología se actualiza el período de bloqueo en el secundario que se recupera de ONTAP.

Para obtener más información sobre el almacén de SnapLock, consulte Confirmar instantáneas en WORM en un almacén
destino

Consulte link:view-postgresql-cluster-backups-and-clones-in-the-topology-page.html["Consulte los backups y los clones relacionados con los recursos de PostgreSQL en la página Topology"].



 a| 
*Número de reintentos de error*
 a| 
Escriba el número máximo de intentos de replicación que se permitirán antes de que la operación se detenga.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

