---
permalink: protect-postgresql/set-up-credentials-for-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: credentials, SnapCenter Plug-in for postgresql 
summary: SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar los plugins de SnapCenter, y credenciales adicionales para realizar operaciones de protección de datos en clústeres o sistemas de archivos Windows. 
---
= Configure credenciales para el plugin de SnapCenter para PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utiliza credenciales para autenticar usuarios para las operaciones de SnapCenter. Debe crear credenciales para instalar los plugins de SnapCenter, y credenciales adicionales para realizar operaciones de protección de datos en clústeres o sistemas de archivos Windows.

.Acerca de esta tarea
* Hosts Linux
+
Debe configurar credenciales para instalar plugins en hosts Linux.

+
Debe configurar las credenciales para el usuario raíz o un usuario que no sea raíz que tenga privilegios sudo para instalar e iniciar el proceso del plugin.

+
|===


| *Práctica recomendada:* aunque se permite crear credenciales para Linux después de implementar hosts e instalar plugins, la práctica recomendada es crear credenciales después de añadir SVM, antes de implementar hosts e instalar plugins. 
|===
* Host Windows
+
Debe configurar credenciales de Windows antes de instalar plugins.

+
Debe configurar las credenciales con privilegios de administrador, incluidos los derechos de administrador en el host remoto.



Si se configuran las credenciales para grupos de recursos individuales y el nombre de usuario no tiene privilegios de administrador completos, debe asignar al menos los privilegios de grupo de recursos y backup al nombre de usuario.

.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Settings, haga clic en *Credential*.
. Haga clic en *Nuevo*.
. En la página Credential, especifique la información necesaria para configurar las credenciales:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Nombre de credencial
 a| 
Introduzca un nombre para las credenciales.



 a| 
Nombre de usuario
 a| 
Introduzca el nombre de usuario y la contraseña que se utilizarán para la autenticación.

** Administrador de dominio o cualquier miembro del grupo de administradores
+
Especifique el administrador de dominio o cualquier miembro del grupo de administrador en el sistema en el que va a instalar el plugin de SnapCenter. Los formatos válidos para el campo Nombre de usuario son:

+
*** _NetBIOS\Username_
*** _Domain FQDN\Username_


** Administrador local (sólo para grupos de trabajo)
+
Para los sistemas que pertenecen a un grupo de trabajo, especifique el administrador local integrado en el sistema en el que va a instalar el plugin de SnapCenter. Puede especificar una cuenta de usuario local que pertenezca al grupo de administradores local si la cuenta de usuario tiene privilegios elevados o si la función de control de acceso de usuario está desactivada en el sistema host. El formato válido para el campo Username es: _Username_

+
No utilice comillas dobles (") ni marcas de retroceso (') en las contraseñas. No debe usar el signo menos de (<) y el signo de exclamación (!) los símbolos juntos en las contraseñas. Por ejemplo, arrendhan<!10, les10<!, backtick'12.





 a| 
Contraseña
 a| 
Introduzca la contraseña usada para autenticación.



 a| 
Modo de autenticación
 a| 
Seleccione el modo de autenticación que desea utilizar.



 a| 
Use privilegios sudo
 a| 
Seleccione la casilla de verificación *Use sudo Privileges* si va a crear credenciales para usuarios que no son raíz.


NOTE: Aplicable únicamente a usuarios Linux.

|===
. Haga clic en *Aceptar*.


Después de terminar de configurar las credenciales, se recomienda asignar el mantenimiento de credenciales a un usuario o un grupo de usuarios en la página User and Access.
