---
permalink: protect-postgresql/snapcenter-plug-in-for-postgresql-features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for postgresql 
summary: SnapCenter se integra con la aplicación de plugins y con tecnologías de NetApp en el sistema de almacenamiento. Para trabajar con el plugin para clúster postgresql, se utiliza la interfaz gráfica de usuario de SnapCenter. 
---
= Funciones del plugin de SnapCenter para PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter se integra con la aplicación de plugins y con tecnologías de NetApp en el sistema de almacenamiento. Para trabajar con el plugin para clúster PostgreSQL, se utiliza la interfaz gráfica de usuario de SnapCenter.

* *Interfaz gráfica de usuario unificada*
+
La interfaz de SnapCenter ofrece estandarización y consistencia entre plugins y entornos. La interfaz de SnapCenter permite completar operaciones de backup, restauración y clonado consistentes entre plugins, utilizar informes centralizados, utilizar visualizaciones de consola rápidas, configurar el RBAC y supervisar trabajos en todos los plugins.

* *Administración central automatizada*
+
Es posible programar operaciones de backup, configurar la retención de backup basado en políticas y realizar operaciones de restauración. También es posible supervisar de manera proactiva el entorno configurando SnapCenter para que envíe alertas por correo electrónico.

* *Tecnología de copia instantánea NetApp no disruptiva*
+
SnapCenter utiliza la tecnología Snapshot de NetApp con el clúster del plugin para PostgreSQL para realizar backups de recursos.



Usar el plugin para PostgreSQL también ofrece los siguientes beneficios:

* Compatibilidad con flujos de trabajo de backup, restauración y clonado
* Seguridad compatible con RBAC y delegación de roles centralizada
+
También es posible configurar las credenciales para que los usuarios de SnapCenter autorizados tengan permisos en el nivel de las aplicaciones.

* Creación de copias de recursos con gestión eficiente del espacio y en un momento específico con fines de prueba o de extracción de datos con la tecnología FlexClone de NetApp
+
Se requiere una licencia de FlexClone en el sistema de almacenamiento donde desea crear el clon.

* Compatibilidad con la función Snapshot del grupo de coherencia (CG) de ONTAP como parte de la creación de backups.
* Capacidad para ejecutar varios backups de forma simultánea entre varios hosts de recursos
+
En una sola operación se consolidan Snapshot cuando los recursos en un solo host comparten el mismo volumen.

* Capacidad para crear snapshots con comandos externos
* Compatibilidad con LVM de Linux en el sistema de archivos XFS.

