---
permalink: protect-postgresql/types-of-restore-strategies-supported-for-manually-added-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter. Hay dos tipos de estrategias de restauración para los recursos PostgreSQL agregados manualmente. No se pueden recuperar recursos PostgreSQL añadidos manualmente. 
---
= Tipos de estrategias de restauración compatibles con los recursos PostgreSQL añadidos manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter.


NOTE: No se pueden recuperar recursos PostgreSQL añadidos manualmente.



== Restauración de recursos completa

* Restaura todos los volúmenes, qtrees y LUN de un recurso



NOTE: Si el recurso contiene volúmenes o qtrees, las copias de Snapshot tomadas después de la copia de Snapshot seleccionada para restaurar en los volúmenes o qtrees se eliminan y no pueden recuperarse. Además, si hay algún otro recurso alojado en los mismos volúmenes o qtrees, también se lo elimina.

NOTA: El plugin para PostgreSQL crea una etiqueta de copia de seguridad y un mapa de tablespace en la carpeta _/<OS_temp_folder>/postgresql_sc_recovery_<Restore_JobId>/_ para ayudar a recuperar manualmente.
