---
permalink: install/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter requiere varias licencias para permitir operaciones de protección de datos. El tipo de licencia de SnapCenter que instale dependerá del entorno de almacenamiento y de las funciones que desee utilizar. 
---
= Licencias SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter requiere varias licencias para permitir la protección de datos de aplicaciones, bases de datos, sistemas de archivos y máquinas virtuales. El tipo de licencia de SnapCenter que instale dependerá del entorno de almacenamiento y de las funciones que desee utilizar.

|===
| Licencia | Donde se la requiere 


 a| 
Basado en controladora estándar de SnapCenter
 a| 
Necesaria para cabinas FAS, AFF y All SAN (ASA)

La licencia estándar de SnapCenter es una licencia basada en la controladora y se incluye como parte del paquete Premium. Si tiene la licencia de conjunto de SnapManager, también obtendrá el derecho de licencia estándar de SnapCenter. Si desea instalar SnapCenter a modo de prueba con almacenamiento FAS, AFF o ASA, puede obtener una licencia de evaluación Premium Bundle poniéndose en contacto con el representante de ventas.


NOTE: SnapCenter también se ofrece como parte del paquete de protección de datos. Si ha adquirido el A400 o una versión posterior, debe comprar el paquete de protección de datos.



 a| 
SnapCenter basada en capacidad estándar
 a| 
Necesario con ONTAP Select y Cloud Volumes ONTAP

Si es cliente de Cloud Volumes ONTAP o ONTAP Select, necesita adquirir una licencia basada en capacidad por TB en función de los datos gestionados por SnapCenter. De forma predeterminada, SnapCenter envía una licencia de prueba integrada basada en capacidad estándar de SnapCenter de 90 días y 100 TB. Si desea obtener más detalles, póngase en contacto con el representante de ventas.



 a| 
SnapMirror o SnapVault
 a| 
ONTAP

Se requieren licencias de SnapMirror o SnapVault si la replicación se habilita en SnapCenter.



 a| 
SnapRestore
 a| 
Necesario para restaurar y verificar backups.

En sistemas de almacenamiento principales

* Requerida en sistemas de destino de SnapVault para realizar la verificación remota y restaurar desde un backup
* Requerida en sistemas de destino de SnapMirror para realizar la verificación remota




 a| 
FlexClone
 a| 
Necesario para clonar bases de datos y operaciones de verificación.

En sistemas de almacenamiento principales y secundarios

* Requerida en sistemas de destino de SnapVault para crear clones a partir de un backup de almacén secundario
* Requerida en sistemas de destino de SnapMirror para crear clones a partir de un backup de SnapMirror secundario




 a| 
Protocolos
 a| 
* Licencia de iSCSI o FC para LUN
* Licencia de CIFS para recursos compartidos de SMB
* Licencia de NFS para VMDK de tipo NFS
* Licencia de iSCSI o FC para VMDK de tipo VMFS


Requerida en sistemas de destino de SnapMirror para suministrar datos si un volumen de origen no se encuentra disponible



 a| 
Licencias estándar de SnapCenter (opcional)
 a| 
Destinos secundarios


NOTE: Se recomienda, pero no es obligatorio, añadir licencias estándar de SnapCenter a destinos secundarios. Si las licencias estándar de SnapCenter están deshabilitadas en destinos secundarios, no puede usar SnapCenter para realizar un backup de los recursos en el destino secundario después de realizar una operación de conmutación al nodo de respaldo. Sin embargo, se requiere una licencia de FlexClone en destinos secundarios para realizar operaciones de clonado y verificación.

|===

NOTE: Las licencias avanzada y SnapCenter de servicios de archivos NAS de SnapCenter quedaron obsoletas y ya no están disponibles.

Debe instalar una o más licencias de SnapCenter. Para obtener información acerca de cómo agregar licencias, consulte link:../install/concept_snapcenter_standard_controller_based_licenses.html["Añada licencias estándar basadas en controladora de SnapCenter"] o. link:../install/concept_snapcenter_standard_capacity_based_licenses.html["Añada licencias basadas en capacidad estándar de SnapCenter"].



== Licencias de Single Mailbox Recovery (SMBR)

Si utiliza el plugin de SnapCenter para Exchange para gestionar bases de datos de Microsoft Exchange Server y Single Mailbox Recovery (SMBR), necesita una licencia adicional para SMBR, la cual debe adquirirse por separado en función del buzón de usuario.

NetApp® Single Mailbox Recovery ha llegado al final de la disponibilidad (EOA) el 12 de mayo de 2023. Para obtener más información, consulte link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"]. NetApp continuará prestando soporte a los clientes que hayan adquirido capacidad, mantenimiento y soporte de sus buzones mediante números de referencia de marketing introducidos el 24 de junio de 2020, durante el periodo de concesión de soporte.

Single Mailbox Recovery de NetApp es un producto de partner que proporciona Ontrack. Ontrack PowerControls ofrece capacidades similares a las de Single Mailbox Recovery de NetApp. Los clientes pueden adquirir nuevas licencias de software Ontrack PowerControls y renovaciones de mantenimiento y soporte de Ontrack PowerControls desde Ontrack (hasta licensingteam@ontrack.com) para la recuperación granular de buzones después de la fecha EOA del 12 de mayo de 2023.
