---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: Las credenciales utilizan métodos de autenticación diferentes según la aplicación o el entorno. Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter. Debe crear un conjunto de credenciales para instalar plugins y otros conjuntos para operaciones de protección de datos. 
---
= Métodos de autenticación para las credenciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las credenciales utilizan métodos de autenticación diferentes según la aplicación o el entorno. Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter. Debe crear un conjunto de credenciales para instalar plugins y otros conjuntos para operaciones de protección de datos.



== Autenticación de Windows

El método de autenticación de Windows autentica de acuerdo con Active Directory. Para la autenticación de Windows, se configura Active Directory fuera de SnapCenter. SnapCenter autentica sin configuración adicional. Se necesita una credencial de Windows para realizar ciertas tareas, como añadir hosts, instalar paquetes de plugins y programar trabajos.



== Autenticación de dominio que no es de confianza

SnapCenter permite la creación de credenciales de Windows mediante usuarios y grupos que pertenecen a dominios que no son de confianza. Para que la autenticación se complete correctamente, debe registrar los dominios que no son de confianza en SnapCenter.



== Autenticación de grupo de trabajo local

SnapCenter permite la creación de credenciales de Windows con grupos y usuarios de grupo de trabajo local. La autenticación de Windows para usuarios y grupos de grupos de trabajo locales no ocurre en el momento de la creación de credenciales de Windows, sino que se aplaza hasta que se realizan el registro de host y otras operaciones de host.



== Autenticación de SQL Server

El método de autenticación de SQL se verifica de acuerdo con una instancia de SQL Server. Esto significa que debe detectarse una instancia de SQL Server en SnapCenter. Por lo tanto, antes de añadir una credencial de SQL, debe añadir un host, instalar paquetes de plugins y actualizar los recursos. Necesita la autenticación de SQL Server para realizar operaciones, como programar en SQL Server o detectar recursos.



== Autenticación de Linux

El método de autenticación de Linux autentica con un host Linux. Necesita la autenticación de Linux durante el paso inicial de añadir el host Linux e instalar el paquete de plugins de SnapCenter para Linux de forma remota desde la interfaz gráfica de usuario de SnapCenter.



== Autenticación AIX

El método de autenticación AIX autentica con un host AIX. Necesita la autenticación de AIX durante el paso inicial de añadir el host AIX e instalar el paquete de plugins de SnapCenter para AIX de forma remota desde la interfaz gráfica de usuario de SnapCenter.



== Autenticación de base de datos de Oracle

El método de autenticación de base de datos de Oracle autentica con una base de datos de Oracle. Necesita una autenticación de base de datos de Oracle para realizar operaciones en la base de datos de Oracle si la autenticación de sistema operativo (SO) está deshabilitada en el host de bases de datos. Por lo tanto, antes de agregar una credencial de base de datos Oracle, debe crear un usuario de Oracle en la base de datos Oracle con privilegios sysdba.



== Autenticación de Oracle ASM

El método de autenticación de Oracle ASM autentica con una instancia de Oracle Automatic Storage Management (ASM). Si debe acceder a la instancia de Oracle ASM y si la autenticación de sistema operativo (SO) está deshabilitada en el host de bases de datos, se necesita una autenticación de Oracle ASM. Por lo tanto, antes de añadir una credencial de Oracle ASM, debe crear un usuario de Oracle con privilegios sysasm en la instancia de ASM.



== Autenticación de catálogo de RMAN

El método de autenticación de catálogo de RMAN autentica con la base de datos de catálogos de Oracle Recovery Manager (RMAN). Si configuró un mecanismo de catálogo externo y registró la base de datos en la base de datos de catálogos, debe añadir una autenticación de catálogo de RMAN.
