---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6,1 es compatible con sistemas ASA R2 que crean una experiencia más simplificada específica para las necesidades de clientes de solo SAN. 
---
= Obtenga información sobre la compatibilidad con los sistemas R2 de ASA en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6,1 es compatible con sistemas ASA R2 que crean una experiencia más simplificada específica para las necesidades de clientes de solo SAN.

Los sistemas R2 de ASA son compatibles con todos los protocolos SAN (iSCSI, FC y NVMe sobre TCP/IP) en una única puesta en marcha de par de alta disponibilidad. Los protocolos SCSI (iSCSI y FC) utilizan una arquitectura activo-activo simétrica para la multivía, de modo que todas las rutas entre los hosts y el almacenamiento estén activas/optimizadas. Los protocolos iSCSI y NVMe/TCP admiten rutas directas entre los hosts y el almacenamiento.


NOTE: SnapCenter admite únicamente el sistema de archivos de máquina virtual (VMFS) VMware en sistemas ASA R2.

Los sistemas R2 de ASA introducen el uso de unidades de almacenamiento con grupos de coherencia:

* Una unidad de almacenamiento pone el espacio de almacenamiento a disposición de los hosts de SAN para realizar operaciones de datos. Una unidad de almacenamiento hace referencia a un LUN para hosts SCSI o un espacio de nombres NVMe para los hosts NVMe.
* Un grupo de consistencia es una colección de unidades de almacenamiento que se administran como una sola unidad.


Los sistemas R2 de ASA utilizan unidades de almacenamiento y grupos de consistencia para simplificar la administración del almacenamiento y la protección de datos. Por ejemplo, suponga que tiene una base de datos que consta de 10 unidades de almacenamiento en un grupo de coherencia y necesita realizar un backup de toda la base de datos. En lugar de realizar un backup de cada unidad de almacenamiento de forma individual, puede proteger toda la base de datos mediante un backup del grupo de coherencia.

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Obtenga más información sobre los sistemas R2 de ASA"].



== Qué es compatible en SnapCenter 6,1 para los sistemas ASA R2

SnapCenter le permite realizar las siguientes operaciones en todas las aplicaciones compatibles con SnapCenter si utiliza sistemas de almacenamiento ASA R2:

* Crear backups primarios de aplicaciones en VMDK
* Transferir snapshots de grupo de coherencia a sistema de almacenamiento secundario
* Restaurar los backups y restaurar a partir de una ubicación alternativa
+
** Restauración sin movimiento desde almacenamiento primario y secundario mediante VMware vMotion
** Conecte y restaure copias de almacenamiento primario y secundario


* Clona los backups y también los clona a una ubicación alternativa




== ¿Qué no es compatible con SnapCenter 6,1 para los sistemas ASA R2

* Asignación de dispositivo sin formato (RDM)
* Volúmenes de aplicaciones para Oracle
* NDV DE SAP HANA
* Vault
* Instantánea a prueba de manipulaciones
* Grupo Flexible
* Grupo de coherencia jerárquico
* Migración de sistemas ONTAP 9.x a ASA R2
* Cambio de nombre de instantáneas
* SnapCenter no admite el aprovisionamiento secundario del directorio de registro del host del plugin de SQL. Debe configurar manualmente mediante la interfaz de línea de comandos de ONTAP o System Manager.

