---
permalink: install/reference_supported_browsers.html 
sidebar: sidebar 
keywords: SnapCenter, browsers, chrome, IE, Edge 
summary: El software SnapCenter se puede usar en diversos exploradores. 
---
= Exploradores compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El software SnapCenter se puede usar en diversos exploradores.

* Cromo
+
Si utiliza v66, es posible que no se pueda iniciar la interfaz gráfica de usuario de SnapCenter.

* Internet Explorer
+
La interfaz de usuario de SnapCenter no se carga correctamente si se utiliza IE 10 o versiones anteriores. Debe actualizar a IE 11.

+
** Tan solo se ofrece compatibilidad para las funciones de seguridad de nivel predeterminado.
+
Realizar cambios en la configuración de seguridad de Internet Explorer puede dar como resultado problemas significativos de visualización para el explorador.

** Es necesario deshabilitar la vista de compatibilidad de Internet Explorer.


* Microsoft Edge


Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=108380;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].
