---
permalink: install/reference_san_host_requirements.html 
sidebar: sidebar 
keywords: host utilities, Microsoft DSM, Windows MPIO 
summary: Si el host de SnapCenter forma parte de un entorno FC/iSCSI, puede que tenga que instalar software adicionales en el sistema para habilitar el acceso al almacenamiento ONTAP. 
---
= Requisitos del host SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el host de SnapCenter forma parte de un entorno FC/iSCSI, puede que tenga que instalar software adicionales en el sistema para habilitar el acceso al almacenamiento ONTAP.

SnapCenter no incluye las utilidades de host ni DSM. Si el host de SnapCenter forma parte de un entorno SAN, puede tener que instalar y configurar el siguiente software:

* Utilidades de host
+
Las utilidades de host son compatibles con FC e iSCSI, y le permiten usar MPIO en sus servidores Windows. Para obtener más información, consulte https://["Documentación de utilidades de host"^].

* Microsoft DSM para Windows MPIO
+
Este software funciona con controladores Windows MPIO para gestionar varias rutas entre equipos host de Windows y NetApp.

+
Se requiere un DSM para configuraciones de alta disponibilidad.

+

NOTE: Si estaba utilizando ONTAP DSM, debe migrar a Microsoft DSM. Para obtener más información, consulte https://["Cómo migrar desde ONTAP DSM a Microsoft DSM"^].


