---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: Debe asegurarse de que se cumplan los requisitos de conexiones y puertos antes de instalar SnapCenter Server y los plugins de aplicación o base de datos. 
---
= Requisitos de conexión y puerto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que se cumplan los requisitos de conexiones y puertos antes de instalar SnapCenter Server y los plugins de aplicación o base de datos.

* Las aplicaciones no pueden compartir los puertos.
+
Cada puerto debe ser dedicado a la aplicación adecuada.

* En el caso de los puertos personalizables, puede seleccionar un puerto personalizado durante la instalación si no quiere usar el predeterminado.
+
Puede cambiar un puerto de plugin después de la instalación usando el asistente Modify host.

* En el caso de los puertos fijos, tiene que aceptar el número de puerto predeterminado.
* Servidores de seguridad
+
** Firewalls, proxies u otros dispositivos de red no deben interferir con las conexiones.
** Si especifica un puerto personalizado al instalar SnapCenter, tendrá que añadir un regla de firewall en el host del plugin para dicho puerto en el cargador del plugin de SnapCenter.




En la tabla siguiente se enumeran los distintos puertos y sus valores predeterminados.

|===
| Nombre de puerto | Números de puerto | Protocolo | Dirección | Descripción 


 a| 
Puerto SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se usa para establecer la comunicación entre el cliente SnapCenter (el usuario SnapCenter) y el servidor SnapCenter, y también se utiliza para establecer la comunicación de los hosts del plugin con el servidor SnapCenter.

Puede personalizar el número de puerto.



 a| 
Puerto de comunicación SMCore de SnapCenter
 a| 
8145
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre SnapCenter Server y los hosts en los que se han instalado los plugins de SnapCenter.

Puede personalizar el número de puerto.



 a| 
Puerto de servicio del programador
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Este puerto se utiliza para orquestar los flujos de trabajo del programador de SnapCenter para todos los plugins gestionados dentro del host del servidor SnapCenter de forma centralizada.

Puede personalizar el número de puerto.



 a| 
Puerto RabbitMQ
 a| 
5672
 a| 
TCP
 a| 
 a| 
Este es el puerto predeterminado en el que RabbitMQ escucha y se utiliza para la comunicación del modelo editor-suscriptor entre el servicio Programador y SnapCenter.



 a| 
Puerto MySQL
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
El puerto se utiliza para comunicarse con la base de datos del repositorio de SnapCenter. Puede crear conexiones seguras desde el servidor SnapCenter al servidor MySQL. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Leer más"]



 a| 
Hosts de plugins de Windows
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Este puerto se utiliza para establecer la comunicación entre el servidor de SnapCenter y el host en el que se está instalando el plugin. El rango de puertos dinámicos adicional especificado por Microsoft también debe estar abierto.



 a| 
Hosts de plugins de Linux o AIX
 a| 
22
 a| 
SSH
 a| 
Unidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre el servidor de SnapCenter y el host, iniciado desde el servidor al host del cliente.



 a| 
Paquete de plugins de SnapCenter para Windows, Linux o AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre SMCore y los hosts en los que está instalado el paquete de plugins. Personalizable.

Puede personalizar el número de puerto.



 a| 
Plugin de SnapCenter para base de datos de Oracle
 a| 
27216
 a| 
 a| 
 a| 
El puerto de JDBC predeterminado, lo utiliza el plugin para Oracle para conectarse a la base de datos de Oracle.



 a| 
Plugin de SnapCenter para base de datos de Exchange
 a| 
909
 a| 
 a| 
 a| 
NET predeterminado. El plugin para Windows utiliza el puerto TCP para conectarse a las devoluciones de llamadas VSS de Exchange.



 a| 
Complementos compatibles con NetApp para SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Se trata de un puerto interno que se usa solo en el host del plugin personalizado; no son obligatorias las excepciones de firewall.

La comunicación entre SnapCenter Server y los plugins personalizados pasa a través del puerto 8145.



 a| 
Puerto de comunicación del clúster de ONTAP o de SVM
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidireccional
 a| 
El puerto se utiliza en SAL (capa de abstracción del almacenamiento) para establecer la comunicación entre el host que ejecuta SnapCenter Server y SVM. Actualmente, el puerto también se utiliza en SAL en SnapCenter para los hosts del plugin de Windows para establecer la comunicación entre el host del plugin de SnapCenter y SVM.



 a| 
Plugin de SnapCenter para base de datos SAP HANA
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidireccional
 a| 
Para un tenant único de un contenedor de base de datos multitenant (MDC), el número del puerto termina en 13; para los que no son MDC, el número de puerto termina en 15.

Puede personalizar el número de puerto.



 a| 
Complemento de SnapCenter para PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Este puerto es el puerto PostgreSQL predeterminado utilizado para la comunicación del plugin para PostgreSQL con el clúster PostgreSQL.

Puede personalizar el número de puerto.

|===
Para modificar los detalles del puerto, consulte link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["Modifique los hosts de plugins"].
