---
permalink: install/reference_provision_storage_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: Provision storage, snapcenter 
summary: Si no desea utilizar la interfaz gráfica de usuario de SnapCenter para realizar trabajos de aprovisionamiento de hosts y reclamación de espacio, puede utilizar los cmdlets de PowerShell que ofrece el plugin de SnapCenter para Microsoft Windows. Puede usar los cmdlets directamente o añadirlos a scripts. 
---
= Aprovisionar el almacenamiento mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si no desea utilizar la interfaz gráfica de usuario de SnapCenter para realizar trabajos de aprovisionamiento de hosts y reclamación de espacio, puede utilizar los cmdlets de PowerShell que ofrece el plugin de SnapCenter para Microsoft Windows. Puede usar los cmdlets directamente o añadirlos a scripts.

Si ejecuta los cmdlets en el host de un plugin remoto, debe ejecutar el cmdlet SnapCenter Open-SMConnection para abrir una conexión con el servidor SnapCenter.

La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2886895["Guía de referencia de cmdlets de SnapCenter Software"^].

Si los cmdlets de PowerShell de SnapCenter se rompen debido a la eliminación de SnapDrive para Windows del servidor, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_cmdlets_broken_when_SnapDrive_for_Windows_is_uninstalled["Los cmdlets de SnapCenter se rompen cuando se desinstala SnapDrive para Windows"^].
