---
permalink: install/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Debe conocer cuáles son los sistemas de almacenamiento, las aplicaciones y las bases de datos compatibles. 
---
= Sistemas de almacenamiento y aplicaciones compatibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer cuáles son los sistemas de almacenamiento, las aplicaciones y las bases de datos compatibles.

* SnapCenter admite ONTAP 9.12.1 y versiones posteriores para proteger sus datos.
+
Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.

* SnapCenter 6,1 es compatible con sistemas NetApp ASA R2 que ejecutan ONTAP 9.16.1.
+
Los sistemas R2 de ASA ofrecen una solución unificada de hardware y software para entornos SAN basados en plataformas all-flash.

+
Para obtener información sobre los sistemas ASA R2, consulte https://docs.netapp.com/us-en/asa-r2/index.html["Documentación de ASA r2"^].

* SnapCenter es compatible con Amazon FSx para NetApp ONTAP para proteger tus datos.
+
Si utiliza Amazon FSX para ONTAP de NetApp, asegúrese de que los plugins del host del servidor SnapCenter se actualicen a 4.5 P1 o una versión posterior para realizar operaciones de protección de datos.

+
Admite memoria no volátil rápida (NVMe) con protocolo de control de transporte (TCP).

+
Para obtener más información sobre Amazon FSX para ONTAP de NetApp, consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentación de Amazon FSX para ONTAP de NetApp"^].

* SnapCenter admite la protección de distintas aplicaciones y bases de datos.
+
Para obtener información detallada sobre las aplicaciones y bases de datos soportadas, consulte https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].

* SnapCenter 4,9 P1 y versiones posteriores admiten la protección de las cargas de trabajo de Oracle y Microsoft SQL en entornos de centro de datos definido por software (SDDC) de VMware Cloud on Amazon Web Services (AWS).
+
Para obtener más información, consulte https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Proteja las cargas de trabajo de Oracle y MS SQL mediante NetApp SnapCenter en entornos SDDC de VMware Cloud on AWS"].


