---
permalink: install/requirements-to-install-snapcenter-server.html 
sidebar: sidebar 
keywords: active directory domain, workgroups, multi-domain forests, cross-domain, cross-forest domains, browsers, chrome, IE, Edge, ports, port requirements, host utilities, Microsoft DSM, Windows MPIO 
summary: Debe asegurarse de que se cumplen todos los requisitos antes de instalar el servidor SnapCenter 
---
= Requisitos para instalar el servidor SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar SnapCenter Server en el host de Windows o Linux, debe revisar y asegurarse de que se cumplan todos los requisitos para su entorno.



== Requisitos del dominio y grupos de trabajo para el host Windows

El servidor de SnapCenter puede instalarse en un host de Windows que esté en un dominio o en un grupo de trabajo.

El usuario que tiene Privileges de administrador puede instalar el servidor de SnapCenter.

* Dominio de Active Directory: Debe usar un usuario de dominio con derechos de administrador local. El usuario de dominio debe ser miembro del grupo de administrador local en el host de Windows.
* Grupos de trabajo: Debe utilizar una cuenta local que tenga derechos de administrador local.


Mientras que las confianzas de dominio, bosques de multidominio y confianzas entre dominios son compatibles, los dominios entre bosques no lo son. La documentación de Microsoft acerca de Dominios y confianzas de Active Directory contiene más información.


NOTE: Tras instalar el servidor SnapCenter, no debe cambiar el dominio en el que se encuentra el host SnapCenter. Si quita el host de SnapCenter Server del dominio en el que estaba cuando se instaló el servidor SnapCenter y, a continuación, intenta desinstalar SnapCenter Server, la operación de desinstalación fracasará.



== Requisitos de espacio y de tamaño

Debería estar familiarizado con los requisitos de espacio y tamaño.

|===
| Elemento | Requisitos del host de Windows | Requisitos del host Linux 


 a| 
Sistemas operativos
 a| 
Microsoft Windows

Solo se admiten las versiones en inglés, alemán, japonés y chino simplificado de los sistemas operativos.

Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].
 a| 
* Red Hat Enterprise Linux (RHEL) 8 y 9
* SUSE Linux Enterprise Server (SLES) 15


Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].



 a| 
Recuento de CPU mínimo
 a| 
4 núcleos
 a| 
4 núcleos



 a| 
RAM mínimo
 a| 
8 GB


NOTE: El grupo de buffers de MySQL Server utiliza el 20 por ciento de la RAM total.
 a| 
8 GB



 a| 
Espacio mínimo en disco duro para el software y los registros del servidor SnapCenter
 a| 
7 GB


NOTE: Si tiene el repositorio de SnapCenter en la misma unidad donde está instalado el servidor SnapCenter, se recomienda tener 15 GB.
 a| 
15 GB



 a| 
Espacio en disco duro mínimo para el repositorio de SnapCenter
 a| 
8 GB


NOTE: NOTA: Si tiene el servidor SnapCenter en la misma unidad en la que está instalado el repositorio de SnapCenter, se recomienda tener 15 GB.
 a| 
No aplicable



 a| 
Paquetes de software obligatorios
 a| 
* ASP.NET Core Runtime 8.0.12 (y todos los parches 8,0.x posteriores) Hosting Bundle
* PowerShell 7.4.2 o posterior


Para obtener información específica sobre la solución de problemas de .NET, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["La actualización o instalación de SnapCenter falla para sistemas heredados que no tienen conectividad a Internet"^].
 a| 
* .NET Framework 8.0.12 (y todos los parches 8,0.x posteriores)
* PowerShell 7.4.2 o posterior
* Nginx es un servidor web que se puede utilizar como proxy inverso
* PAM-devel
+
PAM (Pluggable Authentication Modules) es una herramienta de seguridad del sistema que permite a los administradores del sistema establecer la política de autenticación sin tener que volver a compilar programas que hacen autenticación.



|===

NOTE: El núcleo ASP.NET necesita IIS_IUSRS para acceder al sistema de archivos temporales en el servidor SnapCenter en Windows.



== Requisitos del host SAN

SnapCenter no incluye utilidades de host ni un DSM. Si el host de SnapCenter forma parte de un entorno SAN (FC/iSCSI), puede que tenga que instalar y configurar software adicional en el host de SnapCenter.

* Utilidades de host: Las utilidades de host son compatibles con FC e iSCSI, y le permiten usar MPIO en sus servidores Windows. https://docs.netapp.com/us-en/ontap-sanhost/hu_sanhost_index.html["Más información"^].
* Microsoft DSM para Windows MPIO: Este software funciona con controladores Windows MPIO para gestionar varias rutas entre equipos host de Windows y NetApp. Se requiere un DSM para configuraciones de alta disponibilidad.
+

NOTE: Si estaba utilizando ONTAP DSM, debe migrar a Microsoft DSM. Para obtener más información, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Data_ONTAP_DSM_for_Windows_MPIO/How_to_migrate_from_Data_ONTAP_DSM_4.1p1_to_Microsoft_native_DSM["Cómo migrar desde ONTAP DSM a Microsoft DSM"^].





== Requisitos de navegador

El software SnapCenter es compatible con Chrome 125 y versiones posteriores, y Microsoft Edge 110.0.1587.17 y versiones posteriores.



== Requisitos de puertos

El software SnapCenter requiere diferentes puertos para la comunicación entre diferentes componentes.

* Las aplicaciones no pueden compartir los puertos.
* En el caso de los puertos personalizables, puede seleccionar un puerto personalizado durante la instalación si no quiere usar el predeterminado.
* En el caso de los puertos fijos, tiene que aceptar el número de puerto predeterminado.
* Servidores de seguridad
+
** Firewalls, proxies u otros dispositivos de red no deben interferir con las conexiones.
** Si especifica un puerto personalizado al instalar SnapCenter, tendrá que añadir un regla de firewall en el host del plugin para dicho puerto en el cargador del plugin de SnapCenter.




En la tabla siguiente se enumeran los distintos puertos y sus valores predeterminados.

|===
| Nombre de puerto | Números de puerto | Protocolo | Dirección | Descripción 


 a| 
Puerto SnapCenter
 a| 
8146
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se usa para establecer la comunicación entre el cliente SnapCenter (el usuario SnapCenter) y el servidor SnapCenter, y también se utiliza para establecer la comunicación de los hosts del plugin con el servidor SnapCenter.

Puede personalizar el número de puerto.



 a| 
Puerto de comunicación SMCore de SnapCenter
 a| 
8145
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre SnapCenter Server y los hosts en los que se han instalado los plugins de SnapCenter.

Puede personalizar el número de puerto.



 a| 
Puerto de servicio del programador
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
Este puerto se utiliza para orquestar los flujos de trabajo del programador de SnapCenter para todos los plugins gestionados dentro del host del servidor SnapCenter de forma centralizada.

Puede personalizar el número de puerto.



 a| 
Puerto RabbitMQ
 a| 
5672
 a| 
TCP
 a| 
 a| 
Este es el puerto predeterminado en el que RabbitMQ escucha y se utiliza para la comunicación del modelo editor-suscriptor entre el servicio Programador y SnapCenter.



 a| 
Puerto MySQL
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
El puerto se utiliza para comunicarse con la base de datos del repositorio de SnapCenter. Puede crear conexiones seguras desde el servidor SnapCenter al servidor MySQL. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["Leer más"]



 a| 
Hosts de plugins de Windows
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
Este puerto se utiliza para establecer la comunicación entre el servidor de SnapCenter y el host en el que se está instalando el plugin. El rango de puertos dinámicos adicional especificado por Microsoft también debe estar abierto.



 a| 
Hosts de plugins de Linux o AIX
 a| 
22
 a| 
SSH
 a| 
Unidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre el servidor de SnapCenter y el host, iniciado desde el servidor al host del cliente.



 a| 
Paquete de plugins de SnapCenter para Windows, Linux o AIX
 a| 
8145
 a| 
HTTPS
 a| 
Bidireccional
 a| 
Este puerto se utiliza para establecer la comunicación entre SMCore y los hosts en los que está instalado el paquete de plugins. Personalizable.

Puede personalizar el número de puerto.



 a| 
Plugin de SnapCenter para base de datos de Oracle
 a| 
27216
 a| 
 a| 
 a| 
El puerto de JDBC predeterminado, lo utiliza el plugin para Oracle para conectarse a la base de datos de Oracle.



 a| 
Plugin de SnapCenter para base de datos de Exchange
 a| 
909
 a| 
 a| 
 a| 
NET predeterminado. El plugin para Windows utiliza el puerto TCP para conectarse a las devoluciones de llamadas VSS de Exchange.



 a| 
Complementos compatibles con NetApp para SnapCenter
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
Se trata de un puerto interno que se usa solo en el host del plugin personalizado; no son obligatorias las excepciones de firewall.

La comunicación entre SnapCenter Server y los plugins personalizados pasa a través del puerto 8145.



 a| 
Puerto de comunicación del clúster de ONTAP o de SVM
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
Bidireccional
 a| 
El puerto se utiliza en SAL (capa de abstracción del almacenamiento) para establecer la comunicación entre el host que ejecuta SnapCenter Server y SVM. Actualmente, el puerto también se utiliza en SAL en SnapCenter para los hosts del plugin de Windows para establecer la comunicación entre el host del plugin de SnapCenter y SVM.



 a| 
Plugin de SnapCenter para base de datos SAP HANA
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
Bidireccional
 a| 
Para un tenant único de un contenedor de base de datos multitenant (MDC), el número del puerto termina en 13; para los que no son MDC, el número de puerto termina en 15.

Puede personalizar el número de puerto.



 a| 
Complemento de SnapCenter para PostgreSQL
 a| 
5432
 a| 
 a| 
 a| 
Este puerto es el puerto PostgreSQL predeterminado utilizado para la comunicación del plugin para PostgreSQL con el clúster PostgreSQL.

Puede personalizar el número de puerto.

|===