---
permalink: install/task_import_ca_certificate_to_unix_plugin_hosts.html 
sidebar: sidebar 
keywords: security,authentication,import CA certificates 
summary: Debe importar el certificado de CA a los hosts del plugin de UNIX. 
---
= Importe el certificado de CA en los hosts del plugin UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe importar el certificado de CA a los hosts del plugin de UNIX.

*Acerca de esta tarea*

* Puede gestionar la contraseña del almacén de claves del SPL y el alias de la pareja de claves firmada de CA en uso.
* La contraseña para el almacén de claves SPL y para toda la contraseña de alias asociada de la clave privada deben ser la misma.


* Pasos*

. Puede recuperar la contraseña predeterminada del almacén de claves del SPL desde el archivo de propiedades del SPL. Es el valor correspondiente a la clave `SPL_KEYSTORE_PASS`.
. Cambie la contraseña del almacén de claves:
`$ keytool -storepasswd -keystore keystore.jks`
. Cambie la contraseña para todos los alias de las entradas de clave privada en el almacén de claves por la misma contraseña utilizada para el almacén de claves:
`$ keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
. Actualice lo mismo para la clave spl_KEYSTORE_PASS IN `spl.properties`` archivo.
. Reinicie el servicio después de cambiar la contraseña.

