---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: Puede configurar para registrar los eventos de seguridad de las plataformas de software y todo el software que se ejecuta en dichas plataformas. 
---
= Configure los ajustes del registro de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se generan registros de auditoría para cada una de las actividades del servidor SnapCenter. De forma predeterminada, los registros de auditoría se protegen en la ubicación predeterminada instalada _C:\Program Files\NetApp\SnapCenter WebApp\audit\_.

Los registros de auditoría se protegen mediante la generación de resumen firmados digitalmente para cada uno de los eventos de auditoría para protegerlos de la modificación no autorizada. El resumen generado se mantiene en el archivo de suma de comprobación de auditoría independiente y se realizan comprobaciones de integridad periódicas para garantizar la integridad del contenido.

Inició sesión con el rol de administrador de SnapCenter.

*Acerca de esta tarea*

* Las alertas se envían en las siguientes situaciones:
+
** La programación de comprobación de integridad del registro de auditoría o el servidor de syslog están habilitados o deshabilitados
** Errores en la comprobación de integridad del registro de auditoría, el registro de auditoría o el registro del servidor de syslog
** Poco espacio en disco


* El correo electrónico se envía sólo cuando la comprobación de integridad falla.
* Debe modificar simultáneamente las rutas del directorio de registro de auditoría y del directorio de registro de suma de comprobación de auditoría. Solo no puede modificar uno de ellos.
* Cuando se modifican las rutas del directorio de registro de auditoría y del directorio de registro de suma de comprobación de auditoría, no se puede realizar la comprobación de integridad en los registros de auditoría presentes en la ubicación anterior.
* Las rutas de acceso del directorio de registro de auditoría y del directorio de suma de comprobación de auditoría deben estar en la unidad local del servidor SnapCenter.
+
No se admiten las unidades compartidas o montadas en red.

* Si el protocolo UDP se utiliza en la configuración del servidor de syslog, los errores debido a que el puerto está inactivo o no está disponible no se pueden capturar como un error o una alerta en SnapCenter.
* Puede utilizar los comandos Set-SmAuditSettings y Get-SmAuditSettings para configurar los registros de auditoría.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando Get-Help nombre_comando. Como alternativa, también puede consultar el https://["Guía de referencia de cmdlets de SnapCenter Software"^].



* Pasos*

. En la página *Configuración*, vaya a *Configuración* > *Configuración global* > *Configuración del registro de auditoría*.
. En la sección Registro de auditoría, introduzca los detalles.
. Introduzca el directorio *Registro de auditoría* y el directorio *Registro de suma de comprobación de auditoría*
+
.. Introduzca el tamaño máximo del archivo
.. Introduzca el número máximo de archivos de registro
.. Introduzca el porcentaje de uso de espacio en disco para enviar una alerta


. (Opcional) Activar *Registrar hora UTC*.
. (Opcional) Activar *Comprobación de integridad del registro de auditoría* y hacer clic en *Iniciar comprobación de integridad* para verificación de integridad bajo demanda.
+
También puede ejecutar el comando *Start-SmAuditIntegrityCheck* para iniciar la comprobación de integridad bajo demanda.

. (Opcional) habilite los registros de auditoría reenviados al servidor de syslog remoto e introduzca los detalles del servidor de syslog.
+
Debe importar el certificado del servidor de syslog en la raíz de confianza para el protocolo TLS 1.2.

+
.. Introduzca el host de servidor de syslog
.. Introduzca el puerto del servidor de syslog
.. Introduzca el protocolo de servidor de syslog
.. Introduzca el formato RFC


. Haga clic en *Guardar*.
. Puede ver comprobaciones de integridad de auditoría y de espacio en disco haciendo clic en *Monitor* > *Jobs*.

