---
permalink: install/task_export_snapcenter_certificates.html 
sidebar: sidebar 
keywords: exporting certificates 
summary: Exportar certificados SnapCenter. 
---
= Exportar certificados SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* Pasos*

. Vaya a la consola de administración de Microsoft (MMC) y, a continuación, haga clic en *Archivo* > *Agregar o quitar complemento*.
. En la ventana Agregar o quitar complementos, seleccione *certificados* y, a continuación, haga clic en *Agregar*.
. En la ventana del complemento certificados, seleccione la opción *Mi cuenta de usuario* y, a continuación, haga clic en *Finalizar*.
. Haga clic en *raíz de consola* > *certificados - Usuario actual* > *entidades de certificación raíz de confianza* > *certificados*.
. Haga clic con el botón derecho del ratón en el certificado que tiene el nombre descriptivo de SnapCenter y, a continuación, seleccione *todas las tareas* > *Exportar* para iniciar el asistente de exportación.
. Complete el asistente de la siguiente manera:
+
|===
| En esta ventana del asistente... | Haga lo siguiente... 


 a| 
Exportar clave privada
 a| 
Seleccione la opción *Sí, exporte la clave privada* y, a continuación, haga clic en *Siguiente*.



 a| 
Exportar formato de archivo
 a| 
No realice cambios; haga clic en *Siguiente*.



 a| 
Seguridad
 a| 
Especifique la nueva contraseña que se utilizará para el certificado exportado y, a continuación, haga clic en *Siguiente*.



 a| 
Archivo a exportar
 a| 
Especifique un nombre de archivo para el certificado exportado (debe utilizar .pfx) y, a continuación, haga clic en *Siguiente*.



 a| 
Finalización del Asistente para exportación de certificados
 a| 
Revise el resumen y, a continuación, haga clic en *Finalizar* para iniciar la exportación.

|===


*resultado*

Los certificados se exportan en formato .pfx.
