---
permalink: install/task_configure_CA_client_certificate_for_LDAPS.html 
sidebar: sidebar 
keywords: CA client certificate, LDAPS 
summary: Debe configurar el certificado de cliente de CA para LDAPS en el servidor SnapCenter cuando la LDAPS de Windows con los certificados de CA. 
---
= Configure el certificado de cliente de CA para LDAPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar el certificado de cliente de CA para LDAPS en el servidor SnapCenter cuando la LDAPS de Windows con los certificados de CA.

* Pasos*

. Vaya a la consola de administración de Microsoft (MMC) y, a continuación, haga clic en *Archivo* > *Agregar o quitar Snapin*.
. En la ventana Agregar o quitar complementos, seleccione *certificados* y, a continuación, haga clic en *Agregar*.
. En la ventana del complemento certificados, seleccione la opción *cuenta de equipo* y, a continuación, haga clic en *Finalizar*.
. Haga clic en *raíz de consola* > *certificados – Equipo local* > *entidades de certificación raíz de confianza* > *certificados*.
. Haga clic con el botón secundario en la carpeta “entidades de certificación raíz de confianza” y, a continuación, seleccione *todas las tareas* > *Importar* para iniciar el asistente de importación.
. Complete el asistente de la siguiente manera:
+
|===
| En esta ventana del asistente... | Haga lo siguiente... 


 a| 
En la segunda página del asistente
 a| 
Haga clic en *examinar*, seleccione el _Root Certificate_ y haga clic en *Siguiente*.



 a| 
Finalización del Asistente para importación de certificados
 a| 
Revise el resumen y, a continuación, haga clic en *Finalizar* para iniciar la importación.

|===
. Repita los pasos 5 y 6 para los certificados intermedios.

