---
permalink: install/task_import_ca_certificate_to_windows_plugin_hosts.html 
sidebar: sidebar 
keywords: security,authentication, export CA certificates 
summary: Para usar el certificado de CA de servidor de SnapCenter exportado, es necesario importar el certificado relacionado a los hosts del plugin de Windows de SnapCenter 
---
= Importe el certificado de una entidad de certificación (CA) en los hosts del plugin de Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para usar el certificado de CA de servidor de SnapCenter exportado, es necesario importar el certificado relacionado a los hosts del plugin de Windows de SnapCenter mediante la consola de gestión de Microsoft (MMC).

* Pasos*

. Vaya a la consola de administración de Microsoft (MMC) y, a continuación, haga clic en *Archivo* > *Agregar o quitar Snapin*.
. En la ventana Agregar o quitar complementos, seleccione *certificados* y, a continuación, haga clic en *Agregar*.
. En la ventana Certificados Snap-in, seleccione la opción *Cuenta de computadora* y luego haga clic en *Finalizar*.
. Haga clic en *Console root* > *Certificados - Equipo local* > *Personal* > *Certificados*.
. Haga clic con el botón derecho en la carpeta “Personal” y seleccione *Todas las tareas* > *Importar* para iniciar el asistente de importación.
. Realice las siguientes acciones en el asistente.


|===
| Para esta opción... | Haga lo siguiente... 


 a| 
Ubicación de tienda
 a| 
Haga clic en *Siguiente*.



 a| 
Archivo para importar
 a| 
Seleccione el certificado de servidor SnapCenter que termina con la extensión .cer.



 a| 
Almacén de certificados
 a| 
Haga clic en *Siguiente*.



 a| 
Finalización del Asistente para exportación de certificados
 a| 
Revise el resumen y, a continuación, haga clic en *Finalizar* para iniciar la importación.

|===