---
permalink: install/task_switch_from_nlb_to_f5_for_high_availability.html 
sidebar: sidebar 
keywords: F5, NLB, high availability 
summary: 'Es posible cambiar la configuración de alta disponibilidad de SnapCenter de balanceo de carga de red (NLB) para usar el balanceador de carga F5.' 
---
= Cambie de NLB a F5 para ofrecer alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la configuración de alta disponibilidad de SnapCenter de balanceo de carga de red (NLB) para usar el balanceador de carga F5.

* Pasos*

. Configurar servidores SnapCenter para obtener alta disponibilidad mediante F5. https://["Leer más"^].
. En el host de SnapCenter Server, inicie PowerShell.
. Inicie una sesión con el cmdlet Open-SmConnection y, a continuación, introduzca sus credenciales.
. Actualice el servidor SnapCenter para que apunte a la dirección IP del clúster F5 mediante el cmdlet Update-SmServerCluster.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://["Guía de referencia de cmdlets de SnapCenter Software"^].


