---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: Cree una política de copia de seguridad para los sistemas de archivos Unix de los que desea realizar la copia de seguridad. 
---
= Crear directivas de backup para sistemas de archivos Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar backups de sistemas de archivos Unix, debe crear una política de backup para el recurso o el grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups. También puede especificar la configuración de replicación, script y tipo de backup. Crear una política permite ahorrar tiempo cuando se desea volver a utilizar esa política en otro recurso o grupo de recursos.

.Antes de empezar
* En el marco de los preparativos para la protección de datos, completó tareas como instalar SnapCenter, añadir hosts, detectar sistemas de archivos y crear conexiones con el sistema de almacenamiento.
* Si desea replicar snapshots en un almacenamiento secundario con snapmirror o snapvault, el administrador de SnapCenter debe haberle asignado las SVM de los volúmenes de origen y de destino.
* Revise los requisitos previos y las limitaciones específicos de SnapMirror Active Sync. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Límites de objetos para la sincronización activa de SnapMirror"].


.Acerca de esta tarea
* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
+
Si se especifica un período de bloqueo de Snapshot, se evita la eliminación de las snapshots hasta que caduque el período de retención.  Esto podría llevar a retener un número mayor de instantáneas que el recuento especificado en la política.

+
Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.





.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Seleccione *Unix File Systems* de la lista desplegable.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Backup and Replication, realice las siguientes acciones:
+
.. Especifique la configuración de backup.
.. Especifique la frecuencia de programación seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
.. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:


+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Actualizar SnapMirror tras crear una copia Snapshot local
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de backup en otro volumen (replicación de SnapMirror).

Esta opción debe estar habilitada para la sincronización activa de SnapMirror.



 a| 
Actualizar SnapVault después de crear una copia Snapshot local
 a| 
Seleccione esta opción para realizar una replicación de backup disco a disco (backups de SnapVault).



 a| 
Número de reintentos con error
 a| 
Escriba el número máximo de intentos de replicación que se permitirán antes de que la operación se detenga.

|===
. En la página Retention, especifique la configuración de retención para el tipo de backup y el tipo de programación seleccionados en la página Backup and Replication:
+
|===


| Si desea... | Realice lo siguiente... 


 a| 
Mantenga un cierto número de Snapshots
 a| 
Seleccione *Copias para guardar* y, a continuación, especifique el número de instantáneas que desea conservar.

Si la cantidad de snapshots supera el número especificado, las snapshots se eliminan empezando por las más antiguas.


NOTE: El valor de retención máximo es 1018. Se producirá un error en los backups si la retención se establece en un valor superior a la versión de ONTAP subyacente.


IMPORTANT: Debe establecer el número de retención en 2 o un valor más alto si tiene pensado habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera Snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva Snapshot en el destino.



 a| 
Mantenga los Snapshots durante una cierta cantidad de días
 a| 
Seleccione *Retener copias para* y, a continuación, especifique el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de copia de instantánea
 a| 
Seleccione *Período de bloqueo de copia de instantánea* y especifique la duración en días, meses o años.

El período de retención de SnapLock debe ser inferior a 100 años.

|===
. Seleccione la etiqueta de política.
+

NOTE: Puede asignar etiquetas SnapMirror a instantáneas principales para replicación remota, lo que permite que las instantáneas principales descarguen la operación de replicación de instantáneas de SnapCenter a los sistemas secundarios de ONTAP .  Esto se puede hacer sin habilitar la opción SnapMirror o SnapVault en la página de políticas.

. En la página Script, introduzca la ruta y los argumentos del script previo o script posterior que desea ejecutar antes o después de la operación de backup, según corresponda.
+

NOTE: Debe comprobar si los comandos existen en la lista de comandos disponible en el host del plugin desde la ruta _ /opt/NetApp/SnapCenter/scc/etc/allowed_commands.config_.

+
También puede especificar el valor de tiempo de espera del script. El valor predeterminado es 60 segundos.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

