---
permalink: protect-db2/add-hosts-and-install-plug-in-packages-on-remote-hosts-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: Debe usar la página SnapCenter Add Host para añadir hosts y, a continuación, instalar los paquetes de los plugins. Los plugins se instalan automáticamente en hosts remotos. Puede añadir un host e instalar paquetes de plugins para un host individual o para un clúster. 
---
= Añada hosts e instale paquetes de plugins en hosts remotos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe usar la página SnapCenter Add Host para añadir hosts y, a continuación, instalar los paquetes de los plugins. Los plugins se instalan automáticamente en hosts remotos. Puede añadir un host e instalar paquetes de plugins para un host individual o para un clúster.

.Antes de empezar
* Si el sistema operativo del host de SnapCenter Server es Windows 2019 y el sistema operativo del host del plugin es Windows 2022, debe realizar lo siguiente:
+
** Actualice a Windows Server 2019 (compilación del sistema operativo 17763,5936) o posterior
** Actualice a Windows Server 2022 (compilación del sistema operativo 20348,2402) o posterior


* Debe ser un usuario al que se ha asignado una función que tenga permisos de instalación y desinstalación de plugins, como el rol de administrador de SnapCenter.
* Al instalar un plugin en un host de Windows, si especifica una credencial que no está incorporada o si el usuario pertenece a un usuario de grupo de trabajo local, debe deshabilitar UAC en el host.
* Debe asegurarse de que el servicio de cola de mensajes está en ejecución.
* La documentación de administración contiene información sobre la gestión de los hosts.
* Si está utilizando la cuenta de servicio gestionado en grupo (GMSA), debe configurar GMSA con privilegios administrativos.
+
link:../protect-db2/configure-gMSA-on-windows-server-2012-or-later.html["Configure la cuenta de servicio gestionado de grupo en Windows Server 2016 o posterior para IBM DB2"^]



.Acerca de esta tarea
* No es posible añadir un servidor SnapCenter como host de plugins a otro servidor SnapCenter.


.Pasos
. En el panel de navegación de la izquierda, haga clic en *hosts*.
. Compruebe que la ficha *Managed hosts* está seleccionada en la parte superior.
. Haga clic en *Agregar*.
. En la página hosts, realice las siguientes acciones:
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Tipo de host
 a| 
Seleccione el tipo de host:

** Windows
** Linux
+

NOTE: El plugin para IBM DB2 está instalado en el host de cliente IBM DB2, y este host puede estar en un sistema Windows o Linux.





 a| 
Nombre de host
 a| 
Introduzca el nombre de host de comunicación. Introduzca el nombre de dominio completamente cualificado (FQDN) o la dirección IP del host. SnapCenter depende de una configuración adecuada del DNS. Por lo tanto, lo más recomendable es introducir el FQDN.



 a| 
Credenciales
 a| 
Seleccione el nombre de credencial que ha creado o cree nuevas credenciales. Las credenciales deben tener derechos de administrador en el host remoto. Para obtener más detalles, consulte la información acerca de crear credenciales.

Puede ver detalles sobre las credenciales colocando el cursor sobre el nombre de las credenciales que ha proporcionado.


NOTE: El modo de autenticación de las credenciales se determina por el tipo de host que especifique en el asistente Add host.

|===
. En la sección Select Plug-ins to Install, seleccione los plugins que desea instalar.
+
Mientras utiliza la API DE REST para instalar el plugin para DB2, debe pasar la versión como 3,0. Por ejemplo, DB2:3,0

. (Opcional) haga clic en *más opciones*.
+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Puerto
 a| 
Conserve el número de puerto predeterminado o especifique el número de puerto. El número de puerto predeterminado es 8145. Si el servidor SnapCenter se instaló en un puerto personalizado, ese número de puerto se mostrará como el puerto predeterminado.


NOTE: Si ha instalado plugins manualmente y ha especificado un puerto personalizado, debe especificar el mismo puerto. De lo contrario, la operación dará error.



 a| 
Ruta de instalación
 a| 
El plugin para IBM DB2 está instalado en el host de cliente IBM DB2, y este host puede estar en un sistema Windows o Linux.

** En el caso del paquete de plugins de SnapCenter para Windows, la ruta predeterminada es C:\Program Files\NetApp\SnapCenter. Opcionalmente, puede personalizar la ruta.
** Para el paquete de plugins de SnapCenter para Linux, la ruta predeterminada es /opt/NetApp/snapcenter. Opcionalmente, puede personalizar la ruta.




 a| 
Omitir comprobaciones previas a la instalación
 a| 
Seleccione esta casilla de comprobación si ya ha instalado los plugins manualmente y no desea validar si el host cumple con los requisitos para la instalación del plugin.



 a| 
Utilice Group Managed Service Account (GMSA) para ejecutar los servicios de plug-in
 a| 
En el caso de host de Windows, seleccione esta casilla de comprobación si desea utilizar una cuenta de servicio gestionado de grupo (GMSA) para ejecutar los servicios de plugin.


NOTE: Proporcione el nombre de GMSA con el siguiente formato: Nombre_de_dominio\accountName$.


NOTE: GMSA se utilizará como cuenta de servicio de inicio de sesión solo en el complemento SnapCenter para el servicio de Windows.

|===
. Haga clic en *Enviar*.
+
Si no ha seleccionado la casilla de comprobación Skip prechecks, el host se valida para comprobar si cumple con los requisitos para la instalación del plugin. El espacio en disco, RAM, versión de PowerShell, . La versión de NET, la ubicación (para plugins de Windows) y Java 11 (tanto para plugins de Windows como de Linux) se validan frente a los requisitos mínimos. Si no se satisfacen los requisitos mínimos, se muestran los mensajes de error o advertencia correspondientes.

+
Si el error está relacionado con el espacio en disco o RAM, es posible actualizar el archivo web.config ubicado en C:\Program Files\NetApp\SnapCenter WebApp para modificar los valores predeterminados. Si el error está relacionado con otros parámetros, primero debe solucionar el problema.

+

NOTE: En una configuración de alta disponibilidad, si actualiza el archivo web.config, debe actualizar el archivo en ambos nodos.

. Si el tipo de host es Linux, verifique la huella digital y, a continuación, haga clic en *Confirmar y enviar*.
+
En una configuración de clúster, debe comprobar la huella de cada uno de los nodos del clúster.

+

NOTE: La verificación de huellas digitales es obligatoria aunque se haya añadido anteriormente el mismo host a SnapCenter y se haya confirmado la huella.

. Supervise el progreso de la instalación.
+
** Para el plugin de Windows, los registros de instalación y actualización se encuentran en: _C:\Windows\SnapCenter plugin\Install_<JOBID>\
** Para el plugin de Linux, los registros de instalación se encuentran en: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log y los registros de actualización se encuentran en: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log




.Después de terminar
Si desea actualizar a SnapCenter 6,0 o posterior, el plugin basado en PERL para DB2 existente se desinstala del servidor de plugins remoto.
