---
permalink: protect-db2/clone-ibm-db2-backups-using-powershell-cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: El flujo de trabajo de clonado incluye planificar, realizar la operación de clonado y supervisar la operación. 
---
= Clonar backups de la base de datos IBM DB2 mediante cmdlets de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El flujo de trabajo de clonado incluye planificar, realizar la operación de clonado y supervisar la operación.

Debe haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.

La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].

.Pasos
. Inicie una sesión de conexión con el servidor de SnapCenter para el usuario especificado mediante el cmdlet de Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmConnection
----
. Recupere los backups para realizar la operación de clonado mediante el cmdlet Get-SmBackup.
+
Este ejemplo muestra que hay dos backups disponibles para clonar:

+
[listing]
----
 C:\PS> Get-SmBackup

        BackupId                      BackupName                    BackupTime                    BackupType
        --------                      ----------                    ----------                    ----------
         1                     Payroll Dataset_vise-f6_08... 8/4/2015 11:02:32 AM          Full Backup
         2                     Payroll Dataset_vise-f6_08... 8/4/2015 11:23:17 AM
----
. Inicie una operación de clonado a partir de un backup existente y especifique las direcciones IP de exportación de NFS a las que se van a exportar los volúmenes clonados.
+
Este ejemplo muestra que el backup que se va a clonar tiene una dirección NFSExportIPs de 10.32.212.14:

+
Para la base de datos DB2:

+
[listing]
----
PS C:\> New-SmClone -Resources @{"Host"="10.32.212.13";"Uid"="db2inst1\BOOKS"} -BackupName 'scdb201_gdl_openlab_netapp_local_DB2_db2inst1_BOOKS_scdb201_05-15-2024_00.29.20.1466' -AppPluginCode DB2 -CloneToInstance '10.32.212.14' -CloneInstance db2inst1 -CloneName BOOKS -NFSExportIPs 10.32.212.14
----
+
Para una instancia de DB2:

+
[listing]
----
PS C:\> New-SmClone -Resources @{"Host"="10.32.212.13";"Uid"="DB2"} -BackupName 'scdb201_gdl_openlab_netapp_local_DB2_db2inst1_BOOKS_scdb201_05-15-2024_00.29.20.1466' -AppPluginCode DB2 -CloneToInstance '10.32.212.14' -CloneName Db2 -NFSExportIPs 10.32.212.14
----
+

NOTE: Si no se especificó NFSExportIPs, el valor predeterminado se exporta al host de destino del clon.

. Compruebe que los backups se hayan clonado correctamente mediante el cmdlet Get-SmCloneReport para ver los detalles del trabajo de clonado.
+
Puede ver detalles como el ID del clon, la fecha y hora de inicio, y la fecha y hora de finalización.

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

    SmCloneId           : 1
    SmJobId             : 186
    StartDateTime       : 8/3/2015 2:43:02 PM
    EndDateTime         : 8/3/2015 2:44:08 PM
    Duration            : 00:01:06.6760000
    Status              : Completed
    ProtectionGroupName : Draper
    SmProtectionGroupId : 4
    PolicyName          : OnDemand_Clone
    SmPolicyId          : 4
    BackupPolicyName    : OnDemand_Full_Log
    SmBackupPolicyId    : 1
    CloneHostName       : SCSPR0054212005.mycompany.com
    CloneHostId         : 4
    CloneName           : Draper__clone__08-03-2015_14.43.53
    SourceResources     : {Don, Betty, Bobby, Sally}
    ClonedResources     : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER, Sally_DRAPER}
    SmJobError          :
----

