---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: Antes de usar SnapCenter para realizar un backup de los recursos de la base de datos IBM DB2, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups. 
---
= Crear políticas de backup para IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar SnapCenter para realizar un backup de recursos de IBM DB2, debe crear una política de backup para el recurso o grupo de recursos que desea incluir en el backup. Una política de backup es un conjunto de reglas que rigen cómo gestionar, programar y retener backups.

.Antes de empezar
* Debe tener definida una estrategia de backup.
+
Para obtener detalles, consulte la información sobre cómo definir una estrategia de protección de datos para las bases de datos IBM DB2.

* Debe haberse preparado para la protección de datos completando tareas como instalar SnapCenter, añadir hosts, configurar las conexiones del sistema de almacenamiento y añadir recursos.
* El administrador de SnapCenter debe haberle asignado las instancias de SVM de los volúmenes de origen y de destino en caso de que replique snapshots en un reflejo o almacén.
+
Además, puede definir la configuración de replicación, script y aplicaciones en la política. Estas opciones ahorran tiempo cuando se desea volver a utilizar la política con otro grupo de recursos.



.Acerca de esta tarea
* SnapLock
+
** Si se selecciona la opción 'Retain the backup copies for a specific number of days', el período de retención de SnapLock debe ser menor o igual que los días de retención mencionados.
** Si se especifica un período de bloqueo de instantáneas, se evita la eliminación de las instantáneas hasta que caduque el período de retención. Esto podría provocar que se retenga un número mayor de instantáneas que el recuento especificado en la política.
** Para ONTAP 9.12.1 y versiones anteriores, los clones creados a partir de las instantáneas de almacén de SnapLock como parte de la restauración heredarán el tiempo de caducidad de almacén de SnapLock. El administrador de almacenamiento debe limpiar manualmente los clones después de la hora de caducidad de SnapLock.




.Pasos
. En el panel de navegación de la izquierda, haga clic en *Configuración*.
. En la página Configuración, haga clic en *Directivas*.
. Haga clic en *Nuevo*.
. En la página Name, escriba el nombre de la política y sus detalles.
. En la página Policy type, realice lo siguiente:
+
.. Seleccione el tipo de almacenamiento.
.. En la sección *Configuración de copia de seguridad personalizada*, proporcione cualquier configuración de copia de seguridad específica que tenga que pasarse al plugin en formato de clave-valor.
+
Puede pasar varios pares de clave-valor al plugin.



. En la página Snapshot and Replication, realice las siguientes acciones.
+
.. Especifique la frecuencia de programación seleccionando *a petición*, *hora*, *Diario*, *Semanal* o *Mensual*.
+

NOTE: Puede especificar la programación (fecha de inicio, fecha de finalización y frecuencia) para la operación de backup mientras crea un grupo de recursos. Esto le permite crear grupos de recursos que comparten la misma política y frecuencia de backup, pero también le permite asignar diferentes programaciones de backup a cada política.

+

NOTE: Si ha programado para las 2:00 a.m., la programación no se activará durante el horario de verano.

.. En la sección Snapshot settings, realice las siguientes acciones:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Conserve un cierto número de instantáneas
 a| 
Seleccione *Copias para mantener* y, a continuación, especifique el número de instantáneas que desea conservar.

Si la cantidad de copias de Snapshot supera el número especificado, las copias de Snapshot se eliminan empezando por las más antiguas.



 a| 
Mantenga los Snapshots durante una cierta cantidad de días
 a| 
Seleccione *Retener copias para* y, a continuación, especifique el número de días durante los cuales desea conservar las instantáneas antes de eliminarlas.



 a| 
Período de bloqueo de la copia snapshot primaria
 a| 
Si desea especificar el período de bloqueo de snapshot del primario, seleccione Snapshot copy locking period y seleccione days, months o years.

El período de retención de SnapLock debe ser inferior a 100 años.



 a| 
Período de bloqueo de instantánea secundaria
 a| 
Seleccione *Periodo de bloqueo de copia de instantánea secundaria* y seleccione Días, Meses o Años.

Para que esta opción sea efectiva, debe realizar las siguientes tareas:

*** Seleccione el *Periodo de bloqueo de copia de instantánea primaria*.
*** Seleccione una de las opciones de replicación secundaria o ambas.


|===
+

IMPORTANT: Para los backups basados en copias de Snapshot, debe establecer el número de retención en 2 o más si va a habilitar la replicación de SnapVault. Si establece el número de retención en 1, la operación puede generar un error, ya que la primera snapshot es la de referencia para la relación de SnapVault hasta que se replica una nueva snapshot en el destino.

.. Seleccione una etiqueta de Snapshot.
+
Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+

NOTE: Si ha seleccionado *Actualizar SnapMirror después de crear una copia Snapshot local*, puede especificar opcionalmente la etiqueta de la directiva secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.



. En la sección Select secondary replication options, seleccione una de las siguientes opciones de replicación secundaria o ambas:
+

NOTE: Debe seleccionar las opciones de replicación secundarias para que el *Periodo de bloqueo de copia de instantánea secundaria* sea efectivo.

+
|===
| Para este campo... | Realice lo siguiente... 


 a| 
Actualizar SnapMirror tras crear una copia Snapshot local
 a| 
Seleccione este campo para crear copias reflejadas de los conjuntos de backup en otro volumen (replicación de SnapMirror).

Esta opción debe estar habilitada para la sincronización activa de SnapMirror.



 a| 
Actualizar SnapVault después de crear una copia Snapshot local
 a| 
Seleccione esta opción para realizar una replicación de backup disco a disco (backups de SnapVault).



 a| 
Etiqueta de la política secundaria
 a| 
Seleccione una etiqueta de Snapshot.

+ Según la etiqueta de Snapshot que seleccione, ONTAP aplicará la política de retención de Snapshot secundaria que corresponda a esa etiqueta.

+ NOTA: Si ha seleccionado *Actualizar SnapMirror después de crear una copia instantánea local*, puede especificar opcionalmente la etiqueta de la política secundaria. Sin embargo, si ha seleccionado *Actualizar SnapVault después de crear una copia Snapshot local*, debe especificar la etiqueta de la directiva secundaria.



 a| 
Número de reintentos con error
 a| 
Escriba el número máximo de intentos de replicación que se permitirán antes de que la operación se detenga.

|===
+

NOTE: Debe configurar la política de retención de SnapMirror en ONTAP para el almacenamiento secundario a fin de evitar que se alcance el límite máximo de Snapshots en el almacenamiento secundario.

. Revise el resumen y, a continuación, haga clic en *Finalizar*.

