---
permalink: protect-db2/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Es necesario crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar cmdlets de PowerShell para realizar backup, restaurar o clonar bases de datos IBM DB2.' 
---
= Cree una conexión del sistema de almacenamiento y una credencial mediante cmdlets de PowerShell para IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es necesario crear una conexión de máquina virtual de almacenamiento (SVM) y una credencial antes de usar cmdlets de PowerShell para realizar backup, restaurar o clonar bases de datos IBM DB2.

.Antes de empezar
* Debe haber preparado el entorno de PowerShell para ejecutar los cmdlets de PowerShell.
* Debe tener los permisos necesarios en el rol de administrador de infraestructura para crear conexiones de almacenamiento.
* Debe asegurarse de que no se encuentren en curso las instalaciones de plugins.
+
No debe haber instalaciones de complementos de host en curso al añadir una conexión a sistemas de almacenamiento, ya que puede que la caché del host no se actualice y que el estado de las bases de datos pueda aparecer en la interfaz gráfica de usuario de SnapCenter como «'no disponible para el backup' o «'no en el almacenamiento de NetApp'».

* Los nombres de los sistemas de almacenamiento deben ser únicos.
+
SnapCenter no admite varios sistemas de almacenamiento con el mismo nombre en clústeres diferentes. Cada uno de los sistemas de almacenamiento que admite SnapCenter debe tener un nombre único y una dirección IP de LIF de datos única.



.Pasos
. Haga clic en *SnapCenterPS* para iniciar PowerShell Core.
. Cree una nueva conexión con el sistema de almacenamiento mediante el cmdlet Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Cree una credencial nueva mediante el cmdlet Add-SmCredential.
+
Este ejemplo muestra cómo crear una nueva credencial llamada FinanceAdmin con las credenciales de Windows:

+
[listing]
----
PS C:\> Add-SmCredential -Name 'FinanceAdmin' -Type Linux -AuthenticationType PasswordBased -Credential db2hostuser -EnableSudoPrevileges:$true
----
. Agregue el host de comunicación IBM DB2 al servidor SnapCenter.
+
Para Linux:

+
[listing]
----
PS C:\> Add-SmHost -HostType Linux -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
+
Para Windows:

+
[listing]
----
PS C:\> Add-SmHost -HostType Windows -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
. Instale el paquete y el plugin de SnapCenter para IBM DB2 en el host.
+
Para Linux:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2
----
+
Para Windows:

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2,SCW
----
. Defina la ruta de acceso a SQLLIB.
+
Para Windows, el plugin DB2 utilizará la ruta predeterminada para la carpeta SQLLIB: “C:\Program Files\IBM\SQLLIB\BIN”

+
Si desea anular la ruta predeterminada, utilice el comando siguiente.

+
[listing]
----
PS C:\> Set-SmConfigSettings -Plugin -HostName '10.232.204.61' -PluginCode DB2 -configSettings @{"DB2_SQLLIB_CMD"="<custom_path>\IBM\SQLLIB\BIN"}

----


La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].
