---
permalink: protect-db2/prerequisites-for-using-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for IBM Db2 
summary: Antes de utilizar el plugin de SnapCenter para IBM DB2, el administrador de SnapCenter debe instalar y configurar el servidor SnapCenter y llevar a cabo las tareas de requisitos previos. 
---
= Requisitos previos para usar el plugin de SnapCenter para IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de utilizar el plugin de SnapCenter para IBM DB2, el administrador de SnapCenter debe instalar y configurar el servidor SnapCenter y llevar a cabo las tareas de requisitos previos.

* Instalar y configurar SnapCenter Server.
* Inicie sesión en el servidor SnapCenter.
* Configure el entorno de SnapCenter añadiendo conexiones con el sistema de almacenamiento y creando credenciales, si es necesario.
* Instala Java 17 (Oracle Java u OpenJDK) para SnapCenter 6.2.1 y versiones posteriores o
* Java 11 para SnapCenter 6.2 y anteriores en tu host Linux o Windows.
+
Debe configurar la ruta de Java en la variable de rutas del entorno del equipo host.

* Configure SnapMirror y SnapVault si quiere realizar una replicación de backup.

