---
permalink: protect-db2/snapcenter-plug-in-for-ibm-db2-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: El plugin de SnapCenter para IBM DB2 es un componente en el lado del host de NetApp SnapCenter Software que permite la gestión de protección de datos para aplicaciones de bases de datos IBM DB2. El plugin para bases de datos de IBM DB2 automatiza el backup, la restauración y la clonado de bases de datos de IBM DB2 en el entorno de SnapCenter. 
---
= Información general sobre el plugin de SnapCenter para IBM DB2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El plugin de SnapCenter para bases de datos de IBM DB2 es un componente del lado del host de NetApp SnapCenter Software que permite la gestión de protección de datos para aplicaciones de bases de datos IBM DB2. El plugin para bases de datos de IBM DB2 automatiza el backup, la restauración y la clonado de bases de datos de IBM DB2 en el entorno de SnapCenter.

SnapCenter admite configuraciones DB2 de instancia única y de varias instancias. Es posible utilizar el plugin para base de datos de IBM DB2 en entornos Linux y Windows. En entornos Windows, se admitirá DB2 como recurso manual.

Cuando se instala el plugin para bases de datos de IBM DB2, es posible utilizar SnapCenter con la tecnología SnapMirror de NetApp para crear copias de reflejo de conjuntos de backups en otro volumen. También es posible utilizar el plugin con la tecnología SnapVault de NetApp para realizar replicaciones de backup disco a disco para cumplimiento de normativas.

El complemento SnapCenter para DB2 es compatible con NFS y SAN en distribuciones de almacenamiento de archivos de ONTAP y Azure NetApp.

No se admite la distribución de almacenamiento virtual o VMDK.
