---
permalink: protect-db2/types-of-restore-strategies-supported-for-manually-added-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter. Existen dos tipos de estrategias de restauración para los recursos de IBM DB2 agregados manualmente. No se pueden recuperar recursos de IBM DB2 añadidos manualmente. 
---
= Estrategias de restauración para recursos de IBM Db2 añadidos manualmente en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter. Existen dos tipos de estrategias de restauración para los recursos de IBM DB2 agregados manualmente.


NOTE: No se pueden recuperar recursos de IBM DB2 añadidos manualmente.



[[complete-resource-restore]]
== Restauración de recursos completa

* Restaura todos los volúmenes, qtrees y LUN de un recurso



NOTE: Si el recurso contiene volúmenes o qtrees, las copias de Snapshot tomadas después de la copia de Snapshot seleccionada para restaurar en los volúmenes o qtrees se eliminan y no pueden recuperarse. Además, si hay algún otro recurso alojado en los mismos volúmenes o qtrees, también se lo elimina.
