---
permalink: protect-nsp/what_you_can_do_with_the_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins 
summary: Es posible usar los plugins compatibles con NetApp para las operaciones de protección de datos. 
---
= Tareas que pueden llevarse a cabo con los complementos y complementos de almacenamiento compatibles con NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar el plugin compatible con NetApp para las operaciones de protección de datos.

*NetApp soporta plug-ins*

* Añadir recursos como bases de datos, instancias, documentos o espacios de tablas.
* Crear backups.
* Restaurar desde backups.
* Clonar backups.
* Programar operaciones de backup.
* Supervisar operaciones de backup, de restauración y de clonado.
* Ver informes para operaciones de backup, restauración y clonado.


*Complemento de almacenamiento*

Es posible usar el plugin de almacenamiento para operaciones de protección de datos.

* Realice copias Snapshot de grupo de coherencia de los volúmenes de almacenamiento en los clústeres de ONTAP.
* Realice copias de seguridad de aplicaciones personalizadas mediante el marco incorporado de secuencias de comandos previas y posteriores
+
Es posible realizar backups de un volumen de ONTAP, LUN o un qtree.

* Actualice las snapshots creadas del almacenamiento primario a un secundario de ONTAP aprovechando la relación de replicación existente (SnapVault/SnapMirror/replicación unificada) mediante la normativa de SnapCenter
+
ONTAP principal y secundario puede ser ONTAP FAS, AFF, cabina All SAN (ASA), Select o Cloud ONTAP.

* Recupere volúmenes, LUN o archivos ONTAP completos.
+
Debe proporcionar la ruta de archivo correspondiente manualmente, ya que las funciones de exploración o indexación no están integradas en el producto.

+
No se admite la restauración de qtree o directorio, pero solo se puede clonar y exportar el qtree si el alcance de backup se define en el nivel de Qtree.


