---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: Las credenciales utilizan métodos de autenticación diferentes según la aplicación o el entorno. Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter. Debe crear un conjunto de credenciales para instalar plugins y otros conjuntos para operaciones de protección de datos. 
---
= Métodos de autenticación para las credenciales de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las credenciales utilizan métodos de autenticación diferentes según la aplicación o el entorno. Las credenciales autentican a los usuarios para que puedan realizar operaciones de SnapCenter. Debe crear un conjunto de credenciales para instalar plugins y otro para operaciones de protección de datos.



== Autenticación de Windows

El método de autenticación de Windows autentica de acuerdo con Active Directory. Para la autenticación de Windows, se configura Active Directory fuera de SnapCenter. SnapCenter autentica sin configuración adicional. Es necesario contar con credenciales de Windows para añadir hosts, instalar paquetes de plugins y programar trabajos.



== Autenticación de dominio que no es de confianza

SnapCenter permite que los usuarios y grupos que pertenecen a dominios que no son de confianza creen credenciales de Windows. Para que la autenticación se complete correctamente, debe registrar los dominios que no son de confianza en SnapCenter.



== Autenticación de grupo de trabajo local

SnapCenter permite la creación de credenciales de Windows con grupos y usuarios de grupo de trabajo local. La autenticación de Windows para los grupos y usuarios de grupos de trabajo locales no se produce durante la creación de las credenciales de Windows, pero se aplaza hasta que se realizan el registro del host y otras operaciones del host.



== Autenticación de SQL Server

El método de autenticación de SQL se verifica de acuerdo con una instancia de SQL Server. Esto significa que debe detectarse una instancia de SQL Server en SnapCenter. Por lo tanto, antes de añadir una credencial de SQL, debe añadir un host, instalar paquetes de plugins y actualizar los recursos. Necesita la autenticación de SQL Server para realizar operaciones, como programar en SQL Server o detectar recursos.



== Autenticación de Linux

El método de autenticación de Linux autentica con un host Linux. Necesita la autenticación de Linux durante el paso inicial de añadir el host Linux e instalar el paquete de plugins de SnapCenter para Linux de forma remota desde la interfaz gráfica de usuario de SnapCenter.



== Autenticación AIX

El método de autenticación AIX autentica con un host AIX. Necesita la autenticación de AIX durante el paso inicial de añadir el host AIX e instalar el paquete de plugins de SnapCenter para AIX de forma remota desde la interfaz gráfica de usuario de SnapCenter.



== Autenticación de base de datos de Oracle

El método de autenticación de base de datos de Oracle autentica con una base de datos de Oracle. Necesita una autenticación de base de datos de Oracle para realizar operaciones en la base de datos de Oracle si la autenticación de sistema operativo (SO) está deshabilitada en el host de bases de datos. Por lo tanto, antes de añadir una credencial de base de datos de Oracle, debe crear un usuario de Oracle en la base de datos de Oracle con Privileges de sysdba.



== Autenticación de Oracle ASM

El método de autenticación de Oracle ASM autentica con una instancia de Oracle Automatic Storage Management (ASM). Si necesita acceder a una instancia de Oracle ASM y la autenticación del sistema operativo está deshabilitada en el host de base de datos, es necesaria la autenticación de Oracle ASM. Antes de agregar una credencial de Oracle ASM, cree un usuario oracle con SYSTEM Privileges en la instancia de ASM.



== Autenticación de catálogo de RMAN

El método de autenticación de catálogo de RMAN autentica con la base de datos de catálogos de Oracle Recovery Manager (RMAN). Si configuró un mecanismo de catálogo externo y registró la base de datos en la base de datos de catálogos, debe añadir una autenticación de catálogo de RMAN.
