---
permalink: get-started/rbac-snapcenter.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions, application-level RBAC, ONTAP permissions, default snapcenter roles, ONTAP permissions, SnapCenter Admin role 
summary: El RBAC de SnapCenter y los permisos de ONTAP permiten que los administradores de SnapCenter creen roles y establezcan permisos de acceso. Este acceso con gestión central otorga a los administradores de aplicaciones la posibilidad de trabajar con seguridad dentro de entornos delegados. 
---
= Control de acceso basado en roles en SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El control de acceso basado en roles (RBAC) de SnapCenter y los permisos de ONTAP permiten a los administradores de SnapCenter asignar acceso a recursos a usuarios o grupos.  Este acceso administrado centralmente permite a los administradores de aplicaciones trabajar de forma segura dentro de entornos designados.

Debe crear o modificar roles y agregar acceso a recursos a los usuarios.  Al configurar SnapCenter por primera vez, agregue usuarios o grupos de Active Directory a los roles y asigne recursos a esos usuarios o grupos.


NOTE: SnapCenter no crea cuentas de usuarios o grupos.  Crear cuentas de usuario o grupo en el Directorio Activo del sistema operativo o de la base de datos.



== Tipos de RBAC en SnapCenter

SnapCenter admite los siguientes tipos de control de acceso basado en roles:

* RBAC de SnapCenter
* RBAC en el nivel de aplicaciones
* Control de acceso basado en roles del plugin de SnapCenter para VMware vSphere
* Permisos de ONTAP




=== RBAC de SnapCenter

SnapCenter tiene roles predefinidos y usted puede asignar usuarios o grupos a estos roles.

* SnapCenter Admin
* App Backup and Clone Admin
* Backup and Clone Viewer
* Infrastructure Admin


Cuando se asigna un rol a un usuario, SnapCenter muestra los trabajos que son relevantes para ese usuario en la página Trabajos, a menos que el usuario tenga el rol SnapCenterAdmin.

También es posible crear nuevos roles y gestionar los permisos y los usuarios. Es posible asignar permisos a usuarios o grupos para que tengan acceso a objetos de SnapCenter, como hosts, conexiones de almacenamiento y grupos de recursos.

Se pueden asignar permisos de RBAC a usuarios y grupos dentro del mismo bosque y a usuarios de distintos bosques. No es posible asignar permisos de RBAC a usuarios que pertenecen a grupos anidados en diferentes bosques.


NOTE: Al crear un rol personalizado, asegúrese de que incluya todos los permisos del rol SnapCenterAdmin.  Si copia solo algunos permisos, SnapCenter le impedirá realizar todas las operaciones.

Los usuarios deben autenticarse al iniciar sesión a través de la interfaz de usuario o los cmdlets de PowerShell.  Si los usuarios tienen varios roles, seleccionan un rol después de iniciar sesión. También se requiere autenticación para ejecutar API.



=== RBAC en el nivel de aplicaciones

SnapCenter usa credenciales para verificar que los usuarios de SnapCenter autorizados también tengan permisos en el nivel de aplicaciones.

Por ejemplo, para realizar operaciones de protección de datos en un entorno de SQL Server, configure las credenciales de Windows o SQL correctas.  Si desea realizar operaciones de protección de datos en un entorno de sistema de archivos de Windows en el almacenamiento ONTAP , el rol de administrador de SnapCenter debe tener privilegios de administrador en el host de Windows.

De manera similar, si desea realizar operaciones de protección de datos en una base de datos Oracle y si la autenticación del sistema operativo (SO) está deshabilitada en el host de la base de datos, debe configurar las credenciales con la base de datos Oracle o las credenciales de Oracle ASM.  El servidor SnapCenter autentica las credenciales establecidas utilizando uno de estos métodos según la operación.



=== Control de acceso basado en roles del plugin de SnapCenter para VMware vSphere

Cuando se utiliza el plugin de SnapCenter VMware para protección de datos coherente con máquinas virtuales, vCenter Server ofrece un nivel adicional de control de acceso basado en roles. El plugin de VMware de SnapCenter es compatible con el control de acceso basado en roles de vCenter Server y de ONTAP. https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["Más información"^]

NOTA: NetApp recomienda crear una función de ONTAP para las operaciones del SnapCenter Plug-in for VMware vSphere y asignarle todos los privilegios necesarios.



=== Permisos de ONTAP

Debe crear una cuenta vsadmin con los permisos necesarios para acceder al sistema de almacenamiento.link:../install/task_add_a_user_or_group_and_assign_role_and_assets.html["Más información"]



== Permisos asignados a los roles predefinidos de SnapCenter

Cuando agrega un usuario a un rol, asigne el permiso StorageConnection para habilitar la comunicación de la máquina virtual de almacenamiento (SVM) o asigne una SVM al usuario para otorgarle permiso para usar la SVM.  El permiso de Conexión de almacenamiento permite a los usuarios crear conexiones SVM.

Por ejemplo, un administrador de SnapCenter puede crear conexiones SVM y asignarlas a usuarios administradores de App Backup y Clone, quienes no pueden crear ni editar conexiones SVM.  Sin una conexión SVM, los usuarios no pueden realizar operaciones de copia de seguridad, clonación o restauración.



=== SnapCenter Admin

El rol SnapCenter Admin tiene todos los permisos habilitados. No es posible modificar los permisos de este rol. Se pueden agregar usuarios y grupos al rol o quitarlos.



=== App Backup and Clone Admin

El rol App Backup and Clone Admin tiene los permisos necesarios para ejecutar acciones administrativas para tareas vinculadas con el backup y la clonado de aplicaciones. Este rol no tiene permisos para gestión de hosts, aprovisionamiento, gestión de conexiones de almacenamiento o instalación remota.

|===
| Permisos | Activado | Cree | Lea | Actualizar | Eliminar 


 a| 
Grupo de recursos
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Política
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Backup
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Host
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Conexión de almacenamiento
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Clonar
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Provisionamiento
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Consola
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Leídos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Recurso
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Instalar/desinstalar plugins
 a| 
No
 a| 
No aplicable
 a| 
 a| 
No aplicable
 a| 
No aplicable



 a| 
Migración
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Montaje
 a| 
Sí
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Desmontar
 a| 
Sí
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar volumen completo
 a| 
No
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Protección secundaria
 a| 
No
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Monitor de trabajos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable

|===


=== Backup and Clone Viewer

La función Visor de copias de seguridad y clones tiene una vista de solo lectura de todos los permisos.  Esta función también tiene permisos habilitados para descubrimiento, informes y acceso al Panel de Control.

|===
| Permisos | Activado | Cree | Lea | Actualizar | Eliminar 


 a| 
Grupo de recursos
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Política
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Backup
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Host
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Conexión de almacenamiento
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Clonar
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Provisionamiento
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Consola
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Leídos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar
 a| 
No
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Recurso
 a| 
No
 a| 
No
 a| 
Sí
 a| 
Sí
 a| 
No



 a| 
Instalar/desinstalar plugins
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Migración
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Montaje
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Desmontar
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar volumen completo
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Protección secundaria
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Monitor de trabajos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable

|===


=== Infrastructure Admin

El rol Infrastructure Admin tiene permisos habilitados para gestión de hosts, administración del almacenamiento, aprovisionamiento, grupos de recursos, informes de instalación remota, Y acceso a la consola.

|===
| Permisos | Activado | Cree | Lea | Actualizar | Eliminar 


 a| 
Grupo de recursos
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Política
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Backup
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Host
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Conexión de almacenamiento
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Clonar
 a| 
No aplicable
 a| 
No
 a| 
Sí
 a| 
No
 a| 
No



 a| 
Provisionamiento
 a| 
No aplicable
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Consola
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Leídos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Recurso
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



 a| 
Instalar/desinstalar plugins
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Migración
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Montaje
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Desmontar
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Restaurar volumen completo
 a| 
No
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Protección secundaria
 a| 
No
 a| 
No
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable



 a| 
Monitor de trabajos
 a| 
Sí
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable
 a| 
No aplicable

|===