---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: Debe conocer cuáles son los sistemas de almacenamiento, las aplicaciones y las bases de datos compatibles. 
---
= Aplicaciones y sistemas de almacenamiento compatibles con SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe conocer los sistemas de almacenamiento, aplicaciones y bases de datos que admite SnapCenter.



== Sistemas de almacenamiento compatibles

* NetApp ONTAP 9.12.1 y versiones posteriores
* Azure NetApp Files
* Amazon FSX para ONTAP de NetApp
+
Admite memoria no volátil rápida (NVMe) con protocolo de control de transporte (TCP).

+
Para obtener más información sobre Amazon FSX para ONTAP de NetApp, consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentación de Amazon FSX para ONTAP de NetApp"^].

* Sistemas R2 de NetApp ASA que ejecutan NetApp ONTAP 9.16.1.




== Aplicaciones y bases de datos compatibles

SnapCenter admite la protección de distintas aplicaciones y bases de datos. Para obtener información detallada sobre las aplicaciones y bases de datos soportadas, consulte https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].

SnapCenter admite la protección de las cargas de trabajo de Oracle y Microsoft SQL en entornos de centro de datos definido por software (SDDC) de VMware Cloud on Amazon Web Services (AWS). https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["Más información"^].
