---
permalink: uninstall/task_uninstalling_windows_plug_ins_using_the_command_line_interface_on_the_snapcenter_server_host.html 
sidebar: sidebar 
keywords: uninstall, windows plug-ins, powershell cmdlet 
summary: Puede desinstalar plugins individuales o desinstalar paquetes de plugins enteros de uno o más hosts por medio del cmdlet Uninstall-SmHostPackage en la interfaz de línea de comandos del host de SnapCenter Server. 
---
= Desinstale los plugins de Windows mediante el cmdlet de PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desinstalar plugins individuales o desinstalar paquetes de plugins enteros de uno o más hosts por medio del cmdlet _Uninstall-SmHostPackage_ en la interfaz de línea de comandos del host de SnapCenter Server.

Es necesario que previamente haya iniciado sesión en SnapCenter como usuario de dominio con derechos de administrador local en cada host del que desee desinstalar los plugins.

* Pasos*

. Inicie PowerShell.
. En el host del servidor SnapCenter, introduzca el comando: _Open-SMConnection -SMSbaseUrl \https://SNAPCENTER_SERVER_NAME/DOMAIN_NAME_ y, a continuación, introduzca sus credenciales.
. Desinstale los plugins de Windows mediante el cmdlet _Uninstall-SmHostPackage_ y los parámetros necesarios.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar el https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205["Guía de referencia de cmdlets de SnapCenter Software"^].


