---
permalink: uninstall/task_uninstall_plug_ins_from_a_host_using_the_snapcenter_gui.html 
sidebar: sidebar 
keywords: uninstall, gui 
summary: Cuando decide que ya no requiere un plugin individual o un paquete de plugins, puede desinstalarlo por medio de la interfaz de SnapCenter. 
---
= Desinstale plugins mediante la interfaz gráfica de usuario de SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando decide que ya no requiere un plugin individual o un paquete de plugins, puede desinstalarlo por medio de la interfaz de SnapCenter.

*Lo que necesitará*

* Primero debe quitar los grupos de recursos correspondientes al paquete de plugins que vaya a desinstalar.
* Tiene que desconectar las políticas asociadas a los grupos de recursos correspondientes al paquete de plugins que vaya a desinstalar.


*Acerca de esta tarea*

Puede desinstalar plugins individuales. Por ejemplo, quizás necesite desinstalar el plugin de SnapCenter para Microsoft SQL Server porque un host se está quedando sin recursos y quiere moverlo a un host más potente. También puede desinstalar paquetes de plugins enteros. Por ejemplo, quizás necesite desinstalar el paquete de plugins de SnapCenter para Linux, que incluye el plugin de SnapCenter para base de datos de Oracle y el plugin de SnapCenter para UNIX.

* La operación de quitar un host implica desinstalar todos los plugins.
+
Cuando quita un host de SnapCenter, SnapCenter desinstalará todos los paquetes de plugins que haya en el host antes de quitar el host.

* La interfaz gráfica de usuario de SnapCenter quita los plugins de cada host uno por uno.
+
Si utiliza la interfaz gráfica de usuario de SnapCenter, solamente puede desinstalar los plugins de un host cada vez. Sin embargo, puede tener varias operaciones de desinstalación que se ejecuten simultáneamente.

+
También puede desinstalar un plugin de varios hosts mediante el cmdlet _Uninstall-SmHostPackage_ y los parámetros requeridos. La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Como alternativa, también puede consultar la https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["Guía de referencia de cmdlets de SnapCenter Software"^].




IMPORTANT: Desinstalar el paquete de plugins de SnapCenter para Windows de un host donde esté instalado el servidor SnapCenter dañará la instalación de SnapCenter Server. No desinstale el paquete de plugins de SnapCenter para Windows a menos que tenga la seguridad de que ya no requiere SnapCenter Server.

* Pasos*

. En el panel de navegación de la izquierda, haga clic en *hosts*.
. En la página hosts, haga clic en *Managed hosts*.
. En la página Managed hosts, seleccione el host desde el cual desea desinstalar el plugin o paquete de plugins.
. Junto al complemento que desea eliminar, haga clic en *Quitar* > *Enviar*.


*Después de terminar*

Debe esperar 5 minutos antes de reinstalar el plugin en ese host. Este periodo es suficiente para que la interfaz gráfica de usuario de SnapCenter actualice el estado del host gestionado. Si procede a reinstalar de inmediato el plugin, la instalación no se desarrollará correctamente y provocará un error.

Si va a desinstalar el paquete de plugins de SnapCenter para Linux, los archivos de registro específicos de la desinstalación están disponibles en: _/custom_location/snapcenter/log_.
