---
permalink: release-notes/upgrade-path.html 
sidebar: sidebar 
keywords: upgrade paths, supported, upgrade to SnapCenter 
summary: Las rutas de actualización compatibles con SnapCenter. 
---
= Rutas de actualización admitidas para SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La ruta de actualización le ayuda a comprender desde qué versiones anteriores de SnapCenter puede actualizar a las versiones más recientes de SnapCenter y qué versiones de los plugins son compatibles.

|===
| Si se encuentra en la versión de SnapCenter Server... | Puede actualizar directamente el servidor de SnapCenter a... | Versiones de plugins compatibles 


.2+| 4,9 | 5,0  a| 
* 4,9
* 5,0




| 6,0  a| 
* 6,0




.2+| 5,0  a| 
6,0
 a| 
* 5,0
* 6,0




| 6.0.1  a| 
* 6.0.1




| 6,0 | 6.0.1  a| 
* 6,0
* 6.0.1


|===

IMPORTANT: Por ejemplo, si utiliza la versión de SnapCenter 4,9 y quiere actualizar a la versión 6,0.1, primero debe actualizar a la versión 5,0 y, a continuación, realizar una actualización gradual a la versión 6,0.1.

Para obtener información sobre cómo actualizar el plugin de SnapCenter para VMware vSphere, consulte https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade.html["Actualice el plugin de SnapCenter para VMware vSphere"^].
