---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: La versión 6.0.1 del software SnapCenter incluye varias funciones y mejoras nuevas. 
---
= Novedades del software SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versión 6.0.1 del software SnapCenter incluye varias funciones y mejoras nuevas.

|===
| Actualizar | Descripción 


| link:https://docs.netapp.com/us-en/snapcenter/protect-azure/protect-applications-azure-netapp-files.html["Compatibilidad con backups de Azure NetApp Files"]  a| 
Ahora puede utilizar SnapCenter para realizar backups y clonar aplicaciones que residen en Azure NetApp Files en Azure Blob Storage (almacén de objetos).



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Compatibilidad con alta disponibilidad de SnapCenter ejecutándose en Linux"]  a| 
La compatibilidad con la configuración de alta disponibilidad para SnapCenter se amplía ahora a los sistemas Linux. Puede utilizar los equilibradores de carga estándar para esta configuración:

* Equilibrador de carga F5
* NLB = Balanceador de carga de red de Microsoft
* Amazon Web Services (AWS)
* Equilibrio de carga elástico (ELB)
* Equilibrador de carga de Azure




| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Capacidad de gestionar las tareas de backup programadas"]  a| 
Ahora puede establecer un umbral para que los trabajos programados controlen el número de copias de seguridad que desea ejecutar en un momento determinado según la configuración del hardware del sistema.



| link:https://docs.netapp.com/us-en/snapcenter/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Capacidad para gestionar trabajos obsoletos"]  a| 
Ahora puede configurar una programación predefinida para limpiar los trabajos obsoletos que se hayan detenido durante más de 72 horas.



| Funcionalidad de protección de datos incluida para IBM DB2, aplicación de Oracle y plugin de almacenamiento que se ejecutan en AIX  a| 
Es compatible con la protección de datos de IBM DB2, aplicación de Oracle y plugin de almacenamiento que se ejecutan en AIX.

|===