---
permalink: 'release-notes/what"s-new-in-snapcenter601.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0.1 
summary: La versión 6.0.1 del software SnapCenter incluye varias funciones y mejoras nuevas. 
---
= Novedades del software SnapCenter 6.0.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versión 6.0.1 del software SnapCenter incluye varias funciones y mejoras nuevas.

|===
| Actualizar | Descripción 


| link:https://review.docs.netapp.com/us-en/snapcenter_sc601_oct2024_releasebranch/protect-azure/protect-applications-azure-netapp-files.html["Compatibilidad con backups de Azure NetApp Files"]  a| 
SnapCenter admite la función de backup de Azure NetApp Files, que amplía las funcionalidades de protección de datos de Azure NetApp Files al proporcionar una solución de backup totalmente gestionada para la recuperación, el archivado y el cumplimiento de normativas a largo plazo.



| link:hhttps://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Compatibilidad con alta disponibilidad de SnapCenter ejecutándose en Linux"]  a| 
Configure la alta disponibilidad en SnapCenter ejecutándose en Windows o Linux usando el balanceador de carga de F5 GbE, el balanceo de carga de red (NLB) de Microsoft, Elastic Load Balancing (ELB) de Amazon Web Services (AWS) o el balanceador de carga de Azure.



| link:https://review.docs.netapp.com/us-en/snapcenter_sc601_oct2024_releasebranch/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-scheduled-backup-jobs["Soporte para gestionar las tareas de backup programadas"]  a| 
Permite definir un umbral para el número de trabajos programados que se pueden ejecutar en un momento determinado. Esto le permite controlar el número de copias de seguridad que desea ejecutar en función de la configuración de hardware de su sistema.



| link:https://review.docs.netapp.com/us-en/snapcenter_sc601_oct2024_releasebranch/admin/concept_monitor_jobs_schedules_events_and_logs.html#manage-stale-jobs["Soporte para la gestión de trabajos obsoletos"]  a| 
Permite limpiar los trabajos obsoletos que están atascados durante más de 72 horas.



| Compatibilidad con IBM DB2, aplicación de Oracle y plugin de almacenamiento en AIX  a| 
Admite la protección de datos de IBM DB2, aplicaciones de Oracle y el plugin de almacenamiento en AIX

|===