---
permalink: 'release-notes/what"s-new-in-snapcenter61.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.2 
summary: La versión 6,1 del software SnapCenter incluye varias funciones y mejoras nuevas. 
---
= Novedades del SnapCenter software 6.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versión 6.2 del SnapCenter software incluye la siguiente característica nueva.

|===
| Actualizar | Descripción 


| link:../get-started/reference_supported_storage_systems_and_applications.html["Compatibilidad con los sistemas ASA R2"]  a| 
SnapCenter 6.2 (servidor y complementos) junto con ONTAP 9.17.1 admite la protección primaria y secundaria de aplicaciones que se ejecutan en sistemas físicos (Linux y Windows) y sistemas de archivos de máquinas virtuales (VMFS) utilizando grupos de consistencia jerárquicos.

Después de actualizar a SnapCenter 6.2 y ONTAP 9.17.1, SnapCenter cambia los grupos de consistencia planos a grupos de consistencia jerárquicos durante la primera copia de seguridad programada.

|===


== BlueXP ahora es NetApp Console

La consola NetApp , construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento NetApp y de los servicios de datos NetApp en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la consola de NetApp"^] .
