---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: La versión 6,0 del software SnapCenter incluye varias funciones y mejoras nuevas. 
---
= Novedades del software SnapCenter 6,0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La versión 6,0 del software SnapCenter incluye varias funciones y mejoras nuevas.

|===
| Actualizar | Descripción 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["Compatibilidad con el complemento de cargas de trabajo empresariales compatible con NetApp"]  a| 
SnapCenter proporciona complementos para gestionar cargas de trabajo como PostgreSQL, MySQL e IBM DB2. Es posible detectar automáticamente, realizar un backup, restaurar, montar y clonar las cargas de trabajo.

SnapCenter también proporciona complementos para gestionar cargas de trabajo como SAP ASE, SAP MaxDB, MongoDB, aplicaciones Oracle y almacenamiento de ONTAP. Es posible realizar backup, restaurar y clonar las cargas de trabajo.



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["Compatibilidad con la versión de Linux de SnapCenter tanto para cargas de trabajo en la nube como en las instalaciones"]  a| 
* Admite almacenamiento Azure NetApp Files, Amazon FSx para NetApp ONTAP, Cloud Volumes ONTAP y ONTAP.
* Binarios separados para los tipos de Linux, como Red Hat Enterprise Linux (RHEL), Oracle Linux y SUSE Linux Enterprise Server (SLES).
* Admite bases de datos clásicas como SAP HANA, Oracle, IBM DB2, SAP ASE y SAP MaxDB.
* Admite cargas de trabajo modernas como PostgreSQL, MySQL y MongoDB.
* Admite complementos para volúmenes ONTAP y sistemas de archivos Linux para proteger cualquier aplicación no compatible o de expansión interna.




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["Compatibilidad con Active Sync de SnapMirror"]  a| 
Capacidad para realizar backups, restauraciones y clones sin problemas cargas de trabajo SAN (bases de datos y equipos virtuales de VMware) configuradas para ofrecer conmutación al respaldo transparente de aplicaciones y continuidad empresarial.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["Compatibilidad con Microsoft SQL Server en SMB3"]  a| 
Las bases de datos de Microsoft SQL Server puestas en marcha en el protocolo SMB3 en ONTAP, Azure NetApp Files, Amazon FSx para NetApp ONTAP y Cloud Volumes de ONTAP ahora pueden protegerse con SnapCenter.



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["Compatibilidad con NVMe/TCP"]  a| 
Si va a migrar cargas de trabajo cruciales a NVMe/TCP para obtener un mejor rendimiento, puede utilizar SnapCenter para realizar backup y recuperar aplicaciones y sistemas de archivos.



| Compatibilidad con VMware vVols  a| 
Si ha implementado sus bases de datos y sistemas de archivos en VMware vVols, puede usar SnapCenter para protegerlas.

|===