---
permalink: protect-mysql/install-snapcenter-plug-in-packages-for-linux-or-windows-on-multiple-remote-hosts-using-cmdlets-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in Packages for Linux, SnapCenter Plug-in Packages for Windows 
summary: Puede instalar los paquetes de plugins de SnapCenter para Linux o Windows en varios hosts a la vez mediante el cmdlet de PowerShell Install-SmHostPackage. 
---
= Instale paquetes de plugins de SnapCenter para Linux o Windows en varios hosts remotos mediante cmdlets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede instalar los paquetes de plugins de SnapCenter para Linux o Windows en varios hosts a la vez mediante el cmdlet de PowerShell Install-SmHostPackage.

.Antes de empezar
Debe haberse registrado en SnapCenter como usuario del dominio con derechos de administrador local en cada host en el que desee instalar el paquete de plugins.

.Pasos
. Inicie PowerShell.
. En el host de SnapCenter Server, establezca una sesión mediante el cmdlet Open-SmConnection y, a continuación, introduzca sus credenciales.
. Instale el plugin en varios hosts mediante el cmdlet Install-SmHostPackage y los parámetros requeridos.
+
La información relativa a los parámetros que se pueden utilizar con el cmdlet y sus descripciones se puede obtener ejecutando _Get-Help nombre_comando_. Alternativamente, también puede consultar la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guía de referencia de cmdlets de SnapCenter Software"^].

+
Puede utilizar la opción -skipprecheck cuando haya instalado los plugins manualmente y no quiera validar si el host cumple los requisitos para instalar el plugin.

. Introduzca sus credenciales para la instalación remota.

