---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for mysql 
summary: 'SnapCenter es compatible con los tipos de restauración SnapRestore \(VBSR\) basados en volúmenes, SnapRestore de archivo único y conexión y copia para las bases de datos MySQL detectadas automáticamente.' 
---
= Tipos de operaciones de restauración para el MySQL autodetectado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El plugin de SnapCenter para MySQL es compatible con SnapRestore de archivos únicos, y los tipos de restauración por conexión y copia para las bases de datos MySQL detectadas automáticamente.



== Single File SnapRestore se realiza en entornos NFS en los siguientes casos:

* Si solo se selecciona la opción *Complete Resource*
* Cuando la copia de seguridad seleccionada se realiza desde una ubicación secundaria de SnapMirror o SnapVault y se selecciona la opción *completar recurso*




== Single File SnapRestore se realiza en entornos SAN en los siguientes casos:

* Si solo se selecciona la opción *Complete Resource*
* Cuando se selecciona la copia de seguridad de una ubicación secundaria de SnapMirror o SnapVault y se selecciona la opción *Complete Resource*

