---
permalink: protect-mysql/types-of-restore-strategies-supported-for-manually-added-mysql.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter. Existen dos tipos de estrategias de restauración para los recursos MySQL añadidos manualmente. No se pueden recuperar recursos MySQL añadidos manualmente. 
---
= Tipos de estrategias de restauración compatibles con los recursos de MySQL añadidos manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para poder ejecutar correctamente las operaciones de restauración, es necesario definir una estrategia mediante SnapCenter. Existen dos tipos de estrategias de restauración para los recursos MySQL añadidos manualmente.


NOTE: No se pueden recuperar recursos MySQL añadidos manualmente.



== Restauración de recursos completa

* Restaura todos los volúmenes, qtrees y LUN de un recurso



NOTE: Si el recurso contiene volúmenes o qtrees, las copias de Snapshot tomadas después de la copia de Snapshot seleccionada para restaurar en los volúmenes o qtrees se eliminan y no pueden recuperarse. Además, si hay algún otro recurso alojado en los mismos volúmenes o qtrees, también se lo elimina.
